### ISSUE TITLE
Probleme mit unterschiedlichen Icals.

### ISSUE THREAD

**Issue by THWillert** [naimo84/node-red-contrib-ical-events#1]
Hallo,

erstmal vielen Dank für den schönen Beitrag zu Node-RED.

Ich habe leider folgendes Problem damit:
Wenn ich verschiedene Quellen konfiguriere, dann wird immer nur die zuletzt angelegte in den Nodes abgefragt, egal welche "Config" ich auswähle.
Das heist msg.payload, von der Upcoming oder Event-Node, enthält immer nur die Daten der zuletzt angelegten Quelle.

Grüße
 Thorsten

**Comment by naimo84** [comment]
Hallo Thorsten,

vielen Dank für Dein Lob. Das freut mich.

Ich habe soeben Version 0.2.1 gepusht. Damit sollte das Problem behoben sein, hoffe ich. Falls nicht, bitte einfach nochmal melden. Static ist immer wieder problematisch ;)

Viele Grüße,
Benjamin

**Comment by THWillert** [comment]
Hallo Benjamin,

danke für die schnelle Behebung des Problems.
Nun funktioniert es wie gedacht.

Viele Grüße
 Thorsten
