### ISSUE TITLE
React or get the alarms

### ISSUE THREAD

**Issue by Edo78** [naimo84/node-red-contrib-ical-events#103]
**Is your feature request related to a problem? Please describe.**
I'd like to act on the alarms of an event

**Describe the solution you'd like**
An option in the `trigger` and `sensor` node to react to the alarm.

**Describe alternatives you've considered**
Parsing of `VALARM`  blocks should be pretty easy and return an array of alarms so that I can work on them in the flow.
eg.
```
BEGIN:VALARM
ACTION:EMAIL
DESCRIPTION:This is an event reminder
SUMMARY:Alarm notification
ATTENDEE:mailto:fakemail@fakedomain.com
TRIGGER:-P0DT0H10M0S
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT0H20M0S
END:VALARM
```
can be formatted as
```JSON
{
    "alarms":[
        {
            "action":"email",
            "description":"This is an event reminder",
            "attendee":"mailto:fakemail@fakedomain.com",
            "trigger":"-P0DT0H10M0S",
            "triggerParsed":"2021-10-14T14:00:00.000+02:00"
        },
        {
            "action":"display",
            "description":"This is an event reminder",
            "trigger":"-P0DT0H20M0S",
            "triggerParsed":"2021-10-14T13:50:00.000+02:00"
        }
    ]
}
```

**Comment by naimo84** [comment]
Hi @Edo78,

I'll have a look at it as soon as possible 😉

Greets
Benjamin

**Comment by naimo84** [comment]
Hey ho,

v1.3.0 should be online 😉
I close it for now, feel free to reopen it. 
And if you like the node, may you give it a star? 😊

Greets
Benjamin
