### ISSUE TITLE
Filter request

### ISSUE THREAD

**Issue by zedspells** [naimo84/node-red-contrib-ical-events#106]
Hi,
Would it be possible to add a 'filter by  location' option  in the filters  

Thanks
(thanks for this superb program)

**Comment by naimo84** [comment]
Hi @zedspells ,

v1.5.0 is on the way ;) locations-filter is hopefully correctly added ;)

Greets,
Benjamin

**Comment by zedspells** [comment]
Thank you for the update
really appreciate your work on this
