### ISSUE TITLE
Please publish updated npm package

### ISSUE THREAD

**Issue by unclej84** [naimo84/node-red-contrib-ical-events#107]
Hello,

I got notified that version 1.5.0 is released but npmjs and node-red flows still show 1.3.0 as latest version. Could you please publish the updated npm package?
Thanks in advance.

Regards Jörg

**Comment by naimo84** [comment]
Hi @unclej84, 

v1.5.0 is on the way. I've created the github release to early... I wanted to do some testing before the publishing ;)

Greets,
Benjamin
