### ISSUE TITLE
Starting point in ical-upcoming seems to be 1 month ahead

### ISSUE THREAD

**Issue by unclej84** [naimo84/node-red-contrib-ical-events#108]
**Describe the bug**
I fetched upcoming events and the first one was from 29.12. (today is 29.11.) but the next event is on the 06.12.. The preview time is set to 300days and the past view to 200s.

**To Reproduce**
1. create ical-upcoming node
2. have event within the next month
3. fetch events

**Expected behavior**
Start should be now or now - past view.

**node-red-contrib-ical-events
 - Version 1.5.0
 - node-red version 2.1.3
 - nodejs version 12

**Comment by naimo84** [comment]
I will have a look at it as soon as possible.
I changed some past and preview settings with the latest 1.5.0... obviously it does not work correctly.

Do you use a ical, icloud or Caldav Server?

**Comment by naimo84** [comment]
ah, from an old issue : caldav 👍

**Comment by naimo84** [comment]
I did a quick test with my nextcloud and my sogo caldav servers. Unfortunatelly I can't reproduce your error locally...

Can you perhaps try to do a DEBUG logging like described here: https://naimo84.github.io/node-red-contrib-ical-events/guide/debug.html

You can send me the output via mail if you don't wanna post it here ;)

**Comment by unclej84** [comment]
Will do it tomorrow, if this is okay for you.

**Comment by naimo84** [comment]
of course it's ok for me 😉 hopefully I can find the error tomorrow 👍

**Comment by unclej84** [comment]
Information are send via email - hope everything is included as needed.

**Comment by naimo84** [comment]
Many many thanks for your Mail, this confirms my fears, that the scrapegoat update 1.0->2.0 was the trigger...
Like here https://github.com/naimo84/node-red-contrib-ical-events/issues/109

v1.5.1 should be online 😉 

P.S. I'm replying to your Mail also later this day

**Comment by unclej84** [comment]
in 1.5.1 it is working as intended again - also the strange date output of 1.5.0 is gone (`date: 26.03.2022` [1.5.1] vs. `date: 03.04.2022 02:00-01:59` [1.5.0])

**Comment by unclej84** [comment]
> I will have a look at it as soon as possible. I changed some past and preview settings with the latest 1.5.0... obviously it does not work correctly.
> 
> Do you use a ical, icloud or Caldav Server?

Good that you added this to the bug template - I already forgot to add this information in the previous reports 😁

**Comment by naimo84** [comment]
> in 1.5.1 it is working as intended again - also the strange date output of 1.5.0 is gone (`date: 26.03.2022` [1.5.1] vs. `date: 26.03.2022 02:00-01:59` [1.5.0])
> 
> Edit: Did not receive any mail - is my server broken or did you forget/had no time?

I replied to your Mail yesterday... sorry, but it's really busy working days at the moment 😉
