### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by cubecell** [naimo84/node-red-contrib-ical-events#109]
**Describe the bug**
After the update to v1.5.0 the following error message appears: caldav - get calendar went wrong. Error Message: FetchError: request to ht<span>tps://</span>my-nextcloud-on-synology failed, reason: unable to verify the first certificate. Last working version: v1.3.0

Are there any TLS options ?

**node-red-contrib-ical-events
 - Version 1.5.0
 - node-red version 2.1.3
 - nodejs version 14.18.1

**Comment by naimo84** [comment]
Hi @cubecell,

unfortunatelly I didn't check an update of the CalDAV lib scrapegoat closelly enough...
They did indeed change the underlying request lib to cross-fetch and forgot to implement rejectUnauthorized...

https://github.com/peerigon/scrapegoat/pull/47

I will have to investigate some more, but as a quickfix I can publish a new ical-events with a downgraded scrapegoat lib ;)

Greets,
Benjamin

**Comment by naimo84** [comment]
v.1.5.1 should be online ;)

**Comment by cubecell** [comment]
Everything works again! Thanks!

**Comment by naimo84** [comment]
I'm pleased, it works again. Sorry for the circumstances ;)
