### ISSUE TITLE
Update 1.5.1 breaks my calendar events

### ISSUE THREAD

**Issue by ahartman** [naimo84/node-red-contrib-ical-events#110]
Dear naimo84,

Your update 1.5.1 breaks my flows that have worked ell for years. You may remember we communicated on this some years ago.
With 1.5.1, your upcoming node reports 'no events' for both calendars that I am tracking in secure mode.
An hour ago, everything was running fine.

I uninstalled 1.5.1 and re-installed 1.5.0 but that no also no longer works.
I clearly remember how difficult this was in original getting it to work; I hope I do not have to go through that again!
We use the system to control the lighting and electric door lock in our medial practice.

Regards, ahartman, belgium.

**Comment by naimo84** [comment]
Dear @ahartman,

sorry for the big mistake on my side... I'll add an unittest for this... I mixed up the order of preview and pastview in the icloud code and didn't check if it's still working. 

v1.5.2 is on the way. It hopefully will fix it again.

Greets,
Benjamin

**Comment by ahartman** [comment]
Dear Benjamin,

Thank you for the quick reaction .
I guest we will open the door by hand for a couple of day while waiting for 1.5.2.


Met vriendelijke groeten, Kind regards, Meilleures salutations,
André Hartman

**Comment by naimo84** [comment]
It should be available already 

![image](https://user-images.githubusercontent.com/11535502/144378236-2dbe46fc-c689-46cd-8cb5-aaf09d01dd17.png)

**Comment by ahartman** [comment]
Dear Benjamin,

1.5.2 fixed the issue and produces events again.
Something changed since the function node following the upcoming events now now no longer works as intended.
That will be easy to find.
Thank you for now.

Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by naimo84** [comment]
Dear André,

I will try to implement a json comparing method in a github action. It was not intended to change the output ;)

Greets,
Benjamin

**Comment by ahartman** [comment]
Dear Benjamin,

I found the issue. I changed the output timezone from UTC to Europe/Brussels. The following function node cannot use the resulting formatted time, so I changed it back to UTC en everything is fine again.




Met vriendelijke groeten, Kind regards, Meilleures salutations,
André Hartman
