### ISSUE TITLE
Upcoming output is empty.

### ISSUE THREAD

**Issue by mikko80** [naimo84/node-red-contrib-ical-events#111]
Configured ical file is ok but Upcoming events output is empty. Debug shows some dates go too far to future.

URL: https://www.webcal.guru/fi-FI/lataa_kalenteri?subscription_id=80a8d0835c478652decee59877ba0288
Type: ical

Output: {"payload":[],"topic":"","_msgid":"992a2bf860fad3ac","today":0,"tomorrow":0,"total":0,"htmlTable":"<span></span>"}

**node-red-contrib-ical-events
 - Version 1.5.2
 - node-red version 2.1.3
 - nodejs version 12.22.7
 - is it an ical

debug:
 kalender-events getCal - ical +0ms
  kalender-events getCal - ical +5ms
  kalender-events getCal - ical +1ms
  kalender-events {
  kalender-events   version: { params: { VALUE: 'TEXT' }, val: '2.0' },
  kalender-events   prodid: {
  kalender-events     params: { VALUE: 'TEXT' },
  kalender-events     val: '-//WebCal.Guru//NONSGML WebCal.Guru//FI'
  kalender-events   },
  kalender-events   calscale: { params: { VALUE: 'TEXT' }, val: 'GREGORIAN' },
  kalender-events   method: { params: { VALUE: 'TEXT' }, val: 'PUBLISH' },
  kalender-events   name: { params: { VALUE: 'TEXT' }, val: 'Viikkonumerot' },
  kalender-events   'WR-CALNAME': { params: { VALUE: 'TEXT' }, val: 'Viikkonumerot' },
  kalender-events   source: {
  kalender-events     params: { VALUE: 'URI' },
  kalender-events     val: 'https://www.webcal.guru/fi-FI/lataa_kalenteri?subscription_id=80a8d0835c478652decee59877ba0288'
  kalender-events   },
  kalender-events   url: {
  kalender-events     params: { VALUE: 'URI' },
  kalender-events     val: 'https://www.webcal.guru/fi-FI/tapahtumalista?subscription_id=80a8d0835c478652decee59877ba0288'
  kalender-events   },
  kalender-events   uid: {
  kalender-events     params: { VALUE: 'TEXT' },
  kalender-events     val: '1298566E-25E3-46A4-AEFD-807014F2A10D@webcal.guru'
  kalender-events   },
  kalender-events   'WR-RELCALID': {
  kalender-events     params: { VALUE: 'TEXT' },
  kalender-events     val: '1298566E-25E3-46A4-AEFD-807014F2A10D@webcal.guru'
  kalender-events   },
  kalender-events   description: {
  kalender-events     params: { VALUE: 'TEXT', LANGUAGE: 'fi' },
  kalender-events     val: 'Viikkojen numerointi europpalaisen, amerikkalaisen tai lähi-idän standardin mukaan.'
  kalender-events   },
  kalender-events   'WR-CALDESC': {
  kalender-events     params: { VALUE: 'TEXT', LANGUAGE: 'fi' },
  kalender-events     val: 'Viikkojen numerointi europpalaisen, amerikkalaisen tai lähi-idän standardin mukaan.'
  kalender-events   },
  kalender-events   'WR-TIMEZONE': { params: { VALUE: 'TEXT' }, val: 'UTC' },
  kalender-events   'refresh-interval': { params: { VALUE: 'DURATION' }, val: 'P1W' },
  kalender-events   'PUBLISHED-TTL': { params: { VALUE: 'DURATION' }, val: 'P1W' },
  kalender-events   OWNER: {
  kalender-events     params: { VALUE: 'TEXT', CN: 'WebCal.Guru' },
  kalender-events     val: 'mailto:guru@webcal.guru'
  kalender-events   },
  kalender-events   color: { params: { VALUE: 'TEXT' }, val: '#929292' },
  kalender-events   'APPLE-CALENDAR-COLOR': { params: { VALUE: 'TEXT' }, val: '#929292' },
  kalender-events   'OUTLOOK-COLOR': { params: { VALUE: 'TEXT' }, val: '#929292' },
  kalender-events   'FUNAMBOL-COLOR': { params: { VALUE: 'TEXT' }, val: '#929292' },
  kalender-events   'LOTUS-CHARSET': { params: { VALUE: 'TEXT' }, val: 'UTF-8' },
  kalender-events   '[object Object]': {
  kalender-events     type: 'VEVENT',
  kalender-events     params: [],
  kalender-events     uid: {
  kalender-events       params: [Object],
  kalender-events       val: 'C04159F9-1D1C-42DD-A5E3-6CFB5E06194A@webcal.guru'
  kalender-events     },
  kalender-events     'FUNAMBOL-ALLDAY': '1',
  kalender-events     'MICROSOFT-CDO-ALLDAYEVENT': 'TRUE',
  kalender-events     start: 2022-05-22T21:00:00.000Z { tz: undefined, dateOnly: true },
  kalender-events     datetype: 'date',
  kalender-events     end: 2022-05-29T21:00:00.000Z { tz: undefined, dateOnly: true },
  kalender-events     summary: { params: [Object], val: 'Viikko 21' },
  kalender-events     description: {
  kalender-events       params: [Object],
  kalender-events       val: 'Päivitetty: Sat, 27 Nov 2021 01:27:04 +0000\n' +
  kalender-events         '\n' +
  kalender-events         'Muokkaa tilausta\n' +
  kalender-events         'https://www.webcal.guru/fi-FI/omat_kalenterit?subscription_id_hex=80a8d0835c478652decee59877ba0288\n' +
  kalender-events         '\n' +
  kalender-events         'Tämän kalenterin tarjoaa WebCal.Guru (https://www.webcal.guru/).'
  kalender-events     },
  kalender-events     class: { params: [Object], val: 'PUBLIC' },
  kalender-events     contact: { params: [Object], val: 'guru@webcal.guru' },
  kalender-events     transparency: { params: [Object], val: 'TRANSPARENT' },
  kalender-events     'MICROSOFT-CDO-BUSYSTATUS': 'FREE',
  kalender-events     'APPLE-TRAVEL-ADVISORY-BEHAVIOR': { params: [Object], val: 'DISABLED' },
  kalender-events     status: { params: [Object], val: 'CONFIRMED' },
  kalender-events     priority: { params: [Object], val: '5' },
  kalender-events     sequence: { params: [Object], val: '1062' },
  kalender-events     created: 2021-11-27T01:27:04.000Z { tz: undefined },
  kalender-events     lastmodified: 2021-11-27T01:27:04.000Z { tz: undefined },
  kalender-events     dtstamp: 2021-11-27T01:27:04.000Z { tz: undefined }
  kalender-events   },
  kalender-events   lastmodified: 2021-11-27T01:27:04.000Z { tz: undefined }
  kalender-events } +285ms
  kalender-events getEvents - pastview: Thu Dec 02 2021 00:00:00 GMT+0200 +26ms
  kalender-events getEvents - preview: Thu Dec 02 2021 23:59:59 GMT+0200 +1ms
  kalender-events processDataRev - event: {"date":"23.05.2022 00:00-00:00+6","eventStart":"2022-05-22T21:00:00.000Z","eventEnd":"2022-05-29T21:00:00.000Z","summary":{"params":{"VALUE":"TEXT","LANGUAGE":"fi"},"val":"Viikko 21"},"description":{"params":{"VALUE":"TEXT","LANGUAGE":"fi"},"val":"Päivitetty: Sat, 27 Nov 2021 01:27:04 +0000\n\nMuokkaa tilausta\nhttps://www.webcal.guru/fi-FI/omat_kalenterit?subscription_id_hex=80a8d0835c478652decee59877ba0288\n\nTämän kalenterin tarjoaa WebCal.Guru (https://www.webcal.guru/)."},"durationSeconds":0,"uid":{"uid":{"params":{"VALUE":"TEXT"},"val":"C04159F9-1D1C-42DD-A5E3-6CFB5E06194A@webcal.guru"},"date":"1653253200000"},"isRecurring":false,"datetype":"date","allDay":true,"calendarName":null} +0ms
  kalender-events checkDates - event: {"date":"23.05.2022 00:00-00:00+6","eventStart":"2022-05-22T21:00:00.000Z","eventEnd":"2022-05-29T21:00:00.000Z","summary":{"params":{"VALUE":"TEXT","LANGUAGE":"fi"},"val":"Viikko 21"},"description":{"params":{"VALUE":"TEXT","LANGUAGE":"fi"},"val":"Päivitetty: Sat, 27 Nov 2021 01:27:04 +0000\n\nMuokkaa tilausta\nhttps://www.webcal.guru/fi-FI/omat_kalenterit?subscription_id_hex=80a8d0835c478652decee59877ba0288\n\nTämän kalenterin tarjoaa WebCal.Guru (https://www.webcal.guru/)."},"durationSeconds":0,"uid":{"uid":{"params":{"VALUE":"TEXT"},"val":"C04159F9-1D1C-42DD-A5E3-6CFB5E06194A@webcal.guru"},"date":"1653253200000"},"isRecurring":false,"datetype":"date","allDay":true,"calendarName":null} +1ms
  kalender-events getEvents - processedData: [] +1ms

**Comment by naimo84** [comment]
Hi @mikko80,

the lib I'm using (node-ical), is having some issues with that, as you can see here (https://github.com/jens-maus/node-ical/issues/169). I'll upgrade as soon as an update is out ;)

Regards,
Benjamin

**Comment by naimo84** [comment]
Hi @mikko80,

v2.0.1 is online. May you test this version? :)
Temporally I implemented this functionality on my own 👍 

Greets,
Benjamin

**Comment by mikko80** [comment]
V2.0.1 Fix this issue. Now this is working good! 

Happy holidays!
-Mikko

**Comment by naimo84** [comment]
nice to hear it's working 😊
happy holidays! 

Benjamin
