### ISSUE TITLE
v2.0.0 fails with missing - kalender-events/dist/windowsZones.json

### ISSUE THREAD

**Issue by RogerSelwyn** [naimo84/node-red-contrib-ical-events#113]
**Describe the bug**
Version 1.5.3 works fine, but the upgrade to v2.0.0 has caused my calls to Upcoming node to fail

**To Reproduce**
I'm using Node Red add-on for Home Assistant. Upcoming node is configured to retrieve ics events from O365 calendar. Error generated is as shown below.

**Expected behavior**
No error to be generated

**Screenshots**
n/a

**node-red-contrib-ical-events
 - Version - 2.0.0
 - node-red v16.13.1, 5pm version 8.1.3
 - nodejs - not sure
 - o365 ics

**Logs / Additional context**
```
Error: Cannot find module '/opt/node_modules/node-red-contrib-ical-events/node_modules/kalender-events/dist/windowsZones.json'
Require stack:
- /opt/node_modules/node-red-contrib-ical-events/node_modules/kalender-events/dist/ical.js
- /opt/node_modules/node-red-contrib-ical-events/node_modules/kalender-events/dist/caldav.js
- /opt/node_modules/node-red-contrib-ical-events/node_modules/kalender-events/dist/lib.js
- /opt/node_modules/node-red-contrib-ical-events/node_modules/kalender-events/dist/index.js
- /opt/node_modules/node-red-contrib-ical-events/dist/helper.js
- /opt/node_modules/node-red-contrib-ical-events/dist/ical-events.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
```

You can send me a debug log, like described here: https://naimo84.github.io/node-red-contrib-ical-events/guide/debug.html

**Comment by RogerSelwyn** [comment]
I should add, reverting to v1.5.3 returned it to a working state.

**Comment by naimo84** [comment]
Sorry for the inconveniences... I have to setup an unittest for o365/outlook as soon as possible...

v2.0.1 should be in the way

![image](https://user-images.githubusercontent.com/11535502/146835718-4caee44c-ecdd-4e74-942d-5abf6bef728d.png)

**Comment by RogerSelwyn** [comment]
No problem, I do my own development, it's never perfect 🤩

**Comment by RogerSelwyn** [comment]
That seems to have fixed it.

**Comment by naimo84** [comment]
there are soooo many different calender types 😉 and even it's a RFC "standard", every tool/program is interpreting it differently 😋

Best regards,
Benjamin

**Comment by RogerSelwyn** [comment]
Yep, did some ical open source stuff back on a platform called dotnetnuke about 15 years ago. Complex stuff....  Makes your head spin dealing with multi-time zone stuff and the weirdness of DST.
