### ISSUE TITLE
Error in 2.0.0 and 2.0.1

### ISSUE THREAD

**Issue by ahartman** [naimo84/node-red-contrib-ical-events#114]
Dear Benjamin,

I updated this morning to 2.0.0 and got "Error: no data" instead of events.
Then I noticed a newer 2.0.1 and installed that version, no error any more but also no incoming events.
I went to all the way back to 1.5.0 after that and also no events.
Any ideas?

Regards, ahartman, belgium

**Comment by naimo84** [comment]
Oh no André 😐 I have no idea, what's going wrong with the iCloud Part of my kalender-events lib 😐

May you try v1.5.2 please?

**Comment by naimo84** [comment]
I did a quick test with both (2.0.0 and 2.0.1). Both are working locally and the unit test in the github action also seems to work...

I will discontinue my work with ical events.... Every version something else is broken :/

You can send me a debug log, like described here: https://naimo84.github.io/node-red-contrib-ical-events/guide/debug.html

**Comment by naimo84** [comment]
It's really really strange. It tested it with 4 node-red installations with some combinations of node-red version, nodejs version and ical-events version. All seems to be ok.... So one way will be the debug log. Sorry for the inconveniences.

**Comment by naimo84** [comment]
A type of undocumented feature of my lib kalender-events is a cli interface. Perhaps you may try this also? 

```sh 
DEBUG=kalender-events npx kalender-events  upcoming --type icloud  --preview P10D --pastview P10D --url **https://p51-caldav.icloud.com/123456789/calendars/home/**  --username **andre@example.com** --password **abcd-efgh-ijkl-mnop** 
```

The only occurrence of ``throw new Error("No data")`` is directly after the request call of 'https://p51-caldav.icloud.com/123456789/calendars/home/'. This means it's something wrong with the icloud request. Wrong url, username or password...

**Comment by ahartman** [comment]
Benjamin,

I will try this and let you know.
I do not agree every version of your node something is broken.
Your node has worked me for almost two years without any problem at all.

But changing software is a delicate operation for all of us.
The latest versions did create some issues, I can only agree.

Met vriendelijke groeten, Kind regards, Mes meilleures salutations, Freundliche Grüße
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by ahartman** [comment]
Benjamin,

I used your DEBUG trick and the result is below:

kalender-events packageJson version: 0.23.0 +0ms
  kalender-events getCal - icloud +6ms
  kalender-events:icloud requestIcloudSecure - options: {"hostname":"p31-caldav.icloud.com","port":"443","path":"/223639751/calendars/351E54A9-85EC-4AD6-A100-0B1435502C5F/**","method":"REPORT","headers":{"Content-type":"application/xml","Content-Length":394,"User-Agent":"calDavClient","Connection":"close","Depth":"1"}} +0ms
  kalender-events:icloud requestIcloudSecure - xml: <?xml version="1.0" encoding="utf-8" ?>
  kalender-events:icloud <C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  kalender-events:icloud   <D:prop>
  kalender-events:icloud     <C:calendar-data/>
  kalender-events:icloud   </D:prop>
  kalender-events:icloud   <C:filter>
  kalender-events:icloud     <C:comp-filter name="VCALENDAR">
  kalender-events:icloud       <C:comp-filter name="VEVENT">
  kalender-events:icloud         <C:time-range start="20211213T00000Z" end="20220102T06280Z" />
  kalender-events:icloud       </C:comp-filter>
  kalender-events:icloud     </C:comp-filter>
  kalender-events:icloud   </C:filter>
  kalender-events:icloud </C:calendar-query> +1ms
  kalender-events Error: No data
  kalender-events     at ClientRequest.<anonymous> (/home/pi/.npm/_npx/17894/lib/node_modules/kalender-events/dist/icloud.js:75:31)
  kalender-events     at ClientRequest.emit (events.js:400:28)
  kalender-events     at TLSSocket.socketCloseListener (_http_client.js:434:9)
  kalender-events     at TLSSocket.emit (events.js:412:35)
  kalender-events     at net.js:686:12
  kalender-events     at TCP.done (_tls_wrap.js:564:7) +231ms
Error: No data
    at ClientRequest.<anonymous> (/home/pi/.npm/_npx/17894/lib/node_modules/kalender-events/dist/icloud.js:75:31)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketCloseListener (_http_client.js:434:9)
    at TLSSocket.emit (events.js:412:35)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7)

Regards, ahartman, belgium

**Comment by naimo84** [comment]
Hi Andre,

Thanks for sharing the debug log. I've removed the Basic Auth Header for you ;) 
But: I tested it with this this Username /Password and I'm getting an "Unauthorized" error with this at the very first request of my logic.

Maybe your application password is expired? Does apple offer such an option?

Greets,
Benjamin

**Comment by ahartman** [comment]
Benjamin,
As far as I know app-specific passwords do not expire; anyway, I created a new one recently.
I used your curl command and that works fine, see 'Terminal 1'; I can also retrieve all calendars, see 'Terminal 2'.
I do not know the curl command to effectively retrieve events from a calendar, so I could not test that.
Regards, ahartman, belgium

[Terminal 1.txt](https://github.com/naimo84/node-red-contrib-ical-events/files/7773013/Terminal.1.txt)

[Terminal 2.txt](https://github.com/naimo84/node-red-contrib-ical-events/files/7773014/Terminal.2.txt)

**Comment by naimo84** [comment]
Good Morning,

with this new password kalender-events is working on my side.

![image](https://user-images.githubusercontent.com/11535502/147327478-38e430be-b244-4553-a919-a33f5a2d0ef6.png)

If it's not working on your side, I only can implement more debug infos to find the error.

Happy Christmas anyway 😉 

Benjamin

**Comment by ahartman** [comment]
Benjamin,

It works for me now as well!

What I noticed is that I was using ***@***.*** in the node configuration.
Apple has used several domain names over the years and they are supposed to all resolve the some ‘icloud’ domain.
I changed ***@***.*** to ***@***.*** and that solved the issue.

I suspect maybe Apple is trying to phase out some of the old domain names.

So, all is well again.

"Fröhliche Weihnachten und einen guten Rutsch ins neue Jahr”, wünsche ich dir.



Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by naimo84** [comment]
Dear André, 
very very strange behaviour of icloud.
but nice to hear, it's working again 👍👍👍

I hope it's the last issue for some time 😉

otherwise it's always a pleasure to write with you 👍

"Dankeschön, ich wünsche dir auch ein schönes Weihnachtsfest und einen guten Rutsch ins Neue Jahr."

Grüße aus Bayern
Benjamin

P. s. I'll close this issue for now, feel free to reopen it 😊

**Comment by naimo84** [comment]
@ahartman : be careful 😉 i published a new version 😐

**Comment by ahartman** [comment]
Dear Benjamin,

I just upgraded your node - after backing up - and I note an issue.
I have always filtered in your node with a	regular expression the nodes that are of interest to me; see attached image.
That no longer works, the latest version now passes all events in that calendar for that day.

So, I am happy that I have the backup!

Regards, ahartman, belgium

**Comment by naimo84** [comment]
Dear André,

I knew it... I've double checked (triple checked) my code... But I have definitely not changed the logic with the regular expressions :(
Unfortunately it's working again on my side, with my icloud and with 

![image](https://user-images.githubusercontent.com/11535502/152308431-a954f2de-acaa-426d-b1f5-2ac66d95c8a1.png)

I can't see your image attached. May you re-upload it perhaps?

Backing up before any of my updates is always a good idea ;)

Greets,
Benjamin

**Comment by ahartman** [comment]
Benjamin,

Please find my image attached.
I will play around with the node to see if gets back to its old ways.

Regards, André Hartman

**Comment by naimo84** [comment]
André, 

I think you have to upload it via the github website. Answering via mail seems not to upload any image ;)

Thanks and regards,
Benjamin

**Comment by ahartman** [comment]
<img width="498" alt="Schermafbeelding 2022-02-03 om 11 27 14" src="https://user-images.githubusercontent.com/688316/152325037-131a8bca-1a05-4c92-835d-728d53f0a695.png">

**Comment by naimo84** [comment]
I tried a update from 1.5.6 and from 2.0.2 to v2.1.1 and this doesn't happen to me ... I also have no idea... Sorry
