### ISSUE TITLE
Use DUE attribute in VTODO entries

### ISSUE THREAD

**Issue by Programie** [naimo84/node-red-contrib-ical-events#115]
**Describe the bug**
The ical-events node only triggers for VTODO entries with a start or end date (DTSTART or DTEND). But in my case, I use the DUE property to define the time at which a task should be done. Also, I would expect that the ical-events node triggers a message once the due date/time has been reached.

**To Reproduce**
1. Create a task with a due date in the future
2. Let the ical-events find the task
3. The node does not trigger once the due date has been reached

**Expected behavior**
Trigger a message at the output of the ical-events node once the due date/time has been reached. I would expect it at the "End message" output.

**node-red-contrib-ical-events
 - Version 2.0.2
 - Node-RED v2.1.5
 - nodejs version v14.18.2
 - Using Nextcloud 22 as CalDAV server

**Comment by naimo84** [comment]
Hey Michael,

I think I got what you mean 👍 

So you're defining the todos like this?

![image](https://user-images.githubusercontent.com/11535502/149658949-6f44df4d-8802-4271-b1ff-7728795dd881.png)

Without a DTSTART?

Then the eventStart should also be the due date? Currently it's just "now" if nothing is defined ;)

Greets,
Benjamin

P.S. I didn't forget your other issue. 

I thought about something like this?

![image](https://user-images.githubusercontent.com/11535502/149659042-1cca3c31-2f07-47d3-94fc-15691707a7e4.png)

**Comment by Programie** [comment]
Thanks for the quick response!

Yes to both questions: I simply define the due date for a task in Nextcloud which doesn't trigger the node in Node-RED.

And about the other issue: Yes, looks exactly like what I need.

Would be really cool if you could implement both requests. :+1:

**Comment by naimo84** [comment]
Hey @Programie ,

may you wanna try a beta version as well? https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v2.1.0-beta.3/node-red-contrib-ical-events-2.1.0-beta.3.tgz

I've changed a lot of things in the frontend of the nodes, so I'm afraid something is broken and don't wanna push it to flows.nodered.org before anyone else than myself has tested it ;)

Greets,
Benjamin

**Comment by Programie** [comment]
I've tested the new beta version and the node is now correctly triggering a new event once the due date/time has been reached.

Thanks for the fast implementation!

**Comment by naimo84** [comment]
Thanks again for testing. I will publish the "real" 2.1.0 as soon as possible. Currently I'm at work ;)

I'll close this issue for now then
