### ISSUE TITLE
UK Time Zone & date format

### ISSUE THREAD

**Issue by zedspells** [naimo84/node-red-contrib-ical-events#121]
Hi, I had been using v1.5.3 and updated to 2.1.1 -  but now have a problem with time zone.
my Calendar event is set for
Time 11:00 and date 31/01/2022 (UK format)
but the imported data is showing as 
Time 10:00  and date  01/31/2022 (USA format)
I am in the UK and have Time Zone  set as Europe/London (same setting as previous ver)
It looks like its not setting UK daylight saving & using American date format.  Like its not using the Time zone setting
Not sure if I am missing something
Thanks

**Comment by naimo84** [comment]
Hi @zedspells ,

do you mean the date property or the eventStart/eventEnd properties? Do you have a screenshot, perhaps?
I've change some time formating, so you're not missing something. It's definitely my code ;)

Greets,
Benjamin

**Comment by zedspells** [comment]
![Ical timezone](https://user-images.githubusercontent.com/94933079/151871004-a2a2a29f-ae25-4f0d-9678-aabc2f70866c.png)
Hope this helps 
Thanks

**Comment by zedspells** [comment]
In my calendar  Start is 10:00 & End is 10:30
In Node red       Start is 09:00 & End is 09.30

In Node red ical Date format is 1/31/2022 (but I have timezone set as Europe/London) 
Date format should be 31/01/2022
Hope this makes a  it more sense

**Comment by naimo84** [comment]
Perfect, thanks for sharing 👍 
I'll try to reproduce this tomorrow 😉

**Comment by naimo84** [comment]
Good morning, 

so for the date property I can provide a solution ;) I definitely published the last version of the node to early.... sorry for that.
background: displaying a time range  on your own in javascript is real pain... so I decided to use https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat, but forgot to hand out options correctly to the nodes.

The option are a JSON object ( e.g. the example from the screenshot below dateformat = { timeStyle: "short", dateStyle: "short" }), so what do you think? Is it a better idea to make an input which contains the JSON object, or making a lot of input fields, which contains dateStyle, timeStyle and so on?

This leads me to the second issue: I can't reproduce the error with eventStart/eventEnd 😞 
![image](https://user-images.githubusercontent.com/11535502/151917685-39000876-bbf3-4026-b05e-0a0b9881e267.png)

The first one was with timezone Europe/London, the second input with Europe/Berlin.

Would it be possible to send me your calendar data and the flow json via email? Would be a lot easier to debug for me 👍 
I'll keep it secret!

Greets,
Benjamin

**Comment by zedspells** [comment]
Hi, just a quick update - after selecting a different time zone as in your example (i.e. Berlin) which seemed to correct the Start/End Event time - I changed it back to London and it is now working as expected.
1st Feb 2022 is still displaying the American Date format  2/1/2022 instead of UK Date format  
Ver 1.5.3 was working as 01/02/2022 which was perfect
it's the (payload[0].date) as shown in the debug
Best Regards

**Comment by naimo84** [comment]
Hi, and sorry. Yesterday was my nephews fifth birthday party in the afternoon. I didn't have the time to test the upgrade from 1.5 to 2.1. But it seems that there something broken. Sorry for any inconveniences, but many thanks for testing and pointing me out the problem 👍 

For the UK--> American Date format I handed out the formatting options like this: 

![image](https://user-images.githubusercontent.com/11535502/152039476-39989f40-cf68-48f8-8aec-af1fdeb5a55f.png)

Please have a look at the bottom (Dateformat and Language). Now you can format the date output in many ways: 
{ "timeStyle": "short", "dateStyle":"short" } --> 01/02/2022, 10:00–12:00 (**default**)
{ "timeStyle": "long", "dateStyle":"long" } --> 1 February 2022, 10:00:00 CET – 12:00:00 CET
{ "dateStyle":"long" } --> 1 February 2022
{ "dateStyle":"medium" } --> 1 Feb 2022

What do think about it?

**Comment by zedspells** [comment]
Hi, this looks great - it will cover all options - thanks

**Comment by naimo84** [comment]
hey,

v2.2.0 is online 😉

Greets
Benjamin
