### ISSUE TITLE
[QUESTION]: trying to figure out how to use this

### ISSUE THREAD

**Issue by jschwalbe** [naimo84/node-red-contrib-ical-events#122]
I am trying to figure out a way to more easily change the *times* that certain node-red events fire. For example, my morning routine normally goes off at 7:00. Sometimes I would like it to go off earlier, later, or skip the day. 
My thought is this:
1. set up a recurring event in ical (i.e. "morning routine" at 7:00)
2. use the ical-events node to somehow trigger the morning routine
3. change the time as needed and repeat

Which of the three nodes would be best for this? Thanks

**Comment by naimo84** [comment]
Hi @jschwalbe,

I can share my daily morning routine for HomeWorking days. 

https://naimo84.github.io/kalender-events/guide/nodered.html#homeworking-daily-alarm-in-the-morning

changing the time itself will be hard ;)

Please let me know if you need any more informations.

Greets, 
Benjamin

**Comment by jschwalbe** [comment]
That's great! I'm a little hazy on the trigger vs sensor node, but I think what I want is really just the trigger. Thank you
