### ISSUE TITLE
Different calendars report different UTC times

### ISSUE THREAD

**Issue by ahartman** [naimo84/node-red-contrib-ical-events#123]
Benjamin,
I just read issue 119. That seems very complex if you have different passwords for each calendar as in Include secure mode.
I solved this long time ago; I use an upcoming node for each calendar, set the results of the first in a flow variable, retrieve that while processing the second calendar and concatenate but calendar outputs!

But the above is not my issue. I stumble on something weird as I am trying to improve my logic handling the calendar events. See attached images. I have two events for test in two iCloud calendars, both on default timezone UTC.

<img width="121" alt="Schermafbeelding 2022-02-08 om 11 05 55" src="https://user-images.githubusercontent.com/688316/152965082-f4981e5f-024f-4212-8b06-e4666b63412f.png">

I use your upcoming node with different configs for calendar 1 and 2.
The Test 1 event at 0900 local time is reported at 0700UTC, 2 hours difference.
The Test 2 event at 9000 local time is reported at 0800UTC, 1 hour difference.

However, both events produce the correct local time for the 'within' node. My only problem is I need to sort events at the start when I only have the UTC time; that sort is therefore wrong.

<img width="423" alt="Schermafbeelding 2022-02-08 om 11 08 53" src="https://user-images.githubusercontent.com/688316/152965597-b3bc2db7-e25a-45b2-9558-7f85841e9811.png">

Any ideas?
Regards, André

**Comment by naimo84** [comment]
Dear André,

currently issue #119 will only be available for "normal" calDav Server ;) I also thought of implementing this for "icloud secure", but as you said, I've no idea how to handle the different passwords nicely...

regards to your timezone difference, I only know the icloud.com option for time zone directly at the event. 

![image](https://user-images.githubusercontent.com/11535502/152978290-cb65689f-3ffe-40a3-b5c9-5d13cb113f45.png)

It seems, that both are at the same time, but they are reported as 11:00 and 20:00 UTC

![image](https://user-images.githubusercontent.com/11535502/152978498-01499062-d7ec-4516-88ed-2b05a1e95a4d.png)

Maybe that's the problem? 

Otherwise the debug log would be useful :) Please be aware of the basic password. You can send me it via mail 👍 

Greets,
Benjamin

**Comment by ahartman** [comment]
Benjamin,

Time zone support is not enabled in my calendars; so, I do not see the time zone field in a new entry that you see.
Somehow, the two calendars internally seem to be in different timezones. The end result is OK, I can only not sort on the internal UTC times.

This is not an issue of your nodes, they only report what they read in the calendars.

So, I will go and try to sort my events in some other way.

Regards, André

**Comment by naimo84** [comment]
André, 

this looks really strange. I can't imagine how this happens. But I'll keep trying to find out why.
Can you find a tzid field in the array?

This is how it looks for my test events from above:
![image](https://user-images.githubusercontent.com/11535502/153054160-c8c360b8-7a62-4ac4-8374-918002ed0c53.png)

Regards,
Benjamin

**Comment by naimo84** [comment]
Perhaps the debug output will give us more informations ;) 

It will show us the ical Data like this 

```
BEGIN:VCALENDAR
X-WR-CALNAME:test-EU
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//caldav.icloud.com//CALDAVJ 2207B638//EN
BEGIN:VEVENT
DTSTAMP:20220208T110043Z
SUMMARY:test-EU
TZID:Europe/Berlin
SEQUENCE:0
UID:024526F8-6056-4C56-A9B9-E800780B3CBB
CREATED:20220208T110043Z
DTSTART;TZID=Europe/Berlin:20220208T120000
DTEND;TZID=Europe/Berlin:20220208T130000
TRANSP:OPAQUE
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
END:VTIMEZONE
END:VCALENDAR    
```

But nevertheless I can't imagine, why the tzids should be different from dtstart to dtend...

**Comment by naimo84** [comment]
André,

in some way this is funny ;)

the ics file looks correct, the tzid is correct, eventStart/end is correct now as they are UTC.

I have no idea, why yesterday is was an other result... Yesterday you triggered past 12 o'clock, today before 12. But this would be "really funny", if it's a timebased problem

**Comment by ahartman** [comment]
Benjamin,
Good morning, the eventStart and eventEnd are this morning even more weird. EventStart is one hour too early and eventEnd one hour too late!

As example I give you an appointment for this morning 0800-0900, please observe the .ics file as .txt.

[Papa Julien.txt](https://github.com/naimo84/node-red-contrib-ical-events/files/8038773/Papa.Julien.txt)

The next image displays the output from the upcoming node, eventSart and end are wrong, dtstart and dtend and the associated time zones are OK.

<img width="298" alt="Schermafbeelding 2022-02-10 om 07 56 23" src="https://user-images.githubusercontent.com/688316/153355164-4350470e-c49e-4a20-bfa7-2c9830cfe235.png">


The weird thing is that in the end correct datetimes are produced. The 'within node' display a start time of 0700; that is as intended as we open the door 1 hour before the first appointment of 080-0900.

<img width="174" alt="Schermafbeelding 2022-02-10 om 08 01 15" src="https://user-images.githubusercontent.com/688316/153355451-58728088-55a4-41be-8ef5-ede8c56b80cc.png">

Next, I tried the other calendar that I access in NodeRed. Events in that calendar do not display the eventStart, eventEnd issue.

<img width="296" alt="Schermafbeelding 2022-02-10 om 08 14 15" src="https://user-images.githubusercontent.com/688316/153356672-746c0e79-de07-41f3-a9be-a30077c8fe3b.png">

Regards, André

**Comment by ahartman** [comment]
Benjamin,

I am trying to dig out the original dtstart and dtend values out of the array in originalEvent.components. However, array[1] gives 'undefined'. Asking for the keys of that array gives the weird result ["jcal", et cetera] as in the image below. I am really lost here. Can you explain to me how to retrieve dtstart and dtend?

<img width="297" alt="Schermafbeelding 2022-02-10 om 10 26 58" src="https://user-images.githubusercontent.com/688316/153378364-54ce29e4-31d2-4824-b292-adb8041ed878.png">


Regards, Andre

**Comment by ahartman** [comment]
Benjamin,

I managed to extract dtstart and dtend but in a roundabout sort of way:

let tempArray = []
let tempBlok = {}

consultaties = flow.get("consultaties").concat(msg.payload)
consultaties = consultaties.filter(event => event.allDay !== true)
consultaties.forEach(function (consultatie) {
    component = consultatie.originalEvent.component
    components = Object.entries(component)
    elements = components[0][1][1]

    for (const element of elements) {
        if (element[0] == "dtend") {
            dtend = element[3]
        }
        if (element[0] == "dtstart") {
            dtstart = element[3]
        }
    }
    tempBlok = {
        summary: consultatie.summary,
        dtstart: dtstart,
        dtend: dtend,
        eventStart: consultatie.eventStart,
        eventEnd: consultatie.eventEnd
    }
    tempArray.push(tempBlok)
})
consultaties = testArray.sort((a,b) => new Date(a.dtstart) - new Date(b.dtstart))
node.warn(consultaties)

In image below you can see the output:

<img width="297" alt="Schermafbeelding 2022-02-10 om 10 26 58" src="https://user-images.githubusercontent.com/688316/153398076-726488b0-bd05-45cf-b810-fee0ec24a687.png">

The event "Sanne Spetters" is from the calendar that is ok; the event "Gaby Baetens" is from the one that where eventStart and evenend are wrong.

Regards, André

**Comment by ahartman** [comment]
Benjamin,

I made an error. Looking again everything seems to be ok again. For the daily appointments we open the door one hour before the first and close it once hour after the last. So, for a single  appointment 0700-0800, startEvent and endEvent should be 0600-0900. I completely forgot that. The original issue where startEvent would be correct but endEvent not seems to have disappeared (for now?)

Regards, André

**Comment by naimo84** [comment]
André,

happy to read, it disappeared ;) Even if I don't understand why ;)
I tried it yesterday in the morning, in the evening and today in the morning.
I always got an valid response like this

![image](https://user-images.githubusercontent.com/11535502/153560532-b7091d25-ae2a-48ef-b14d-e73c0a3dc096.png)

And thanks for the Log File 👍 But I don't see any error in it. 
I'll look at it again but, nevertheless, this is a concern...

I'll close this in a week, if I don't hear anything from you. Hopefully ;))

Greets, Benjamin
