### ISSUE TITLE
All-Day recurring events starting after Daylight Savings Time not showing

### ISSUE THREAD

**Issue by XBCreepinJesus** [naimo84/node-red-contrib-ical-events#125]
I'm using Node-Red to fetch a shared calendar but found it was only bringing back one event. I've had a look in to the events and with a bit of trial-and-error found that the Node-Red plugin is only returning recurring all-day events that start before we switch to "summer time".

I made a new calendar with different kinds of events. recurring and not. They all get returned except for the all-day recurring event where the first event in the series is after the date we (on GMT/London) switch to British summer time (BST / UTC+1).

Interestingly, this does not appear to happen when using the kalender-events CLI - that returns all events as it should!

The test calendar I've made should be accessible here: https://outlook.live.com/owa/calendar/00000000-0000-0000-0000-000000000000/718688e4-c838-44d0-947e-4379896da965/cid-A87A86BC09A3CEA1/calendar.ics

The Node-Red "upcoming" node (just running on a manual trigger at the moment):
![image](https://user-images.githubusercontent.com/66406317/154037149-b3b05fd5-e2f0-4e74-9287-882f320fe2c0.png)
![image](https://user-images.githubusercontent.com/66406317/154036249-4fdca1ab-975b-4f98-bb51-cb95cf18a4a2.png)

Hopefully, you will find the event called "Post-BST All-Day Repeat" does not show up in the Node-Red output.

I'm running Node-Red 2.2.0 in a Docker container, and have v2.2.0 of node-red-contrib-ical-events.

**Comment by XBCreepinJesus** [comment]
Hi Benjamin,

Thanks for the reply. I've been playing around with it again too and if you look at the .ics file itself, the entry for the Post-BST event is as follows (minus Microsoft tags):

```
BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=YEARLY;UNTIL=20220327T230000Z;INTERVAL=1;BYMONTHDAY=28;BYMONTH=3
UID:040000008200E00074C5B7101A82E00800000000F544F51C4C22D801000000000000000
 010000000124277BB8CB8DA4C9A0C84196FE295D8
SUMMARY:Post-BST All-Day Repeat
DTSTART;VALUE=DATE:20220328
DTEND;VALUE=DATE:20220329
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20220215T131018Z
TRANSP:TRANSPARENT
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
END:VEVENT
```

The "UNTIL" date in the RRULE is actually before the first instance of the event, probably due to the summer time difference. If you change the UNTIL value to 2023 or further ahead, it works fine in Node. It could be a rrule.js thing then, as you suggest, caused by this date difference... It also appears that whatever date I set as the end date on Outlook.com, it just exports the same date as above - maybe only exporting a year's worth of dates at once? - so that's probably not helping!

**Comment by naimo84** [comment]
Hi, 

I did a short test with my outlook.com calendar, somehow the rrule doesn't influence the output on my side. We switch to summertime on 27.03.2022. 

![image](https://user-images.githubusercontent.com/11535502/154510520-3b90a893-acdf-4559-9149-163907241ce4.png)

As you can see in the second event, eventStart is pre summertime and eventEnd is past summertime. 

https://outlook.live.com/owa/calendar/00000000-0000-0000-0000-000000000000/3dcbe7b3-79ad-4326-9427-4fa2fbcd716c/cid-3154F18C68B7A617/calendar.ics

the ics looks similar to yours
```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:test
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=YEARLY;UNTIL=20220217T150000Z;INTERVAL=1;BYMONTHDAY=17;BYMONTH=2
UID:040000008200E00074C5B7101A82E0080000000094EA08590D24D801000000000000000
 010000000704422C82E09A84EAB49A4DCD1F18CA8
SUMMARY:test
DTSTART;TZID=W. Europe Standard Time:20220217T160000
DTEND;TZID=W. Europe Standard Time:20220217T163000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20220217T145052Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
```

I've no idea, how I can help with your issue. I'm so sorry...

Greets,
Benjamin

**Comment by XBCreepinJesus** [comment]
Morning, me again...

I had a look at that [MagicMirror](https://github.com/MichMich/MagicMirror/) module I mentioned (the default Calendar module) and, indeed, there is a line and some comments in one of the .js files:
(Note that I'm running a modified version of a fairly old version of this module - those lines are not in the most recent version)
```
// Added the below line to adjust the 'UNTIL' time in RRULE
// Will need to check it when DST ends to make sure it still works as it should!
rule.options.until = moment(rule.options.until).subtract(rule.options.until.getTimezoneOffset(), "minutes").toDate();
```
Using the test calendar from above, my Post-BST All-Day Repeat event shows up fine. If I comment out that line, it's gone! The author(s) of that module obviously had to use a little workaround to adjust rrule times for DST shifts, but it looks like they were using [ical.js](https://github.com/peterbraden/ical.js) rather than rrule.js.

Anyway, the issue for me has been narrowed down at least to that UNTIL field. This simplified test ics (see below) returns only the adjusted event in NodeRed, but running `kalendar-events upcoming...` in CLI with the same options returns both events. Could it be a system locale thing somewhere ? Perhaps from the browser or Docker host (Of the NodeRed container)? I suppose there is a difference in that the NodeRed node has a Timezone setting for eventStart/eventEnd..? Very puzzling!

Test ics - the same event, one with UNTIL in UTC, the other adjusted to match the event time (BST / UTC+1):
```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:GMT Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T010000
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=YEARLY;UNTIL=20220401T000000Z;INTERVAL=1;BYMONTHDAY=01;BYMONTH=4
UID:040000008200E00074C5B7101A82E00800000000F544F51C4C22D801000000000000000
 010000000124277BB8CB8DA4C9A0C84196FE295D8
SUMMARY:With adjusted UNTIL
DTSTART;VALUE=DATE:20220401
DTEND;VALUE=DATE:20220402
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20220215T132307Z
TRANSP:TRANSPARENT
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
END:VEVENT
BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=YEARLY;UNTIL=20220331T230000Z;INTERVAL=1;BYMONTHDAY=01;BYMONTH=4
UID:040000008200E00074C5B7101A82E00800000000F544F51C4C22D801000000000000000
 010000000124277BB8CB8DA4C9A0C84196FE295D9
SUMMARY:Without adjusted UNTIL
DTSTART;VALUE=DATE:20220401
DTEND;VALUE=DATE:20220402
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20220215T132307Z
TRANSP:TRANSPARENT
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
END:VEVENT
END:VCALENDAR
```

**Comment by naimo84** [comment]
Morning, many many thanks for digging deeper 😁 
your local timezone hint leads me to the right direction 👍 

I have setup a new virtual machine in order to change the local timezone. I've now a setup that ignores "our" summertime day also.... 

I'll have a look at ``rule.options.until = moment(rule.options.until).subtract(rule.options.until.getTimezoneOffset(), "minutes").toDate();``, but this may take some time ;) wife, kids and so on ;)

And I won't give up ;) As a developer it makes me crazy if I don't understand why something doesn't work as expected ^^

**Comment by XBCreepinJesus** [comment]
Morning,

That's it, you've got it! Well, almost - I had a type in the volume bind to /etc/localtime 🤦‍♂️ Correcting that has fixed the issue, but I imagine what you said would have had the same effect.

Thanks for all your investigating, and at least it turned out to be a simple fix!

**Comment by naimo84** [comment]
morning,
glad it read it's working now 👍😉
Timezones are pain sometimes 😉
