### ISSUE TITLE
[QUESTION]: I keep getting 405 with caldav - what is wrong?

### ISSUE THREAD

**Issue by wuppiwuppi** [naimo84/node-red-contrib-ical-events#127]
Hi,

I believe I am just missing some point in my configuration...

My setup is:
* homeassistant with node red add on and this beautiful extension
* nextcloud as a caldav source using a public link like this: https:// some domain /index.php/apps/calendar/p/SanHbkwwYbsMm39b
* configured that url as type CalDav in the configuration node
* there is no username / password required for this url. tried to name the calendar or leave the field empty

I keep getting this error message:
"caldav - get calendar went wrong. Error Message: Error: Response with status code: 405"

Any hints?

thanks

**Comment by naimo84** [comment]
Hi @wuppiwuppi,

If I try your link from above, I'm redirected to some advertisement sites. So is this really a caldav source?

Response Code 405 means "Method not allowed". I'm sure that a advertisement site won't allow "PROPFIND" or something else caldav specific ;)

Greets,
Benjamin

**Comment by wuppiwuppi** [comment]
Hi, 

wow sorry - I did not dare to post my real calendar and thus invented some url. I do not own "aaa.de" and I was not aware that this really leads to something. I removed the above url to avoid future clicks...

So - my real url is a not password protected nextcloud calendar. When clicking on it, it opens a web-calendar. I assume it is an automatic web-view of that caldav source ...

**Comment by naimo84** [comment]
Hey, 
no worries ;) This was the most obvious problem ;)

If you have a look at https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html
your url has be be like https://...some domain.../**remote.php/dav**/calendars/


This might be the real problem ;)

Greets,
Benjamin

**Comment by wuppiwuppi** [comment]
Hi,

thanks for your dedication to this ;)
So I guess that "Share public link" does serve only a web-version of a calendar. Not CalDav. 
Using a private link with a login does not throw these errors. 

So this seems to solve it for now. 
However I have another Question: Is it possible to get events when the reminder-time of a calendar event is entered?

**Comment by naimo84** [comment]
hi @wuppiwuppi,

nice to read it's working now 👍

to your second question. generally the nodes only output the alarm/reminder time, but do not throw an event, when the reminder time is entered. this might be a new feature 😉
