### ISSUE TITLE
Feature Request: Search Event Node

### ISSUE THREAD

**Issue by Matten-Matten** [naimo84/node-red-contrib-ical-events#13]
Hallo, erstmal tolle Arbeit,

Ich habe eine Frage, ist es möglich ein Event output zu bebommen wenn ein event in der zukunft auftritt?

Bsp: 
Event:"Hausmüll" ist in 1 Tag
also in etwa so:

_today: 17.11.2019_

```
object
eventdate: "18.11.2019 08:49"
event: "Hausmüll"
inDays: "1"
...
```
oder im Sensor Node in etwa so:
![-17 11 2019_13_43_19](https://user-images.githubusercontent.com/32074970/69007680-30888900-0941-11ea-8e25-4fb4bb9fa60e.png)

Der Hintergrund ist , das ich mir gerne spezifische Kalender Ereignisse im voraus anzeigen lassen möchte
wäre toll wenn das so umgesetzt werden könnte.

Gruß
Matten Matten

**Comment by naimo84** [comment]
Hallo Matten Matten,

ja das ist möglich, allerdings würde ich das ungern in den Sensor Node einbauen. Ich denke, dass führt zu Verwirrungen.

Wenn ich das richtig sehe, geht's dir um den Mülabführkalender? Das habe ich z.B. über den upcoming node (https://github.com/naimo84/node-red-contrib-ical-events#upcoming) gelöst. Das war auch die ürsprüngliche Intention die nodes zu entwickeln :wink:

Ich lasse alle 4 Stunden den ZAW Abfallkalender prüfen (Sollte sich ja nicht allzu oft ändern :wink:). Wenn msg.tomorrow > 0, dann ist morgen eine Tonne fällig und im flow.context ein Status gesetzt. Am Abend wird der flow.context auf true geprüft und entsprechend eine Meldung ausgegeben. Hier ein kurzer Beispielcode

`[{
        "id": "3369c7f7.18e2e8",
        "type": "ical-upcoming",
        "z": "3e88117f.a3481e",
        "confignode": "e670a0a8.1d7b7",
        "cron": "",
        "name": "",
        "offset": "",
        "endpreview": "",
        "x": 550,
        "y": 260,
        "wires": [["f8fcfbea.415a38"]]
    }, {
        "id": "f8fcfbea.415a38",
        "type": "function",
        "z": "3e88117f.a3481e",
        "name": "",
        "func": "if(msg.tomorrow > 0){\n    flow.set(\"muell\",true);\n    var today = new Date();\n    var tomorrow = new Date();\n    tomorrow.setDate(today.getDate()+1);\n    \n    for(let tonne of msg.payload){\n        if(tonne.eventEnd && tonne.eventEnd > tomorrow){\n            flow.set(\"tonne\",tonne.summary);\n            return {\n               payload:tonne.summary\n            };\n        }\n    }\n}else{\n    flow.set(\"muell\",false);\n    flow.set(\"tonne\");\n}\n",
        "outputs": 1,
        "noerr": 0,
        "x": 760,
        "y": 260,
        "wires": [["b0ae4bb8.4de668"]]
    }, {
        "id": "7e93716a.8dbd9",
        "type": "cron",
        "z": "3e88117f.a3481e",
        "name": "",
        "cronExpression": "0 19 * * *",
        "fireAtStartup": false,
        "x": 200,
        "y": 140,
        "wires": [["23bb381c.0190a8"]]
    }, {
        "id": "23bb381c.0190a8",
        "type": "switch",
        "z": "3e88117f.a3481e",
        "name": "",
        "property": "muell",
        "propertyType": "flow",
        "rules": [{
                "t": "true"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 400,
        "y": 140,
        "wires": [[]]
    }, {
        "id": "f78310f2.b0a43",
        "type": "cron",
        "z": "3e88117f.a3481e",
        "name": "",
        "cronExpression": "0 */4 * * *",
        "fireAtStartup": true,
        "x": 210,
        "y": 260,
        "wires": [["3369c7f7.18e2e8"]]
    }, {
        "id": "9cd22492.37fa88",
        "type": "inject",
        "z": "3e88117f.a3481e",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 290,
        "y": 320,
        "wires": [["3369c7f7.18e2e8"]]
    }, {
        "id": "b0ae4bb8.4de668",
        "type": "debug",
        "z": "3e88117f.a3481e",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 970,
        "y": 260,
        "wires": []
    }, {
        "id": "e670a0a8.1d7b7",
        "type": "ical-config",
        "z": "",
        "url": "/home/naimo/abfall.ics",
        "username": "",
        "password": "",
        "name": "ZAW",
        "replacedates": false
    }
]
`

Ich hoffe, ich konnte dir damit weiterhelfen :wink:

Viele Grüße,
Benjamin

**Comment by Matten-Matten** [comment]
Super danke für deine hilfe, jedoch ist das schon zu hoch für meine Nodred Kenntnisse ich werde schon aus dem Script nicht schlau...
![Node-RED _ 192 168 27 42-19 11 2019_00_38_41](https://user-images.githubusercontent.com/32074970/69103248-3081a980-0a65-11ea-96d8-960fa294eac1.png)
da hätte ich das tatsächlich gerne etwas einfacher ähnlich wie bei iobroker...
Schlagwort eingeben und als Ausgabe das gesuchte Wort wie in meinem obersten Beispiel mit Infos ausbekommen oder so. vielleicht als extra Such-Node oder so.

als ich dein node-red-contrib-ical-events gefunden hatte dachte ich nur SUPER noch was was ich in Nodered verarbeiten kann und aus ioBroker rausschmeißen kann. 

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
vielleich um auch mehrere events mit einmal zu suchen wie in ioBroker
![instances - ioBroker-19 11 2019_00_52_35](https://user-images.githubusercontent.com/32074970/69103981-28c30480-0a67-11ea-90ca-2ab3c8b34599.png)

**Comment by naimo84** [comment]
Hey Matten Matten,

mit der nächsten Version kannst du auch in den Upcoming Nodes Filtern :wink:
Damit dürfte das ganze wesentlich einfacher werden.

Da ich dafür Regex verwende, kannst du mehrere Filter gleichzeitig angeben.

Also z.B. 

```
Gelber Sack|Hausmüll
```

Viele Grüße,
Benjamin

**Comment by naimo84** [comment]
Moin moin,

mit der Version 0.9.0 sollte folgender Flow zum gleichen Ergebnis führen ;)


Grüße,
Benjamin

```json
[
    {
        "id": "d3d1f881.bc0918",
        "type": "ical-upcoming",
        "z": "c21b84f8.c064d8",
        "confignode": "e670a0a8.1d7b7",
        "cron": "",
        "timeout": "4",
        "timeoutUnits": "hours",
        "name": "",
        "offset": "",
        "endpreview": "1",
        "endpreviewUnits": "days",
        "trigger": "always",
        "filter": "",
        "x": 480,
        "y": 280,
        "wires": [
            [
                "4a4a4c6d.45f5d4"
            ]
        ]
    },
    {
        "id": "17e35320.c1b6cd",
        "type": "function",
        "z": "c21b84f8.c064d8",
        "name": "",
        "func": "if(msg.tomorrow > 0){\n    flow.set(\"muell\",true);\n    flow.set(\"tonne\",msg.payload.summary);\n}else{\n    flow.set(\"muell\",false);\n    flow.set(\"tonne\");\n}\n",
        "outputs": 1,
        "noerr": 0,
        "x": 770,
        "y": 280,
        "wires": [
            [
                "20ae0221.76a08e"
            ]
        ]
    },
    {
        "id": "4a4a4c6d.45f5d4",
        "type": "split",
        "z": "c21b84f8.c064d8",
        "name": "",
        "splt": "\\n",
        "spltType": "str",
        "arraySplt": 1,
        "arraySpltType": "len",
        "stream": false,
        "addname": "",
        "x": 650,
        "y": 280,
        "wires": [
            [
                "17e35320.c1b6cd"
            ]
        ]
    },
    {
        "id": "e670a0a8.1d7b7",
        "type": "ical-config",
        "z": "",
        "url": "/home/naimo/abfall.ics",
        "username": "",
        "password": "",
        "name": "ZAW",
        "replacedates": false
    }
]
```

**Comment by Matten-Matten** [comment]
Moin, hab ich seit gestern Abend schon im Betrieb. Vielen Dank!

Ich mache hier mal zu dann.

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
Ich habs jetzt so gelöst:

```
[{"id":"d4b9572f.ff1178","type":"ical-upcoming","z":"a2a29b87.cddaf8","confignode":"5cee0852.b9d778","cron":"","timeout":"5","timeoutUnits":"minutes","name":"Gelber Sack","offset":"","endpreview":"1","endpreviewUnits":"days","trigger":"match","filter":"Gelber Sack","x":310,"y":1040,"wires":[["f078e033.a3c33"]]},{"id":"3d0bddc2.9691c2","type":"inject","z":"a2a29b87.cddaf8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":1040,"wires":[["d4b9572f.ff1178"]]},{"id":"f078e033.a3c33","type":"switch","z":"a2a29b87.cddaf8","name":"leer","property":"payload","propertyType":"msg","rules":[{"t":"nempty"},{"t":"empty"}],"checkall":"true","repair":false,"outputs":2,"x":470,"y":1040,"wires":[["3f98f0a1.f7018"],["e4d1ca53.605078"]]},{"id":"e4d1ca53.605078","type":"change","z":"a2a29b87.cddaf8","name":"\" \"","rules":[{"t":"set","p":"payload","pt":"msg","to":" ","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":910,"y":1080,"wires":[["d5477f48.d3295"]]},{"id":"8e06d535.d1e398","type":"switch","z":"a2a29b87.cddaf8","name":"","property":"payload[0].date","propertyType":"msg","rules":[{"t":"cont","v":"Heute","vt":"str"},{"t":"cont","v":"Morgen","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":770,"y":1020,"wires":[["e1055f17.c3e51"],["5c3e1b05.eb79c4"]]},{"id":"e1055f17.c3e51","type":"trigger","z":"a2a29b87.cddaf8","op1":"Heute wird der {{muell}} abgeholt!","op2":" ","op1type":"str","op2type":"str","duration":"10","extend":false,"units":"hr","reset":"","bytopic":"all","name":"Heute","x":910,"y":1000,"wires":[["d5477f48.d3295"]]},{"id":"3f98f0a1.f7018","type":"change","z":"a2a29b87.cddaf8","name":"Gelbe Sack","rules":[{"t":"set","p":"muell","pt":"msg","to":"Gelbe Sack","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":630,"y":1020,"wires":[["8e06d535.d1e398"]]},{"id":"5c3e1b05.eb79c4","type":"function","z":"a2a29b87.cddaf8","name":"Morgen","func":"msg.payload = \"Morgen wird der \" + msg.muell + \" abgeholt!\";\nreturn msg;","outputs":1,"noerr":0,"x":920,"y":1040,"wires":[["d5477f48.d3295"]]},{"id":"85c8d7cd.565278","type":"comment","z":"a2a29b87.cddaf8","name":"Gelber Sack","info":"","x":130,"y":980,"wires":[]},{"id":"f4dba85a.6534e8","type":"debug","z":"a2a29b87.cddaf8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1290,"y":1040,"wires":[]},{"id":"d5477f48.d3295","type":"rbe","z":"a2a29b87.cddaf8","name":"","func":"rbe","gap":"","start":"","inout":"out","property":"payload","x":1110,"y":1040,"wires":[["f4dba85a.6534e8"]]},{"id":"5cee0852.b9d778","type":"ical-config","z":"","url":"","username":"","password":"","caldav":"false","name":"Google Kalender","replacedates":false}]
```
