### ISSUE TITLE
[QUESTION]: Trying to figure out why my trigger didn't trigger. What does this mean? (See image)

### ISSUE THREAD

**Issue by jschwalbe** [naimo84/node-red-contrib-ical-events#138]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/8005921/172157490-6e32d907-5608-4d5d-aed4-c0ccd5e9e896.png">

I expected this to fire this morning, but instead when I checked NR, it showed the above message.

**Comment by jschwalbe** [comment]
Does the trigger node need to be trigged somehow or can it start by itself? When I connected an inject node, then it switched to the following:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/8005921/172289930-d7d68c38-69fe-46b6-88f4-5380c41bdd30.png">

I don't want to have to inject every time I want it to trigger. What should I do? thx

**Comment by naimo84** [comment]
Hey @jschwalbe,

"next check" means: when is your calendar checked (download the calendar and check if new events are in it)
"next trigger" means: when is the output triggered (an event starts or ends)

It can be started by itself, either by "check every XX hours/minutes/days", or by the cron setting.

![image](https://user-images.githubusercontent.com/11535502/172922019-34a893b7-af5b-474f-8d0e-88e1a194371a.png)

Greets, 
Benjamin
