### ISSUE TITLE
How do I debug this?

### ISSUE THREAD

**Issue by tobycheese** [naimo84/node-red-contrib-ical-events#14]
I am using radicale. When using an upcoming node followed by a debug node, the only debug output I get is 

> "CalDAV -> get calendars went wrong."

On the server side, I see two requests in the access log:

> "PROPFIND /cal/foobar/ HTTP/1.1" 207 266 "-" "node-XMLHttpRequest"
> "PROPFIND /cal/nodered/ HTTP/1.1" 403 43 "-" "node-XMLHttpRequest"

where my calendar URL is "https://domain.com/cal/foobar/"

How can I get more info on what is wrong? All I can deduce is that nodered managed to get past basic auth, then fails for some reason.

**Comment by naimo84** [comment]
Hey tobycheese,

may you please try just "https://domain.com" as calendar URL?

## Like this:

![image](https://user-images.githubusercontent.com/11535502/69778520-dbe8d780-11a4-11ea-8e60-eef003ca376a.png)

---

## My Radicale Test collections:

![image](https://user-images.githubusercontent.com/11535502/69778540-f58a1f00-11a4-11ea-9ceb-940b8f846b80.png)

---

## My debug output looks like:

![image](https://user-images.githubusercontent.com/11535502/69778575-16527480-11a5-11ea-9429-be770cd35616.png)


# Debugging in general

you can change the node-red console logging to debug, in order to get more informations. Please have a look at https://nodered.org/docs/user-guide/runtime/logging

**Comment by tobycheese** [comment]
Thanks. I set the loglevel to trace but still get don't get more usable information in the debug output:

    2 Dec 20:26:39 - [debug] [ical-upcoming:Calendar] caldav
    2 Dec 20:26:40 - [error] [ical-upcoming:Calendar] CalDAV -> get calendars went wrong.

The http log output looks like this with https://domain/

    "GET /.well-known/caldav HTTP/1.1" 302 145 "-" "node-XMLHttpRequest"
    "GET /cal/ HTTP/1.1" 302 18 "-" "node-XMLHttpRequest"
    "PROPFIND / HTTP/1.1" 405 157 "-" "node-XMLHttpRequest"

And like this with https://domain/cal/:

    "GET /.well-known/caldav HTTP/1.1" 302 145 "-" "node-XMLHttpRequest"
    "GET /cal/ HTTP/1.1" 302 18 "-" "node-XMLHttpRequest"
    "PROPFIND /cal/ HTTP/1.1" 403 43 "-" "node-XMLHttpRequest"

And like this with https://domain/cal/foobar/

    "GET /.well-known/caldav HTTP/1.1" 302 145 "-" "node-XMLHttpRequest"
    "GET /cal/ HTTP/1.1" 302 18 "-" "node-XMLHttpRequest"
    "PROPFIND /cal/foobar/ HTTP/1.1" 207 266 "-" "node-XMLHttpRequest"
    "PROPFIND /cal/nodered/ HTTP/1.1" 403 43 "-" "node-XMLHttpRequest"

A working request (from MacOS Calendar) looks like this (foobar being my calendar name, under foobar there are two calendars):

    "PROPFIND /cal/tobias/ HTTP/1.1" 401 179 "-" "Mac+OS+X/10.14.6 (18G103) CalendarAgent/416.5.1"
    "PROPFIND /cal/foobar/ HTTP/1.1" 207 1714 "-" "Mac+OS+X/10.14.6 (18G103) CalendarAgent/416.5.1"
    "PROPFIND /cal/foobar/ HTTP/1.1" 207 431 "-" "Mac+OS+X/10.14.6 (18G103) CalendarAgent/416.5.1"
    "OPTIONS /cal/foobar/ HTTP/1.1" 200 5 "-" "Mac+OS+X/10.14.6 (18G103) CalendarAgent/416.5.1"
    "PROPFIND /cal/foobar/ HTTP/1.1" 207 1714 "-" "Mac+OS+X/10.14.6 (18G103) CalendarAgent/416.5.1"
    "PROPFIND /cal/foobar/ HTTP/1.1" 207 1714 "-" "Mac+OS+X/10.14.6 (18G103) CalendarAgent/416.5.1"

And a working request from Android DAVx:

    "PROPFIND /cal/foobar/48aa7cde-a48c-4121-b933-b7101011f17d/ HTTP/1.1" 207 467 "-" "DAVx5/2.5-ose (2019/05/16; dav4jvm; okhttp/3.12.3) Android/8.1.0"
    "PROPFIND /cal/foobar/21DCD45D-3230-4677-891B-C0A4648EF5E8/ HTTP/1.1" 207 433 "-" "DAVx5/2.5-ose (2019/05/16; dav4jvm; okhttp/3.12.3) Android/8.1.0"
    "REPORT /cal/foobar/21DCD45D-3230-4677-891B-C0A4648EF5E8/ HTTP/1.1" 207 2514 "-" "DAVx5/2.5-ose (2019/05/16; dav4jvm; okhttp/3.12.3) Android/8.1.0"
    "PROPFIND /cal/foobar/8A9DFEA0-F99B-47D4-AC22-C94D86F8AB11/ HTTP/1.1" 207 431 "-" "DAVx5/2.5-ose (2019/05/16; dav4jvm; okhttp/3.12.3) Android/8.1.0"
    "REPORT /cal/foobar/8A9DFEA0-F99B-47D4-AC22-C94D86F8AB11/ HTTP/1.1" 207 772 "-" "DAVx5/2.5-ose (2019/05/16; dav4jvm; okhttp/3.12.3) Android/8.1.0"

The difference that I wonder about is that the requests from nodered get these 302 redirection replies, where the MacOS and Android do not request the well-known thing and do not get these redirects.

I also found a debug log of radicale. There, all cnfigurations except https://domain/cal/foobar/ are denied by radicale rights management.

Here are the working request headers from MacOS Calendar:

```
2019-12-02 21:06:37,846 - DEBUG: Request headers:
{'CONTENT_LENGTH': '2217',
 'CONTENT_TYPE': 'text/xml',
 'DOCUMENT_ROOT': '/some/path/on/my/server',
 'HTTPS': 'on',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'br, gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-us',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_BRIEF': 't',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_CONTENT_LENGTH': '2217',
 'HTTP_CONTENT_TYPE': 'text/xml',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': 'domain.com',
 'HTTP_PREFER': 'return=minimal',
 'HTTP_USER_AGENT': 'Mac+OS+X/10.14.6 (18G103) CalendarAgent/416.5.1',
 'Host': 'domain.com',
 'PATH_INFO': '/foobar/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': 'server_ip',
 'REMOTE_PORT': '60562',
 'REMOTE_USER': 'foobar',
 'REQUEST_METHOD': 'PROPFIND',
 'REQUEST_SCHEME': 'https',
 'REQUEST_URI': '/cal/foobar/',
 'SCRIPT_NAME': '/cal',
 'SERVER_NAME': 'domain.com',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
  some more nginx and uwsgi stuff}
```

And here the non-working request from node-red:

```
{'CONTENT_LENGTH': '323',
 'CONTENT_TYPE': 'application/xml;charset=utf-8',
 'DOCUMENT_ROOT': '/some/path/on/my/server',
 'HTTPS': 'on',
 'HTTP_ACCEPT': '*/*',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CONNECTION': 'close',
 'HTTP_CONTENT_LENGTH': '323',
 'HTTP_CONTENT_TYPE': 'application/xml;charset=utf-8',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': 'domain.com',
 'HTTP_USER_AGENT': 'node-XMLHttpRequest',
 'Host': 'domain.com',
 'PATH_INFO': '/foobar/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': 'server_ip',
 'REMOTE_PORT': '45240',
 'REMOTE_USER': 'foobar',
 'REQUEST_METHOD': 'PROPFIND',
 'REQUEST_SCHEME': 'https',
 'REQUEST_URI': '/cal/foobar/',
 'SCRIPT_NAME': '/cal',
 'SERVER_NAME': 'domain.com',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
  some more nginx and uwsgi stuff}
```

**Comment by naimo84** [comment]
Hi tobycheese,

may you please have a look at v0.9.2?
As I wrote here https://github.com/naimo84/node-red-contrib-ical-events/issues/16#issuecomment-561619330, I found a "feature" in the dav-lib.

Regards,
Benjamin

**Comment by tobycheese** [comment]
Hey @naimo84 
Thanks for looking at this. I tried 0.10.0 and still the same :-(
I realised that for what I want to achieve (check once in early morning for a specific event, if found, set a state in homeassistant or node-red), I can also create a small cronjob on the server where my calender is that parses the relecant .vcf file directly. I might just go that route.

**Comment by naimo84** [comment]
> There, all configurations except https://domain/cal/foobar/ are denied by radicale rights management.

Could you please change this for testing? The DAV-lib makes a PROPFIND request, to get all calendar entires of the caldav server. This would explain the 403 Forbidden of this line.

> "PROPFIND /cal/nodered/ HTTP/1.1" 403 43 "-" "node-XMLHttpRequest"

This was also the problem of #16 .

Otherwise I'm sorry, that I couldn't help you with this problem... 😢
