### ISSUE TITLE
Error in parsed data EventStart & EventEnd "Invalid DateTime"

### ISSUE THREAD

**Issue by ukmoose** [naimo84/node-red-contrib-ical-events#141]
**Describe the bug**
The export from the ical-upcoming node contains  "Invalid DateTime" for all eventStart and eventEnd within the array, where as the raw calendar feed contains information.

`array[3]
0: object
date: "12/25/22, 12:00 AM – 12/26/22, 12:00 AM"
eventStart: "Invalid DateTime"
eventEnd: "Invalid DateTime"`

eg https://www.officeholidays.com/ics-local-name/norway

`DTSTART;VALUE=DATE:20220101
DTEND;VALUE=DATE:20220102
DTSTAMP:20220101T000000Z`

**To Reproduce**

Create a CalDAV calendar config 
Add an upcoming node, select the CalDAV config, leave calendars empty, select "Events" as event types
Connect the upcoming node to a debug node
Trigger the upcoming node using a trigger node

Version: 2.2.1
node-red version: v2.2.2
nodejs version: v14.18.2
is it an ical, caldav or icloud calendar? ical

**Comment by naimo84** [comment]
Hi @ukmoose ,

if I'm setting the type to "iCal" it seems to work correct? Caldav is throwing an exception, as excepted due to the fact its not an Caldav calendar?

![image](https://user-images.githubusercontent.com/11535502/188714284-cf00d237-dc08-4625-89cd-22a246554ce7.png)

Greets,
Benjamin

**Comment by naimo84** [comment]
I'll close this for now, because https://www.officeholidays.com/ics-local-name/norway and the type setting iCAL should work. Feel free to reopen it, if you have some more informations or the issue persists 👍
