### ISSUE TITLE
iCal config node: Username + Password hidden

### ISSUE THREAD

**Issue by aikitori** [naimo84/node-red-contrib-ical-events#147]
Hi there,
thank you for you work with this project. I really like it.

i found some minir issue in the config node. When i select the calender Type "iCal", the username and password fields stays hidden. After selecting the other options, the fields become visible again.

As far as i can see, the fields should become visible:
https://github.com/naimo84/node-red-contrib-ical-events/blob/main/src/nodes/ical-config.html#L87

So now for entering credetials, i use the Browserconsole and change the css manually. The credentials are then saved and used for authentification, no error occur.

Node-RED-Version: 3.0.2
ical-events: Version: 2.2.1
OS: Debian 11, Raspi Os, Ubuntu Server 22.04

![grafik](https://user-images.githubusercontent.com/88290076/198582037-1f0449b3-4e9f-4a29-a24c-74dfd2bb8ed6.png)

**Comment by naimo84** [comment]
Will be part of v2.2.2 😉 I'm trying to fix some other issues, and will release it as soon as possible. Give me 2-3 days 😉
