### ISSUE TITLE
[Upcoming Node] Missing documentation and strange behaviour

### ISSUE THREAD

**Issue by hillbicks** [naimo84/node-red-contrib-ical-events#15]
Hi,

I'm currently struggling with this addon. I have one calender that contains entries on some days, valid for only one minute, e.g. 30.11.2019 00:00 - 30.11.2019 00:00. 

I'm using the upcoming node to trigger telegram notifications with the summary. To test this, I created a test calendar with only one entry. 

Here are the issues that I'm facing:
- The upcoming node contains two options: "Check every xx". For this option, there is no documentation in the info windows. In addition to that, there is a cron feature. That one is documented, but it is not clear how these options are interacting with each other. Also, there are comments here on github stating that having cron not filled will disable it, but I saw it running once an hour. 

- When creating an upcoming node with an calender with only one entry and adding a debug node, I can see the payload being delivered twice. The entries look exactly the same to me

`29/11/2019, 11:45:55node: caldav debug msg.payload : array[1]
array[1]
0: object
date: "30.11.2019 00:00-00:00"
summary: "Leerung: Restabfall"
topic: "Leerung: Restabfall"
event: "Leerung: Restabfall"
eventStart: "2019-11-29T23:00:00.000Z"
eventEnd: "2019-11-30T23:00:00.000Z"
description: ""
id: "OJRFCLOJM9PI1NIPY5C1YQ"
allDay: true
rule: " "
location: ""`

`29/11/2019, 11:45:55node: caldav debug msg.payload : array[1]
array[1]
0: object
date: "30.11.2019 00:00-00:00"
summary: "Leerung: Restabfall"
topic: "Leerung: Restabfall"
event: "Leerung: Restabfall"
eventStart: "2019-11-29T23:00:00.000Z"
eventEnd: "2019-11-30T23:00:00.000Z"
description: ""
id: "OJRFCLOJM9PI1NIPY5C1YQ"
allDay: true
rule: " "
location: ""`

Since I only need the payload[0].summary, I'm using this in telegram but as you can see, the telegram message would actually be delivered twice. Any idea what I'm doing wrong here?

Thanks in advance!

**Comment by naimo84** [comment]
Hi hillbicks,

may you please try version 0.9.1? I'm sorry, but I did a big mistake at one of my last changes at the calDAV code... PLease let my know, if it works with the new version.

I also tried to describe the "Check every" and the "Cron" feature in the info window like this:

• "Check every": Value in seconds, minutes, hours or days, how often the calendar is checked for new upcoming events. 0 or empty value to disable.
• "Cron": Similar to "Check every", but much more configurable. It's a cron expression, how often the calendar is checked for new upcoming events.
If Cron is defined, it wins against "Check every". Empty value to disable.

Regards,
Benjamin

**Comment by hillbicks** [comment]
Hey Benjamin,

the first issue is solved, I'm only receiving the payload once. So thanks for that!
Second issue is also solved, I now get the difference between these two functions. 

Maybe It's just me and because I'm new to node red, but I wasn't entirely sure whether I still need the inject node before the upcoming node so it gets triggered. But then the "check every" and "cron" wouldn't really makes sense. 

Thanks for fixing this issue so quickly, I really appreciate it. I'll close the issue now. :)
