### ISSUE TITLE
[BUG]: When using "Fetch all configs concurrent" you cannot pass in a msg.variable for the Preview field.

### ISSUE THREAD

**Issue by gdst4rp** [naimo84/node-red-contrib-ical-events#150]
**Describe the bug**
If I pass a msg.num_days with a numeric value into the Upcoming node and select a single configuration, I get the expected results for the next msg.num_days. If I then choose a second calendar, it too works. However, if I check the box "Fetch all configs concurrent", I get the error "Error: preview must be a duration string or a number". I only have these two calendars configured, and they both work individually, but selecting the Fetch all configs concurrent, breaks the flow. If I replace the msg.num_days value with a simple numeric for Preview, everything works fine

**To Reproduce**
1. Configure 2 independent iCal Configs
2. Call Upcoming from a previous node that also sets a variable (e.g. msg.num_days) to 4
3. Results should work for the given single calendar
4. Repeat steps 2-3 above with the second iCal config, this too should work
5. Check the "Fetch all configs concurrent" box and attempt to run it again
6. Error received is "Error: preview must be a duration string or a number"
7. Replace the msg.num_days in the Preview box with the numeric 4
8. Re-run (still with the "Fetch all configs concurrent" box checked)
9. You should see the expected merged calendar information

**Expected behavior**
Preview should be able to accept valid numeric values from msg.variables, even when using the "Fetch all configs concurrent" checkbox

**Screenshots**

**node-red-contrib-ical-events
 - Version [e.g. 2.2.1]
 - node-red version v3.0.2
 - Using this as part of a Home Assistant RPi4 install v2022.12.8, Supervisor 2022.11.2, Operating System 9.4
 - nodejs version
 - Both calendars are "iCloud secure"

**Logs / Additional context**

You can send me a debug log, like described here: https://naimo84.github.io/kalender-events/guide/debug.html

**Comment by naimo84** [comment]
Should be fixed with the latest version 👍 
If not, feel free to comment or reopen it 😉
