### ISSUE TITLE
[BUG]: Difference in results between Preview = 1 day, and Preview = 24 hours

### ISSUE THREAD

**Issue by gdst4rp** [naimo84/node-red-contrib-ical-events#153]
**Describe the bug**
For some reason, I get 0 results in my iCloud Secure pull when using Preview = 1 days, but if I change it to Preview = 24 hours, I get the expected calendar entries

**To Reproduce**
1. Use an iCloud Secure configuration with "Replace Dates with name" checked
2. Ensure that there are some entries for today (I was using a non-all day recurring event between specific times today)
3. Default Dateformat field: { "timeStyle": "short", "dateStyle": "short" }
4. Set the Upcoming node config to Preview = 1 days
6. For me, the result set had 0 events listed. This happens with an individual iCloud Secure calendar, and the "Fetch all configs concurrent" checked
7. Change the Upcoming node config to Preview = 24 hours
8.  Re-pull events, and I now see the listed events for the day

**Expected behavior**
I would expect consistent behavior between 24 hours and 1 day event pulls

**Screenshots**

**node-red-contrib-ical-events version [2.2.1]
 - node-red version [Home Assistant 2023.1.2 with NodeRed version  3.0.2)
 - is it an ical, caldav or icloud calendar? iCloud Secure (3 calendars total)

**Comment by naimo84** [comment]
Hey @gdst4rp , 

that comes from https://github.com/naimo84/node-red-contrib-ical-events/issues/12#issuecomment-551449253
Setting to days means complete days 😉 If you want really 24 hours, then yes, you have to set it like this.

You can also have a look at: https://github.com/naimo84/node-red-contrib-ical-events/issues/46

Greets,
Benjamin
