### ISSUE TITLE
caldav not working

### ISSUE THREAD

**Issue by BiBo65** [naimo84/node-red-contrib-ical-events#16]
Hi 
I'm using David from Tobit Software, there it is possible tu access my calendar via caldav.
I tried the connection with Thunderbird and it is working fine there.
When I try to connect with node-red-contrib-ical-events, I'll get an error "CalDAV -> get calendars went wrong." in the payload message.
Any sugesstions why it is not working?
If you need login data, I can send you some for testing.

**Comment by naimo84** [comment]
Hi BiBo65,

the message "get calendars went wrong" indicates, that the error comes from the external library "dav" (https://github.com/lambdabaa/dav) I'm using. 

What URL are you using? Have you activated Basic Authentication in David?

Some login data for testing would be awesome 😉 It would be a lot easier to debug.

Regards, 
Benjamin

**Comment by BiBo65** [comment]
how can I send you the necessary login data ?

**Comment by naimo84** [comment]
You can send me an email at git@neumann-benjamin.de

**Comment by naimo84** [comment]
Hi, 

many many thanks for sharing me a test account. I found a "feature" of the dav-lib 😉 
May you please try v0.9.2? 

Regards, 
Benjamin

**Comment by naimo84** [comment]
Should be fixed with v0.9.2, so I'm closing this now ;) 
Feel free to reopen it.
