### ISSUE TITLE
[BUG]: System Time Change Detected / KNX reconnect

### ISSUE THREAD

**Issue by waldbaer** [naimo84/node-red-contrib-ical-events#163]
**Describe the bug**
When triggering a query of the ical server (either via ical-events or ical-upcoming) strange things are happening in my system:

- CPU load jumping from ~10% to 100% for about 10seconds
- A system time change is detected by the [node-red-contrib-cron-plus](https://github.com/Steve-Mcl/node-red-contrib-cron-plus) node.
- The connection to my smarthome automation bus KNX is lost and must be re-established (using [node-red-contrib-knx-ultimate](https://github.com/Supergiovane/node-red-contrib-knx-ultimate))

**To Reproduce**
1. Create a ical-events or ical-upcoming node. Node settings: 
  * Trigger: Match
  * Filter Property: Summary
  * Filter: "<RegExFilterString>"
 
2. Create a configuration with the following options set: 
  * calenderType=iCal

3. Trigger the node(s) with an injected message `{ payload: true }`
4. See the node-red core outputs:
```
...
Jun 28 21:40:54 rpi0 Node-RED[1874]: 28 Jun 21:40:54 - [info] [cronplus:every 15min (Mai..Sept)] System Time Change Detected!
Jun 28 21:40:54 rpi0 Node-RED[1874]: 28 Jun 21:40:54 - [info] [cronplus:every 15min (Mai..Sept)] Refreshing running schedules
Jun 28 21:41:32 rpi0 Node-RED[1874]: [error] 28/06/2023, 21:41:32.415 knxUltimate-config: received KNXClientEvents.error: Invalid Connection ID
Jun 28 21:41:32 rpi0 Node-RED[1874]: [error] 28/06/2023, 21:41:32.506 knxUltimate-config: Disconnected by: Invalid Connection ID
```

**Expected behavior**

- No system time change
- No disconnect to the KNX gateway/router

**Screenshots**

**node-red-contrib-ical-events
 - Version 2.2.2
 - node-red version 3.0.2
 - nodejs version v18.16.1
 - calender type: iCal
 
**Logs / Additional context**

This issue is for me reproducible 100%. It took me a long time to find out the ical-events regular update (so far every 15min) actually caused the disconnected / re-connect to the KNX router which means the Node-RED instance is not able to send or read messages to my smart home during this re-connect phase.

Then last week I installed ode-red-contrib-knx-ultimate and now saw that this node is reporting a system time change always when the ical update is triggered.  This is maybe also the reason why the connection to the KNX gateway terminates or get's invalid.

I can here also confirm that I am affected 100% by #128. The outputs of an inject node sending a message every 1sec are blocked for ~10sec too when the ical update is triggered.

And: Thanks for this node! Really feature-rich and helpful. Just hoping that we could find the root cause of this strange issue which I am observing since 1 year ;)

**Comment by waldbaer** [comment]
For everyone having the same issue...

I think the issue is caused by the high CPU consumption necessary for parsing of the ICS file.
In case of Node.js this leads to the fact the the main event loop is blocked for a long time. In the concrete case this long blocking of the event loop is most-likely causing other nodes to run into errors (here KNX).

In the meantime I replaced the usage of node-red-contrib-ical-events completely with a python-based icalendar parser.
Benefit is that a separate python process is scheduled not blocking the Node.js event loop.

Thats the small python CLI tool I am now using: [icalendar-events-cli](https://github.com/waldbaer/icalendar-events-cli)

**Comment by naimo84** [comment]
Might be fixed with the latest version 👍 
If not, feel free to comment or reopen it 😉 

I've implemented worker threads and called it "experimental features", in order to not break others flows.

https://naimo84.github.io/kalender-events/guide/experimental.html

**Comment by malys** [comment]
nodered 4.0.8
node-red-contrib-ical-events 2.2.5 with "experimental features"
Same issue :)

because of blocking code, nodered becomes unstable
