### ISSUE TITLE
[FEAT]: Catchable errors from iCal-upcoming node

### ISSUE THREAD

**Issue by mountain181** [naimo84/node-red-contrib-ical-events#165]
**Describe the solution you'd like**

The errors from upcoming node is not catchable. When a error happens it's only sent to debug log, but i cant catch the error with a catch node. 

![calendar-error](https://github.com/naimo84/node-red-contrib-ical-events/assets/123192192/d501dc8c-752a-48a7-b8c7-6a425db95f8a)

The error seen in picture is an uncatchable error. 

Would be great if someone have time to fix.

**Comment by naimo84** [comment]
Should be fixed with the latest version 👍 
If not, feel free to comment or reopen it 😉
