### ISSUE TITLE
[BUG]: npm packet not published due to error in Github action

### ISSUE THREAD

**Issue by unclej84** [naimo84/node-red-contrib-ical-events#166]
**Describe the bug**
The github action stops because of deprecated node.js version for the jobs. Therefor no new npm package is published

**To Reproduce**
1. input
2. config
3. ouput

**Expected behavior**

**Screenshots**

**node-red-contrib-ical-events
 - Version [e.g. 0.1.22]
 - node-red version
 - nodejs version
 - is it an ical, caldav or icloud calendar?

**Logs / Additional context**

You can send me a debug log, like described here: https://naimo84.github.io/kalender-events/guide/debug.html

**Comment by naimo84** [comment]
Should be fixed with the latest version 👍 
If not, feel free to comment or reopen it 😉
