### ISSUE TITLE
Value Termin in X Tagen

### ISSUE THREAD

**Issue by Christoph22** [naimo84/node-red-contrib-ical-events#17]
Danke erstmal für die klasse Node !  Endlich kann ich Kalender einfach in Node Red einbinden  👍

Was ich noch sehr nützlich fände, wäre ein zusätzliches Value für jeden Termin das angibt in wieviel Tagen der Termin stattfindet. 

z.B. bei einem Abfallkalender: 

Restmüll in 3 Tagen

Gruß Christoph

**Comment by naimo84** [comment]
Hallo Christoph,
leider hat es ein wenig länger gedauert, sorry. 
Dienstreise, Baby und Weihnachtsfeiern kosten Zeit 😉

Mit Version 0.10.1 gibt es eine zusätzliche countdown Eigenschaft, die die Zeit bis zum eventstart angibt.

Grüße, Benjamin

**Comment by Christoph22** [comment]
Hallo Benjamin,

Vielen Dank für die schnelle Umsetzung 👍 

Gruß Christoph
