### ISSUE TITLE
Repeating events

### ISSUE THREAD

**Issue by hugo1721** [naimo84/node-red-contrib-ical-events#18]
Using the upcoming node, repeating events that occur in within the chosen time frame are not shown. I see the same issue here: https://github.com/naimo84/node-red-contrib-ical-events/issues/5#issue-511588933, but I use iCloud not ics file.
0.10.0 version

Thanks

**Comment by naimo84** [comment]
Hi hugo,
May you please have a look at v0.10.1

I tried to implement repeating events for the icloid secure type. 

Regards, Benjamin

**Comment by hugo1721** [comment]
Thanks!! Perfect now!
