### ISSUE TITLE
Report calendar name in msg.payload

### ISSUE THREAD

**Issue by e-lange** [naimo84/node-red-contrib-ical-events#19]
I do have multiple calendars within one account. I would like to use the different calendars for e.g. setting temperatures in different rooms with the rooms being associated to the different calendars.
As far as I can see the calendar name is somewhere given in the data structures but discarded on the way back to the payload.
Would it make sense to return the calendar name associated for each upcoming event?

**Comment by naimo84** [comment]
This should be no problem 😉 
 I'll have a look at it

**Comment by naimo84** [comment]
May you please have a look at v0.10.2?

**Comment by e-lange** [comment]
Perfect, that was exactly the information I was looking for. thx.
