### ISSUE TITLE
Upcoming events checks every hour even when using input node

### ISSUE THREAD

**Issue by jimmythegreat** [naimo84/node-red-contrib-ical-events#2]
First off, thanks for making this node! It's the only ical supporting node out there.

I am triggering the upcoming events node from another node. Something like this: 

BigTimer -> some other nodes -> link out -> link in -> upcomingEvents -> output parsing -> TSS

However, the upcoming events still triggers every hour (which I assume is the default cron). I'd rather not use cron and would rather see it only fire when it gets input from another node.

Please advise if I am doing something wrong.

Thanks

**Comment by naimo84** [comment]
Hey jimmy,

thanks for your words 😀 
Currently the cronjob should stop, on the first incoming input. 
I know, this is misleading 😉 I'll try to make it configurable. 

Greets
Benjamin

**Comment by naimo84** [comment]
Hey, 

may you please try version 0.2.2?

Now: If no cron is defined, it's only triggered on an input.

Thanks ;)

**Comment by jimmythegreat** [comment]
@naimo84 It now only uses cron if I specify a cron. Thanks a bunch for updating.
