### ISSUE TITLE
SyntaxError: Unexpected token { after install

### ISSUE THREAD

**Issue by lighthousebulb** [naimo84/node-red-contrib-ical-events#20]
I installed `node-red-contrib-ical-events@0.10.2` and it seemed fine, but as soon as I started node-red again the following, showed up in the Log:

`[warn] [node-red-contrib-ical-events/ical-events] SyntaxError: Unexpected token {`
`[warn] [node-red-contrib-ical-events/ical-sensor] SyntaxError: Unexpected token {`
`[warn] [node-red-contrib-ical-events/ical-upcoming] SyntaxError: Unexpected token {`

in this case I'm using:
`Node-RED version: v0.18.4`
`Node.js  version: v4.2.6`
`Linux 4.4.0-122-generic x64 LE`

Nodes are not working. Deploying them, ended in `Flows stopped due to missing node types.`
Any ideas?

**Comment by naimo84** [comment]
Hi,

Unfortunately I have no idea, why this is happening. I tried it on several Systems. 

The only thing I could think about is the 4 year old nodejs 4.2.6. Could you try it on a newer System?

**Comment by naimo84** [comment]
Do you see any line numbers?

**Comment by lighthousebulb** [comment]
Thanks, for investigating so far. I don't see any line numbers.
I will try it on a newer system and will get back to you.

**Comment by lighthousebulb** [comment]
All right, it works with node Version `v12.13.0` for example.
So never mind the old nodejs-Version.
Thanks!
