### ISSUE TITLE
sensor node does not work with recurring events

### ISSUE THREAD

**Issue by mvivaldi** [naimo84/node-red-contrib-ical-events#21]
Hi,
I'm unable to use the sensor node because in my calendar (google calendar ics) I use recurring events but the result of the node is always off.

I use the the node to start my thermostat (I put the temperature in the summary) but it only works on the first occurrence.

Thank you

**Comment by mvivaldi** [comment]
I tried the new version, but now it doesn't return anything (not event the "off") when it hit a recurring event (same when there's no event).

**Comment by naimo84** [comment]
hmmm, for me its working in my development and my production system. 
The third output is after defining a test event.

May I ask, what node-red, nodejs version are you using?

![image](https://user-images.githubusercontent.com/11535502/71840530-c927c380-30bd-11ea-8391-a0128486780d.png)

![image](https://user-images.githubusercontent.com/11535502/71841070-d85b4100-30be-11ea-9ddd-1c7873840408.png)

**Comment by mvivaldi** [comment]
$ node -v
v10.18.0

node-red version 1.0.3

**Comment by mvivaldi** [comment]
I reinstalled node-red, and now i receive the false
this is my ics:
```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:camere
X-WR-TIMEZONE:Europe/Rome
X-WR-CALDESC:termostato camere
BEGIN:VTIMEZONE
TZID:Europe/Rome
X-LIC-LOCATION:Europe/Rome
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Rome:20200103T203000
DTEND;TZID=Europe/Rome:20200103T230000
RRULE:FREQ=DAILY
DTSTAMP:20200106T203417Z
UID:6cvrk1lm6v7rf91dogci3jbfg9@google.com
CREATED:20200106T202943Z
DESCRIPTION:
LAST-MODIFIED:20200106T202943Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:17
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

**Comment by mvivaldi** [comment]
This morning the automation worked.... I don't know what to think. Maybe yesterday I was tired and did something wrong. I'll test for the next few days and report back.
Thank you

**Comment by mvivaldi** [comment]
nope, is not working.
This is my flow:
![node](https://user-images.githubusercontent.com/9114100/71927121-11fe7b80-3195-11ea-9cd5-d1dc56c0cb1d.jpg)
and if I create a recurrent event in the past it doesn't work.

**Comment by mvivaldi** [comment]
This fix seems to work.
I will report back if everthing is ok in the next few days.

Thank you very much!

**Comment by mvivaldi** [comment]
I think you could close this one. I didn't have any more problem.

Thank you!

**Comment by naimo84** [comment]
Perfekt, your welcome 😉
