### ISSUE TITLE
Upcoming events - past view

### ISSUE THREAD

**Issue by ahartman** [naimo84/node-red-contrib-ical-events#22]
I cannot get past view to work. I would expect for a value of past view - '1 day' to see the vets of today that have expired.  Whatever value I put in the field, I only see upcoming events.
Using version 0.10.2.

**Comment by naimo84** [comment]
Hi andrè 😉 

may you please try v0.10.2 and afterwards?

**Comment by ahartman** [comment]
I am on 0.10.2. What I also note is that I need to set 'preview' to 2 days to catch today's events. With preview on 1 day, today's future events are not reported.
Kind regards, ahartman

**Comment by naimo84** [comment]
Hi, if created a new unit test for this: 1 day preview - today 2 - tomorrow 1 - total 3
Preview is 1 day and: 

One event is one hour in the future, one event is running the whole day. Both are reported.

events["2"].start = moment().add(1, 'h').toDate();
events["2"].end = moment().add(2, 'h').toDate();
events["3"].start = moment().startOf('day').toDate();
events["3"].end = moment().endOf('day').toDate();

**Comment by ahartman** [comment]
Benjamin,
Preview works fine, it is past vies that I am struggling with. For me a setting of ‘1 day’ should refer to today, both for preview and for past view. With 3 events in the morning and 3 in the afternoon, I would expect 6 events to be reported at noon, 3 past view and 3 preview.
Please see attached screen images at 0643 this morning and settings of 1 day for preview and 1 day for post view.
Object[0] is an allday event of yesterday that should be not reported in my view.
Object[1] is an allday event for all days in the week, correctly reported.
Object [3] is the active event that the time of the test; correct.
The further events are the previewed events for the rest of the day.

Events ‘test1’ and ‘test2 are not reported but should be reported because of the post view setting. Extending the post view setting to multiple days does not report any events at all of the previous days. Setting preview to 0 days makes object[0] disappear but that event should not be there in the first place.

Hope this helps in making this work ok.
Regards, ahartman


[Archief.zip](https://github.com/naimo84/node-red-contrib-ical-events/files/4057612/Archief.zip)

**Comment by naimo84** [comment]
Thanks andrè for the detailed messages 😉 

Hopefully, I get it working correctly. With the next published version.

![image](https://user-images.githubusercontent.com/11535502/72349507-ee7b8980-36dc-11ea-97fd-a5a7cba27616.png)
![image](https://user-images.githubusercontent.com/11535502/72349615-208ceb80-36dd-11ea-8c9b-f1d90d6bdec9.png)
![image](https://user-images.githubusercontent.com/11535502/72349530-fc310f00-36dc-11ea-9939-4fab2a02d39b.png)

**Comment by ahartman** [comment]
Benjamin,
I see a commit, does that mean I can install and test?
I also removed my screen images as they contain a lot of private information.
We have medical practice at home and I use your module to control the lights and, more importantly, the automatic door lock, 30 minutes before the first patient and 30 minutes after the last one.
Regards, ahartman

**Comment by naimo84** [comment]
Sorry, yes I published a new version yesterday 😉

**Comment by ahartman** [comment]
Benjamin,
This seems to work fine now.
The only thing that I could still think of is an extra property 'past view/preview' to ease filtering but I can do that in code just as easy. I will start using this in my live flows and will let you know if I find something not OK.
And for me a setting in the node 'Exclude allday events' would help but that might not be relevant for others.
Regards, ahartman

**Comment by ahartman** [comment]
Benjamin,
It looks like functionality changed when you coded 'past view'. An ongoing event was reported as part of preview. It only disappeared from preview when it had expired.
Now it seems as if current events have become part of post view and they are no longer in preview.

I have no opinion of what is right and what is wring. I noticed this as some of my code broke with the new version of there 'Upcoming' node.
Regards, ahartman

**Comment by naimo84** [comment]
Andrè,
sorry, that was not intended. May you have a look at v0.10.6 please. 
The problem was pastview = 0 selected tomorrow... 😢 Sorry about that.
Regards,
Benjamin

**Comment by naimo84** [comment]
And: I'll have a look at 'pastview/preview' property as weel as 'Exclude allday events' 😉

**Comment by ahartman** [comment]
Benjamin,
I installed 0.10.6 but there is still something not right. Please see agenda of today in attached image. I run two 'upcoming' nodes, both set to 1 day of preview and 1 day of post view, one node on the red agenda and one on the blue agenda.
The node on the red one picked up all events of today correctly, the node on the blue agenda with 2 evens today, only reports the first event and misses the second one.
I am doing this at 0745 in the morning, so this is all about preview, there is no post view yet.
This has been working correctly for many weeks, so I suspect something is not OK in the version 0.10.6.

Regards, ahartman


<img width="1202" alt="Schermafbeelding 2020-01-21 om 07 43 57" src="https://user-images.githubusercontent.com/688316/72781826-879d2980-3c22-11ea-8a0e-39f4084e495f.png">

**Comment by naimo84** [comment]
When does the event from 18:30 end?

**Comment by naimo84** [comment]
I've tested it here with 2 agendas:

![image](https://user-images.githubusercontent.com/11535502/72784255-b9b18a00-3c28-11ea-8f6c-c5b36793ee35.png)

Both are reported as preview. I don't see the error 😢 

![image](https://user-images.githubusercontent.com/11535502/72784281-c46c1f00-3c28-11ea-97e3-683bba4f7c8b.png)

```json
[
    {
        "id": "ff776b13.2b49d8",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "9fab951d.1ae3f8",
        "type": "inject",
        "z": "ff776b13.2b49d8",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 100,
        "y": 80,
        "wires": [
            [
                "d9fec8e1.e0ef38"
            ]
        ]
    },
    {
        "id": "d9fec8e1.e0ef38",
        "type": "ical-upcoming",
        "z": "ff776b13.2b49d8",
        "confignode": "65bf469c.42a478",
        "cron": "",
        "timeout": "",
        "timeoutUnits": "seconds",
        "name": "",
        "offset": "",
        "endpreview": "1",
        "endpreviewUnits": "days",
        "pastview": "1",
        "pastviewUnits": "days",
        "trigger": "always",
        "filter": "",
        "x": 320,
        "y": 100,
        "wires": [
            [
                "7f44cc45.7b3f24"
            ]
        ]
    },
    {
        "id": "7f44cc45.7b3f24",
        "type": "debug",
        "z": "ff776b13.2b49d8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 560,
        "y": 100,
        "wires": []
    },
    {
        "id": "f018b6ac.c8c1e8",
        "type": "ical-upcoming",
        "z": "ff776b13.2b49d8",
        "confignode": "2f010667.b29e7a",
        "cron": "",
        "timeout": "",
        "timeoutUnits": "seconds",
        "name": "",
        "offset": "",
        "endpreview": "1",
        "endpreviewUnits": "days",
        "pastview": "1",
        "pastviewUnits": "days",
        "trigger": "always",
        "filter": "",
        "x": 310,
        "y": 160,
        "wires": [
            [
                "7f44cc45.7b3f24"
            ]
        ]
    },
    {
        "id": "2d6b67ee.fdcd08",
        "type": "inject",
        "z": "ff776b13.2b49d8",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 100,
        "y": 160,
        "wires": [
            [
                "f018b6ac.c8c1e8"
            ]
        ]
    },
    {
        "id": "65bf469c.42a478",
        "type": "ical-config",
        "z": "",
        "url": "https://p51-caldav.icloud.com/123456789/calendars/home/",
        "username": "...",
        "password": "...",
        "caldav": "icloud",
        "name": "icloud home",
        "replacedates": false,
        "calendar": "",
        "pastWeeks": "",
        "futureWeeks": ""
    },
    {
        "id": "2f010667.b29e7a",
        "type": "ical-config",
        "z": "",
        "url": "https://p51-caldav.icloud.com/123456789/calendars/work/",
        "username": "...",
        "password": "...",
        "caldav": "icloud",
        "name": "icloud work",
        "replacedates": false,
        "calendar": "",
        "pastWeeks": "0",
        "futureWeeks": "4"
    }
]
```

**Comment by ahartman** [comment]
Benjamin,
The blue event starting at 1830 ends at 2100.
As you can see in attached image of my Node-Red, it is not picked up the upcoming 'blokken' node.
regards, André Hartman


[Schermafbeelding 2020-01-21 om 08.45.18.zip](https://github.com/naimo84/node-red-contrib-ical-events/files/4089764/Schermafbeelding.2020-01-21.om.08.45.18.zip)

**Comment by naimo84** [comment]
Andrè,

this is a "nice" error 😉 

Can you please show me the start and enddate of the generated one, if you set preview to 2 days?

![image](https://user-images.githubusercontent.com/11535502/72786795-d355d000-3c2e-11ea-8995-5e88d5356382.png)

Can you perhaps edit the AppleScript to generate the correct timezone? 

Regards,
Ben

**Comment by ahartman** [comment]
Benjamin,
I used to have an AppleScript that fixed the timezone. However, this has never been necessary for Node-Red and your nodes in the many months that I have been working with Node-Red.

I define an extra event late at night but before midnight, forcing the generation of 3 'blue' events for today. Please find attached the 3 .ics files. Then the upcoming node reports 2 events, including the 1830-2000 but not the - new - last one. When setting 2 days of preview, all nodes for today and tomorrow are reported correctly. Apparently there is an issue with the last node in the day when preview has been set to 1 day.

Regards, André Hartman


[Events.zip](https://github.com/naimo84/node-red-contrib-ical-events/files/4090225/Events.zip)

**Comment by naimo84** [comment]
Unfortunately I'm getting all 3 events:

![image](https://user-images.githubusercontent.com/11535502/72810797-9dc8db00-3c5e-11ea-9264-15d96405fb1e.png)


![image](https://user-images.githubusercontent.com/11535502/72810736-783bd180-3c5e-11ea-9bea-2025075e4c6b.png)

**Comment by naimo84** [comment]
I had one last idea 😉 If this doesn't work also, I'm at my wits' end...

**Comment by ahartman** [comment]
Benjamin,
I propose to wait if this a freak or if the incident returns. This has been running OK for many months. also we have an extremely complex agenda with over 10.000 entries in the Library/Calendars folder.

If all goes well I will droop the blue agenda anyway and use the Upcoming node on the red events.
I will let you know in a couple of days.

Regards, André Hartman

**Comment by Buntstich** [comment]
Maybe the screenshot helps to find the error. Event start and end are displayed in the object one hour too early. The values ​​in the read message are correct. Is there a time zone associated with the formatting (object)?

<img width="1440" alt="Bildschirmfoto 2020-01-25 um 09 33 20" src="https://user-images.githubusercontent.com/52909535/73118741-8b011f80-3f58-11ea-8662-579f0b0ef860.png">

**Comment by naimo84** [comment]
Hi Buntstich, 
thanks for sharing the screenshot. But the eventStart and eventEnd are correct. It's the UTC/Zulu time of the event.
You can see it here: https://jsfiddle.net/naimo84/cwofvu7j/1/

Or via node-red with the following sample flow: 

```json
[{"id":"13c7836.e70097d","type":"inject","z":"ff776b13.2b49d8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":340,"wires":[["33d614c2.16035c"]]},{"id":"33d614c2.16035c","type":"function","z":"ff776b13.2b49d8","name":"","func":"var utcDate = new Date(\"2020-01-25T01:00:00Z\");\nvar localDate = new Date(\"2020-01-25T02:00:00+01:00\");\nreturn { \n    payload: {\n        localDate:localDate,\n        utcDate: utcDate\n    }\n};","outputs":1,"noerr":0,"x":340,"y":340,"wires":[["75c32321.42821c"]]},{"id":"75c32321.42821c","type":"debug","z":"ff776b13.2b49d8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":500,"y":340,"wires":[]}]
```

![image](https://user-images.githubusercontent.com/11535502/73125748-9ed57180-3faa-11ea-94be-11038fcc271f.png)

Javascript interprets both like the same.

Regards, 
Benjamin
