### ISSUE TITLE
Add missing configuration options for caldav to Config Node UI

### ISSUE THREAD

**Issue by andeee** [naimo84/node-red-contrib-ical-events#23]
**Is your feature request related to a problem? Please describe.**
In your code (caldav.ts) is see several config options related to caldav which are not visible in the config node - e.g. config.server (unused), config.calendar (unused - but would be a great addition to restrict to the calendar to use), config.pastWeeks, config.futureWeeks

**Describe the solution you'd like**
I'd would be great if those config options would be configurable using the config node.

**Describe alternatives you've considered**
I could provide a pull request for the configuration options.

**Comment by andeee** [comment]
Are you interested in a pull request? I have some more ideas regarding caldav and I really would like to contribute to this project - so I don't have to start my own implementation. So please leave an answer if you're interested or not.

**Comment by naimo84** [comment]
Hi Andreas, I'm sorry that I didn't answer right before... Currently its a bit busy at home and at work 😉
I would be glad, if you contribute 😀
Please be aware, that the node handels ical and icloud as well. So the config settings should only be visible, if caldav is selected. 

Thanks a lot in advance 

Greetings, 
Benjamin 

P. S. Grüße ins Salzburger Land aus Niederbayern 😉

**Comment by andeee** [comment]
Thank you, Benjamin
und beste Grüße zurück ins benachbarte Bayern.

**Comment by naimo84** [comment]
It seems, that RED.validators.number() requires an input. If it's empty, the config is marked as invalid. I created a custom validator for this ;) I'll push a new version as soon as possible.
