### ISSUE TITLE
Google Calendar - Error Circular

### ISSUE THREAD

**Issue by regissg** [naimo84/node-red-contrib-ical-events#25]
**Describe the bug**
I am using the trigger event node. The source is google calendar and I have from time to time an "error circular" when the Cron runs. Expect for that the trigger seems to work.

Is that normal?

**node-red-contrib-ical-events
 - Version [e.g. 0.1.22]
 - node-red version v1.0.2
 - nodejs version

**Comment by naimo84** [comment]
Hi regissg,

the trigger node saves its cronjobs in the contextstorgae of node-red. When node-red tries to save this, this error occurs from time to time.

I'll have a look at it 😉
