### ISSUE TITLE
recurring appointments

### ISSUE THREAD

**Issue by DevMA99** [naimo84/node-red-contrib-ical-events#26]
Hello,

when I read an recurring appointment via CalDav (Sensor Node), the returning payload is `on: false`. When I remove the "recurring option" inside the appointment the event ist read correct.

Is there an way to get recurring appointments?

thx in advance

**Comment by naimo84** [comment]
Hi DevMA99,

I will have a look at it. What caldav server are you using? 

Regards, 
Benjamin

**Comment by DevMA99** [comment]
Synology

Thank you!

**Comment by DevMA99** [comment]
Super fast -thank you!

As soon as it is available as NodeRed package I will test it!

**Comment by DevMA99** [comment]
it works!

thank you again!

**Comment by sbruhse** [comment]
May I ask which Synology caldav you are using? The caldav package or the Synology calendar? I use the Synology calendar and I get a successful reply, but without any events.
