### ISSUE TITLE
Upcoming events: deleted recurring events still in output msg

### ISSUE THREAD

**Issue by Rene-Auberger** [naimo84/node-red-contrib-ical-events#27]
**Describe the bug**
When using Google Calendar (and maybe other calendar systems, too) the _Upcoming Events_ node does not correctly parse recurring events when single occurances of the event are deleted. Eg I have an event that repeats weekly every monday, wednesday and friday.  Even when I delete a single instance eg on a specific monday, this event is still part of the output form the node although it is no longer displayed on Google Calendar or any other calendar program that uses the ical-feed from this Google Calendar.

**To Reproduce**
1. Create event in Google Calendar that repeats weekly every monday, wednesday and friday
2. delete one or more of the following event instances (not all events), eg next monday and next wednesday
2. pull the upcoming events by defining a timeframe that includes deleted instances (ie next monday and next wednesday)
3. inspect msg output: it contains the event on next monday and wednesday although they have been deleted (which is not correct)
4. delete all of the test-events, pull again as in step 2 and inspect msg output: ther recurring event is no longer in the output (which is correct and desired)

**Expected behavior**
Deleted event instances from a recurring event should not be part of the msg object returned by the node, as these instances do not exist on the calendar.

**node-red-contrib-ical-events
 - Version 0.10.8
 - node-red 1.0.3
 - nodejs 10.18.0

**Comment by naimo84** [comment]
Hi Rene,

many thanks for your detailed bug report. I found the error and fixed it. I'll publish a new version within the next few days 😉 

Regards,
Benjamin

**Comment by Rene-Auberger** [comment]
Sounds great, thank you very much for the quick response and your efforts for this great node!

**Comment by Rene-Auberger** [comment]
Fixed, works for me with v0.11.2

**Comment by Rene-Auberger** [comment]
Hi Benjamin,
this issue re-appeared. Using Google calendar I deleted other event instances of recurring events and they are still showing up in the upcoming events node. It's the same recurring event that I formerly had deleted events from. So my guess is: the upcoming events node can only handle a specific amount of deleted events (or maybe even general changes to recurring events such as movements of event instances or deletions). I created test entries and the first five changes (four deletes and one move) were reflected in the node, all other changes were not reflected in the node.

**Comment by naimo84** [comment]
Hi Rene, 

I'm sorry, that this reappered... A quick test in the morning didn't show the described behaviour unfortunately. 

![image](https://user-images.githubusercontent.com/11535502/81141522-31ec5300-8f6d-11ea-8777-c3a72bfdb7ee.png)

Do you use the latest version?

Greets,
Benjamin

**Comment by Rene-Auberger** [comment]
Yes, I'm using the latest version. I just checked how Google Calendar does this in ical. It add a EXDATE entry for each deleted entry of a recurring event, right? It seems that under whatever circumstances the node does not take all EXDATE into account. I downloaded the ics file from Google Calendar and tested the node with the local file. Same result, deleted dates still show up in the results. I can send you the file via mail for testing, don't want to post it here publicly.

**Comment by naimo84** [comment]
Strange thing... Yes, it adds a EXDATE for every deleted entry. But form my side, there is no limitation. 
It would be nice, if you send me a mail for testing. Whould be a lot easier 😉

**Comment by Rene-Auberger** [comment]
Issue still exists with v 0.15.1.

**Comment by Rene-Auberger** [comment]
Maybe the issue is gone with another configuration change: due to another issue with times I added the environment variable TZ to my nodered docker. That seems to have also solved this issue. I will keep an eye on it and let you know when the issue is gone for a few days or if it was only temporary luck :-)

**Comment by naimo84** [comment]
I'm planning a config setting for the timezone, in order to override the system setting 😉 Timezones are always freaky ^^

**Comment by Rene-Auberger** [comment]
Works for a week now as expected. So setting the correct timezone for the docker container fixed it. You need to pass it as environment variable to the container as described here https://nodered.org/docs/getting-started/docker#setting-timezone

As this was no issue from node-red-contrib-ical-events I close this issue.
