### ISSUE TITLE
Empty Summary

### ISSUE THREAD

**Issue by Techserv-krY** [naimo84/node-red-contrib-ical-events#28]
If I do not enter a subject in our company calendar, it will not be displayed as an event in the node-red.
In the file .ics the VEVENT without subject the SUMMARY: is not listed, nevertheless this should appear as event in Node-Red.

----- Entry with subject
BEGIN:VEVENT
**SUMMARY:Test**
DTSTART;TZID="Mitteleuropäische Zeit":20200124T150000
X-GWITEM-TYPE:APPOINTMENT
DTSTAMP:20200124T131613Z
LAST-MODIFIED:20200124T131613Z
TRANSP:OPAQUE
X-GWSHOW-AS:OUT-OF-OFFICE
X-MICROSOFT-CDO-INTENDEDSTATUS:OOF
STATUS:CONFIRMED
X-GWBOX-TYPE:RECEIVED
........
DTEND;TZID="Mitteleuropäische Zeit":20200124T160000
SEQUENCE:5

PRIORITY:5
CLASS:PUBLIC
X-GWCLASS:NORMAL
END:VEVENT

----- Entry without subject
BEGIN:VEVENT
DTSTART;TZID="Mitteleuropäische Zeit":20200124T150000
X-GWITEM-TYPE:APPOINTMENT
DTSTAMP:20200124T132552Z
LAST-MODIFIED:20200124T132552Z
TRANSP:OPAQUE
X-GWSHOW-AS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
STATUS:CONFIRMED
X-GWBOX-TYPE:RECEIVED
......
DTEND;TZID="Mitteleuropäische Zeit":20200124T160000
SEQUENCE:4

PRIORITY:5
CLASS:PUBLIC
X-GWCLASS:NORMAL
END:VEVENT

**Comment by naimo84** [comment]
Hi Peter,

I found the issue and fixed it with 866384b747fe8331904ca0020915a7ee7d9f1ede. I'll publish a new version within the next few days.

Regards,
Benjamin
