### ISSUE TITLE
Fullday events from past have wrong date

### ISSUE THREAD

**Issue by Rene-Auberger** [naimo84/node-red-contrib-ical-events#29]
**Describe the bug**
A fullday event retrieved from Google Calendar in the past has a wrong date in the field payload[n].date

**To Reproduce**
1. create a fullday event in the past eg two days ago
2. retrieve it with "past view: 1 days"
3. payload[n].date is incorrectly set to todays date

**Expected behavior**
payload[n].date euqals the date we had 2 days ago and is the same as payload[n].eventStart just in a different formating. payload[n].eventStart and payload[n].eventEnd are correct though.

**node-red-contrib-ical-events**
 - Version 0.11.2
 - node-red 1.0.3
 - nodejs 10.18.0

**Comment by naimo84** [comment]
Hi Rene,
I will have a look at it and report back. 
Greetings, 
Benjamin

**Comment by naimo84** [comment]
Hi Rene, 

as requested here https://github.com/naimo84/node-red-contrib-ical-events/issues/22#issuecomment-574022791 pastview: 1 day is targeted to "today".

> Preview works fine, it is past vies that I am struggling with. For me a setting of ‘1 day’ should refer to today, both for preview and for past view. With 3 events in the morning and 3 in the afternoon, I would expect 6 events to be reported at noon, 3 past view and 3 preview.

Perhaps Andrè (@ahartman) can better explain the idea behind it.

But @Rene-Auberger thanks for this issue although. I found another bug while testing this 😉 

Greetings, 
Benjamin

**Comment by Rene-Auberger** [comment]
Hi Benjamin,
I have no issue with the event being part of the resultset. My issue is that it has set the property `date` to todays date (which is wrong I would say). The properties `eventStart` and `eventEnd` are correctly set to the same value as in Google Calendar:

![Bildschirmfoto 2020-02-10 um 10 36 48](https://user-images.githubusercontent.com/11235992/74138977-d96a1b80-4bf2-11ea-9a91-0f522df53934.png)

**Comment by ahartman** [comment]
Benjamin, Rene,
I think there are two different things here.
How to set post and preview for today - days = 1 - is clear.
However, Rene talks about the date property; I do not use that.
Is that the create data in HA or the original create date in iCloud?
For me the create date in HA is pretty irrelevant, so I would set it to the create date in iCloud or delete the property.
Regards, André Hartman

**Comment by Rene-Auberger** [comment]
For future events `date` is at least set to the event start date in the local timezone. That's why I at least assumed that `date` is always the start date of an event in the local time zone. However, if this is not the intention of `date` I could switch my flow to use `eventStart` and calculate the local date.

Maybe in general a documentation of the different fields in the resultset of the node would be good (even if most is self-explanatory).

**Comment by ahartman** [comment]
Rene,
There is no need to calculate the local date, as eventStart and eventEnd are local dates, they are only displayed as UTC. As said, I have no idea what the 'date' property represents as I only use eventStart and eventEnd.
Regards, André Hartman

**Comment by naimo84** [comment]
Hi Rene,

should be fixed with the latest version 😉 

Greets,
Benjamin

**Comment by Rene-Auberger** [comment]
Great, thanks! Just installed it and I will see tomorrow if it works as expected with todays fullday event. I will then close this issue.
Regards,
René

**Comment by Rene-Auberger** [comment]
Works - thank you!
