### ISSUE TITLE
Can this be used with CalDav?

### ISSUE THREAD

**Issue by juggledad** [naimo84/node-red-contrib-ical-events#3]
Just wondering if this could be used with a CalDav server? I tried it but the 'Calender Events' came back with a "401: Unauthorized". The calendar does have security set on it (userid/password)

**Comment by naimo84** [comment]
Hey juggledad,

currently my nodes don't have an option to set user and password. But this feature is on my list 😉 

But: my newborn is two weeks old. So Findung time is the bigger problem 😀

I'll try to implement this soon, if it's possible 

Regards, 
Benjamin

**Comment by juggledad** [comment]
Congratulations on the new baby!!!! 

If I can be of any help (not with the baby, I've raised three of my own and helped raise 5 grandkids and three of them live up the street) let me know. If I can find some time, I might look at the code myself.

**Comment by naimo84** [comment]
Thanks for the congratulations 😄 

It's my first one. Coding node-red nodes is much easier, than handling this little "thing" 😃 

I've added a basic authentication to the nodes, so please have a look at version 0.3.0

**Comment by juggledad** [comment]
> Coding node-red nodes is much easier, than handling this little "thing"

HaHa, you  should have seen my wife and I try to change the first diaper when we stopped at my folks on the way home from the hospital. It came to be know as the "Great Diaper Incident" Two adults loosing to a 4 day old child!

Tried version 0.3.0 and I get a **Error: 500 Internal Server Error** and the node has a red block with [Object, Object] showing under it.

I'm trying this with a Baikal server (caldav) that I have been using since 2015 with BusyCal on a Mac in case that makes a difference.

**Comment by naimo84** [comment]
Hmm, if it comes to a 500 error, my basic auth implementation should have worked as expected.

I'll try to setup a baikal server on my own, and See What happens. Will report back with New informations 😉

**Comment by naimo84** [comment]
I've installed a baikal server ;)

Please have a look at v0.4.0 😄 

---

## Baikal administration

It seems, that the "WebDAV authentication type" has to be: _Basic_

![image](https://user-images.githubusercontent.com/11535502/67157317-e05edc80-f32a-11e9-9a65-b49ef53f99b7.png)

---

## Baikal user calendars

And I had to expand my nodes for CalDAV functionality at all. CalDAV seems to use ical/ics in the background for a single calendar event. 

![image](https://user-images.githubusercontent.com/11535502/67157339-1a2fe300-f32b-11e9-8e5b-f9d605eded7e.png)

---

## Config nodes

There is a new option for that in the config, now:

![image](https://user-images.githubusercontent.com/11535502/67157357-52cfbc80-f32b-11e9-852b-fbc4c3bb7dd2.png)

The URL has to be the CalDav path.

**Comment by juggledad** [comment]
Nicely done!! I did have to upgrade Baikal to the latest version and change from authentication type 'Digest' to 'Basic' and now it is working great!

p.s. I hope the baby is sleeping thru the night, but if not, I hope you are (grin)

**Comment by naimo84** [comment]
Nice to hear, it's working now 😁

The nights are ok, waking up every 4 hours is not as hard as I thought it would be 😉
