### ISSUE TITLE
Please add example flows

### ISSUE THREAD

**Issue by Mannshoch** [naimo84/node-red-contrib-ical-events#30]
**Is your feature request related to a problem? Please describe.**
I'm new in node-red. I'm trying and not able to get any usefull.

**Describe the solution you'd like**
Please describe the text fields better. How do a filter expression work (regex?) 
Please add example flows for each node and different possibilities.
eg.:
calendar entry with title, description and category setup as a repeated event and output to the debug node.
Show a Flow which do:
Set a trigger if a calendar item start and set a trigger if the calendar item enddate is reached.

**Describe alternatives you've considered**
probing around and using **:memo : Documentation**

**Comment by naimo84** [comment]
Hi Mannshoch,

I'll do my best to write useful examples.

Greetings,
Benjamin

**Comment by naimo84** [comment]
a first version was added with https://github.com/naimo84/node-red-contrib-ical-events/commit/151097d979783118bb5558180b973d27cce0667e

**Comment by Mannshoch** [comment]
THANKS! Found my Error and was now able to set up my Idea as wished. I was able to set up all my Ideas with the Event Sensor.

The only Problem I have is the event trigger, which also is the cause form y problems. It seems not working in any config. Even your example seems not working. (I use an *.ics file)
