### ISSUE TITLE
Make iCal configuration dynamic

### ISSUE THREAD

**Issue by W7T2A** [naimo84/node-red-contrib-ical-events#31]
**Is your feature request related to a problem? Please describe.**
I use your node to import several external calendars.
It would be awesome to make the ical configuration dynamic (e.g. like the dynamic config option of the http request node (pass msg.url / msg.method, etc.))
So you can pass an array / query database or anything like that to pass the config dynamically to your ical node for iterating and importing multiple icals.

**Describe the solution you'd like**
Just pass the url / type of the calendar to import as attribute of the msg-object.
A good working example is dynamic config option of http request node.

**Additional context**
Thanks for the awesome work!
I really like your node and using it as default for ical imports.

**Comment by naimo84** [comment]
Hi W7T2A,

Thanks for using my nodes as your default. Nice to hear 😊

I'll have a look at it and will report back soon. Generally it should be no big deal to implement this 😉

Greetings, 
Benjamin

**Comment by naimo84** [comment]
Hi and sorry for the big delay. Busy working days, plus a time-consuming little baby lead to little spare time 😉 

May you please try the latest version?

**Comment by W7T2A** [comment]
@naimo84 absolutely no problem - I've already included the changes in my flow and works like charm :+1 :-)

**Comment by naimo84** [comment]
I'll make the config node not required, so a dummy config would not be necessary 😉
