### ISSUE TITLE
Recurring event not properly recognized by "ical-upcoming" node

### ISSUE THREAD

**Issue by e-lange** [naimo84/node-red-contrib-ical-events#33]
The _ical-upcoming_ node does not properly show the upcoming events of a recurring event.

1. Import the attached event (see below) to an ical-server.
2. Configure _ical-upcoming_ to look for the next e.g. four days
3. You will only see one event instead of the expected next four events

I expect to see all upcoming events in the configured interval of the node:
![image](https://user-images.githubusercontent.com/58532249/75621390-f95a8280-5b93-11ea-89b2-647b6d73eda9.png)

The returned payload only includes a single event but not all events within the configured interval (see above):
`[{"date":"02.03.2020 06:45-07:30",
"event":"Warmmacher",
"summary":"Warmmacher",
"topic":"Warmmacher",
"calendarName":"Erdgeschoss",
"eventStart":"2020-03-02T05:45:00.000Z",
"eventEnd":"2020-03-02T06:30:00.000Z",
"description":"",
"id":"FF925405-5BED-4F01-8125-61CE6A275A8B",
"allDay":false,
"rule":" ",
"location":"",
"countdown":{"days":0,"hours":23,"minutes":7,"seconds":13}}]`

My guess is that the recurrence rule is not properly interpreted.

node-red-contrib-ical-events version: 0.11.4
node-red version: 1.0.3
nodejs version: 13.7

ICAL text:
`BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.15.2//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:MESZ
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:MEZ
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20200217T005054Z
UID:FF925405-5BED-4F01-8125-61CE6A275A8B
RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR
DTEND;TZID=Europe/Berlin:20200217T073000
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:Warmmacher
LAST-MODIFIED:20200217T005134Z
DTSTAMP:20200217T005138Z
DTSTART;TZID=Europe/Berlin:20200217T064500
SEQUENCE:1
END:VEVENT
END:VCALENDAR`

**Comment by naimo84** [comment]
Hi e-lange, 

I'll have a look at it and will report back soon.

Greets, 
Benjamin
