### ISSUE TITLE
Cache calendar data

### ISSUE THREAD

**Issue by Mannshoch** [naimo84/node-red-contrib-ical-events#35]
**Is your feature request related to a problem? Please describe.**
I have some cases where the internet connection is not stable.

**Describe the solution you'd like**
Please allow to activate caching.  Download the Calendardata and use them.

**MockUp**
![grafik](https://user-images.githubusercontent.com/7795891/75976221-4ca53b80-5eda-11ea-8d46-83dce657a6fb.png)

**Comment by naimo84** [comment]
Hi again,

I'll have a look at this and will report back.
Caching might be a bit tricky in this context.

Benjamin

**Comment by naimo84** [comment]
Hi Mannshoch,

my you please have a look at v0.13.0? For now I don't have a setting for the cache-duration. Default is unlimited caching.

Greets,
BEnjamin

**Comment by naimo84** [comment]
Should be implemented in the latest version 😉
