### ISSUE TITLE
Public icloud calender no events

### ISSUE THREAD

**Issue by wormiedk** [naimo84/node-red-contrib-ical-events#37]
**Describe the bug**
When I ad a public link from an icloud calendar no events are found

**To Reproduce**
1. Add a public link from an icloud calendar: webcal://p57-caldav.icloud.com/published/.... 
2. config: I tried both caldav which produces - "get calendars went wrong" and iCal
3. ouput. 0 events and an empty html table even though there are events in the calendar

**Expected behavior**
A number of appointments

**node-red-contrib-ical-events
 - Version 0.12.1
 - node-red version 1.03
 - nodejs version 12.16.1

**Comment by wormiedk** [comment]
I now took the time to set the same calendar up as a secure calendar. Now I do get event but only from the next two days eventhough I have set the days ahead to 14.

**Comment by naimo84** [comment]
Hey Wormiedk,

unfortunately I think, the CalDav library I use, is unable to handle caldav requests without authentication....

I have to research, why the secure type is not working correctly.

Regards,
Benjamin

**Comment by wormiedk** [comment]
I guess that means you have fixed the issue. I tried running:



`git clone https://github.com/naimo84/node-red-contrib-ical-events.git
cd node-red-contrib-ical-events
git checkout abcfc7f5ebd4882d2d551cbc220148de6eb3f020
npm install
gulp
cd ~/.node-red
npm install /path/to/node-red-contrib-ical-events`

However when I run the last command i get an error:
`pi@domopi:~/.node-red $ npm install /home/pi/node-red-contrib-ical-events/
npm WARN node-red-node-test-helper@0.2.3 requires a peer of node-red@~0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /home/pi/.node-red/node_modules/.staging/node-red-contrib-ical-events-781dda18/node_modules/@babel/code-frame
npm ERR! dest /home/pi/.node-red/node_modules/.staging/@babel/code-frame-27285286
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/home/pi/.node-red/node_modules/.staging/node-red-contrib-ical-events-781dda18/node_modules/@babel/code-frame' -> '/home/pi/.node-red/node_modules/.staging/@babel/code-frame-27285286'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-03-12T06_31_50_579Z-debug.log
pi@domopi:~/.node-red $`

**Comment by naimo84** [comment]
I published the fixed version to the registry. I can't imagine why this error happens...

**Comment by naimo84** [comment]
Should be fixed with the latest version 😉
