### ISSUE TITLE
Event trigger or event sensor on change output do not work

### ISSUE THREAD

**Issue by regissg** [naimo84/node-red-contrib-ical-events#38]
Event trigger or event sensor on change output do not work. 

Event sensor does work well on tick output which indicates that the link with google calendar is properly set.

node-red-contrib-ical-events version 0.12.1
 - node-red version V1.0.4
 - nodejs version v12.13.0

**Comment by regissg** [comment]
I should add that the events I want to trigger are daily recurring events (I am using calendar to set the temperature of my home heating system)

**Comment by naimo84** [comment]
Hi @regissg, 

a quick test works for me at my dev machine 😞 

![image](https://user-images.githubusercontent.com/11535502/76421756-71028b80-63a4-11ea-8f70-96210f19a0c3.png)

the event ended on 14:25:00 and the change was correctly triggered.
Do you have more than one event at the same time? So to say: concurrent events?

Are you using trigger and filter?

![image](https://user-images.githubusercontent.com/11535502/76422117-fede7680-63a4-11ea-9ac2-3ba4bcc8b830.png)


Greetz,
Benjamin

**Comment by regissg** [comment]
Thanks Benjamin for your response.
I have run a simple test like yours and I am now able to have proper behavior for both outputs of the event-sensor. But as you could see below the event-trigger node is not responding (it usually generates an error-circular).
I am using Google calendar with, for this example, a single event with no recurrency and no concurrent event.

I have set all nodes to a 1mn check cycle with the following cron */1 * * * * for the event-trigger

![ical](https://user-images.githubusercontent.com/19576754/76432716-a367b500-63b3-11ea-93a6-c37b745cf460.jpg)

Regards
Régis

**Comment by naimo84** [comment]
Hi Régis,

may you please have a look at v0.12.2?

Regards,
Benjamin

**Comment by regissg** [comment]
Hello Benjamin,
Sorry for my late reply. 
I have tried v.0.13 and the  event-trigger node does work now.
Many thanks for the fix.
Régis
