### ISSUE TITLE
this.metric is not a function

### ISSUE THREAD

**Issue by rikki78** [naimo84/node-red-contrib-ical-events#39]
**Describe the bug**
An uncaught exception occurs, when trying to use the ical-sensor

**To Reproduce**
1. Ical sensor, checking every minute to match a string
2. google calendar ics
3. node red restarts
```
13 Mar 13:59:00 - [red] Uncaught Exception:
13 Mar 13:59:00 - TypeError: this.metric is not a function
    at Node.send (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:427:10)
    at cronJobStart (/config/node-red/node_modules/node-red-contrib-ical-events/dist/ical-events.js:176:9)
    at CronJob.fireOnTick (/config/node-red/node_modules/cron/lib/cron.js:600:23)
    at Timeout.callbackWrapper [as _onTimeout] (/config/node-red/node_modules/cron/lib/cron.js:667:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
**Expected behavior**

**Screenshots**

**node-red-contrib-ical-events
 - Version 0.12.1
 - node-red version v1.0.4
 - nodejs version

**Additional context**

edit: it looks like this error comes when an event starts. After the initial error and node red restart, the error doesnt show up anymore

**Comment by naimo84** [comment]
Hi rikki,

may you please have a look at v0.12.2? I fund a similar error yesterday at the same code.

Greetz,
Benjamin

**Comment by rikki78** [comment]
this gives more errors... 
```
npm ERR! code ELOOP
npm ERR! syscall open
npm ERR! path /config/node-red/node_modules/node-red-contrib-ical-events/npm-shrinkwrap.json
npm ERR! errno -40
npm ERR! ELOOP: too many symbolic links encountered, open '/config/node-red/node_modules/node-red-contrib-ical-events/npm-shrinkwrap.json'
```

**Comment by rikki78** [comment]
Sorry - I did that wrong myself. I will test the latest version.

**Comment by rikki78** [comment]
Your update fixed it.
Thanks for the quick responses!
