### ISSUE TITLE
Nothimg happens

### ISSUE THREAD

**Issue by KeesKemper** [naimo84/node-red-contrib-ical-events#4]
See below my flow. Nothing happens at all when I inject a timestamp. 

[flows.txt](https://github.com/naimo84/node-red-contrib-ical-events/files/3727866/flows.txt)

**Comment by naimo84** [comment]
Currently my nodes only handle upcoming future events. 

Unfortunately your ical doesn't have a event in the future ;)

**Comment by KeesKemper** [comment]
For me it's okay that you only find future events, but I'm surprised to hear that there are no such events in my calendar. I have a Python script that really finds events in the future. 
The node doesn't generate any message, also not an empty one.

**Comment by naimo84** [comment]
I'm sorry, it was my mistake. I didn't look close enough...
Can you please have a look at version 0.2.3? I made the Previewdays configurable (only events between now and this range are handled). Before it was hardcoded: 10 days.

Although one of your Events is tomorrow... I don't know, why it was not handled before my changes...

**Comment by KeesKemper** [comment]
It's the same with version 0.2.3.

The node doesn't seem to contact the calendar.

**Comment by naimo84** [comment]
Is your debug-node enabled?
In your example-flow it's disabled.
![image](https://user-images.githubusercontent.com/11535502/66911702-5c96ae80-f011-11e9-9ba4-c38462d1a162.png)

If I enable it, it takes some time because the ics has 400 Events, that have to be parsed by my node.
But the result is the following:

![image](https://user-images.githubusercontent.com/11535502/66911915-c3b46300-f011-11e9-92b9-6634598ceeaa.png)

**Comment by KeesKemper** [comment]
Yes, I disabled by accident the debug-node. I had no idea that it was possible to disable it. Now it works.
Thanks a lot for your help.
Are there also plans to process the objects with a rule?

**Comment by naimo84** [comment]
Yes, rrules are planned, but my newborn is currently 2 weeks old. So finding time is the problem 😉

**Comment by KeesKemper** [comment]
Congratulations! Is everything OK with the child and the mother?
Of course rrules are less relevant. To be honest, the biggest part of my live I have done without rrules.
