### ISSUE TITLE
Private Google ical calender with shared url and recurring all day events no entries

### ISSUE THREAD

**Issue by Gizmoh1683** [naimo84/node-red-contrib-ical-events#42]
**Describe the bug**
I have an private google calender and added this with the private share ical url to the ical node. The calender only includes recurring all day events. The node just gets an empty array

**To Reproduce**
1. input: private share ical adress of google calender with recurring all day events
2. config private ical share url as calendar url
3. ouput nothing

**Expected behavior**
I want to get the events in the next days. I've also increased the preview period.

**node-red-contrib-ical-events
 - Version 0.13.0
 - node-red version 1.0.3
 - nodejs version 10.19.0

**Comment by naimo84** [comment]
Hi Gizmoh,

a quick test on my dev machine with my google calendar results in the correct behavior (see below). 
May I ask, what node you are using? upcoming, trigger or event?

a export of the flow whould be nice 😉 

Kind regars,
Benjamin

![image](https://user-images.githubusercontent.com/11535502/77249178-95c9ef00-6c3f-11ea-9016-68d21e360c16.png)

**Comment by Gizmoh1683** [comment]
Hi Naimo,

i'm using the upcoming Node. Here's an export of my flow:

`[{"id":"4b200b96.c493e4","type":"ical-upcoming","z":"8c7325e.128bad8","confignode":"ca35bb55.c9e028","cron":"","timeout":"1","timeoutUnits":"hours","name":"Abfallkalender","offset":"","endpreview":"","endpreviewUnits":"","preview":"60","previewUnits":"days","pastview":"10","pastviewUnits":"days","trigger":"always","filter":"","x":460,"y":320,"wires":[["1e68df0f.8a0321"]]},{"id":"ca35bb55.c9e028","type":"ical-config","z":"","url":"https://calendar.google.com/calendar/ical/b3bmfntnakvicd18if7k9soiqo%40group.calendar.google.com/private-bf38decce709d4984f880c82378b8e6f/basic.ics","username":"","password":"","caldav":"false","name":"","language":"de","replacedates":false,"calendar":"","pastWeeks":"0","futureWeeks":"4"}]`

There are 3 all day events this week.

Kind regards
Gizmoh

**Comment by Jardland** [comment]
Hi Benjamin
I have a similar issue, but only if there are 2 or more recurring events.
Different result depending on how the events are made.
3 events 3 different days with weekly recurring you only see the last one.
2 events 3 day each you only see the last day of the first one second event OK.
Pictures attached is for 2 events 3 days.
<img width="634" alt="Skärmavbild 2020-03-23 kl  11 02 20" src="https://user-images.githubusercontent.com/16799691/77305117-c66c6000-6cf5-11ea-80a0-76e71fcdbd17.png">
<img width="299" alt="Skärmavbild 2020-03-23 kl  11 06 15" src="https://user-images.githubusercontent.com/16799691/77305480-5ad6c280-6cf6-11ea-8af3-c5fe73585def.png">

Kind regards,
Thomas

**Comment by naimo84** [comment]
Hi Gizmoh, 

thanks for sharing your flow. Unfortunately it's also working for this (see below).
Maybe your debug-node is disabled?

Kind regards,
Benjamin


![image](https://user-images.githubusercontent.com/11535502/77345128-7e206280-6d34-11ea-85e9-049881579aad.png)

**Comment by naimo84** [comment]
@Jardland : Hi Thomas, 
are you using a CalDav instead of a Google Calendar. If yes, then I maybe found the problem within another issue. I'll publish a new version soon.

Regards,
Benjamin

**Comment by Jardland** [comment]
Hi Benjamin
Yes I am using CalDav. 

Regards,
Thomas

**Comment by Gizmoh1683** [comment]
Hi Benjamin,

the debug node is enabled. I just get an empty array:

![image](https://user-images.githubusercontent.com/9698670/77394302-47336680-6d9f-11ea-9940-aef712f2bdef.png)

**Comment by Jardland** [comment]
Hi Benjamin
I have tried the new version, but now I cant get anything, debug node totally empty no error.
If I try iCal settings from a shared calendar then it is OK.

Best regards 
Thomas

**Comment by naimo84** [comment]
Sorry Thomas for this,

can you please send me an export of your flow? That would make it easier for me.

Thanks and regards,
Benjamin

**Comment by Jardland** [comment]
Hi Benjamin
Here is it
[{"id":"5d8c9f56.9ac07","type":"ical-sensor","z":"d2958269.18657","confignode":"1cc0f7cc.f0919","timeout":"1","timeoutUnits":"minutes","name":"","trigger":"always","filter":"","x":430,"y":220,"wires":[["328e6a16.7bb936"],["328e6a16.7bb936"]]},{"id":"1cc0f7cc.f0919","type":"ical-config","z":"","url":"https://jardland.se/cloud/remote.php/dav/calendars/thomas/","username”:”***”,”password”:”***,”caldav":"true","name":"test caldav","replacedates":false,"calendar":"Openhab","pastWeeks":"0","futureWeeks":"4"}]

It works in 0.13.0 except for recurring events CalDav.
Regards 
Thomas

**Comment by naimo84** [comment]
Unfortunately I had to remove futureWeeks and pastWeeks with #43. For the sensor node it should be not necessary, but for the upcoming, the default is 10 days preview and 0 days pastview.

May this be the error? Can you perhaps send me some Credentials to git@neumann-benjamin.de?

**Comment by naimo84** [comment]
Thanks for sharing the test credentials @Jardland . It was a NullPointerException, that caused the difference between the versions 😉

**Comment by Jardland** [comment]
Hi Benjamin
Many thanks for the quick update. It works as expected for me now.
Best regards 
Thomas

**Comment by naimo84** [comment]
no problem, greetings to sweden :sweden:
