### ISSUE TITLE
Upcoming Node only showing last recurring event

### ISSUE THREAD

**Issue by unclej84** [naimo84/node-red-contrib-ical-events#43]
**Describe the bug**
When using the Upcoming-event node with recurring events, only the last event is output (e.g. weekly events, configuration node "future weeks 4" only event in 4 weeks shown - not next week)

**To Reproduce**
1. CalDav with recurring events
2. set up configuration node with time frame to multiple time difference of event
3. only most future event is given

**Expected behavior**
Next upcoming event should be output.

**Screenshots**

**node-red-contrib-ical-events
 - Version 0.13.0
 - node-red version 1.0.4
 - nodejs version 10.19.0

**Additional context**

**Comment by naimo84** [comment]
Hi unclej,

I'll have a look at it and will report back.

Kind regards,
Benjamin

**Comment by naimo84** [comment]
Hi unclej, 

I think, I found the issue. But I had to move future- and pastWeeks (pullrequest: https://github.com/naimo84/node-red-contrib-ical-events/pull/24) from config to preview and pastview of the node itself. 

I'll publish a new version as soon as possible.

Greets,
Benjamin

**Comment by naimo84** [comment]
Should be fixed with the latest version 😉

**Comment by unclej84** [comment]
Confirmed - fixed in 0.14.0. Thanks for the fast fix.
