### ISSUE TITLE
Synology CalDav Server

### ISSUE THREAD

**Issue by bee-eater** [naimo84/node-red-contrib-ical-events#44]
Hey there,

first of all thanks for that great plugin, even if it doesn't yet work for me :-)

When I try to connect to my local CalDav Server on my Synology, I just end up getting the error:
"CalDAV -> get calendars went wrong. Error: Bad status: 0"

Normaly, e.g. from OpenHAB I was able to get the calendar by using an url like this:
`https://<SynologyIP>:<Port>/web/Calendar/MyCalendar/`

I don't know if it should work, but I tried a lot of combinations. What is the parameter "Name" in the ical-config node exactly for? I tried using `https://<SynologyIP>:<Port>/web/Calendar/` and Name `MyCalendar` but I always ended up getting the same error. 

I did set Username and Password as well as Type: CalDav.

Any ideas? What does the error exactly state? 

Best regards,
Marcel

**Comment by naimo84** [comment]
Hi Marcel,

I'll have a look at it and will report back ;)

Best regards from Bavaria to Bavaria ;)
Benjamin

**Comment by naimo84** [comment]
version 0.14.2 should be online. I'll close this for now. Feel free to reopen, if issue is not fixed.

**Comment by naimo84** [comment]
I forgot to mention: Name is only the Displayname of the node, like in any other nodes of node-red.

 With my local diskstation, this https://<SynologyIP>:<Port>/web/Calendar/MyCalendar/ works as expected 😉

**Comment by bee-eater** [comment]
Hey Benjamin,

great! Thanks for your effort! I think it could work - at least I'm not getting any errors - but: currently I'm getting no debug output what so ever! I just took a look at my nodered.service status and found multiple entries like this:

`UnhandledPromiseRejectionWarning: Error: unable to verify the first certificate`

Is the validation of the certificate handled in the node or is it a NodeRED setting? 

Best regards and thanks again :-)
Marcel

**Comment by naimo84** [comment]
Hey Marcel, 

I'm really sorry for that. I published the version one commit to early.... For now I added a rejectUnauthorized property (default is false). With this, https should also work 😉 

v0.14.3 is on the way

Best regards,
Benjamin

**Comment by bee-eater** [comment]
Hey Benjamin,

great! Thanks again for this quick fix! You're awesome! Now everything works as expected.

Best regards,
Marcel
