### ISSUE TITLE
1 Days doesn

### ISSUE THREAD

**Issue by bee-eater** [naimo84/node-red-contrib-ical-events#46]

**Comment by bee-eater** [comment]
Hey Benjamin,

found something :-)

When I tested the 0.14.3 version yesterday for https (lets say 10:30 pm) and I had set the "Preview" parameter to 1 Day, I didn't get any results! Only when I set the "Preview" to 24 hours, I got my two calendar entries! This behavior is reproducible for me!

Is the "Preview" like "Rest of the day"? 

Also I didn't find any descriptions on when the automatic check of the upcoming node is executed! Is it the timestamp at the node? 22:00 ? 

Best regards,
Marcel

**Comment by naimo84** [comment]
Hi Marcel,

yes, this comes from this issuecomment: https://github.com/naimo84/node-red-contrib-ical-events/issues/12#issuecomment-551449253.

Setting to days means complete days 😉 If you want really 24 hours, then yes, you have to set it like this.

And yes, the timestamp at the node shows the next check date.

Servus,
Benjamin
