### ISSUE TITLE
Sensor : Only one event but two messages

### ISSUE THREAD

**Issue by Steve2k** [naimo84/node-red-contrib-ical-events#47]
Hello,

I try to use the sensor node. I don't know if I do something wrong but here is my configuration : 
- I use sensor node with Trigger Always
- debug node on every ticks

**Case 1 :** no event in the calendar -> only one message from debug node `{"on":false}`
**Case 2 :** one event is configured -> two messages from debug node 
1 : `{"summary":"TestEvent","topic":"TestEvent","id":"0bfd5fe3-74b6-4688-b742-b6165fe1efb91587196800000","location":"","eventStart":"2020-04-18T08:00:00.000Z","eventEnd":"2020-04-18T09:15:00.000Z","description":"TestEvent","on":true,"calendarName":null,"countdown":{"days":-1,"hours":-2,"minutes":-15,"seconds":-31}}`
2 : `{"on":false}`

I don't understand why there is two messages and not only the message with the event.

Thank you in advance and thank you for your work,

Steve

**Comment by naimo84** [comment]
Hi Steve,

What type (caldav, ical, icloud) und are you using? is the Event a recurring one?

Then I will have a look at it and will report back

Greets 
Benjamin

**Comment by Steve2k** [comment]
Hi,

I use CalDav type and it's not a recurring event. The calendar is on a Synology.
I use the version 0.14.4 of the node.

Regards,

Steve

**Comment by naimo84** [comment]
I'm sorry for that, with the patch last week I forgot to return the correct value of the sensor...

Should be fixed with version 0.14.5. It's already on the way 😉

**Comment by Steve2k** [comment]
After re-install the node, it's working fine. Thank you for all and your quick help.

Regards,

Steve
