### ISSUE TITLE
iCal - No events in list

### ISSUE THREAD

**Issue by tsprivate** [naimo84/node-red-contrib-ical-events#48]
Hi,

I was trying your latest node and created my Outlook ICS link. For testing I added this link to my Google-Calendar and it is showing all events properly.
![image](https://user-images.githubusercontent.com/41630517/81514286-9d6d6080-9371-11ea-8383-9e590d355395.png)

Unfortunately, when reading the events by your node it is not detecting any events. I checked on the day only as well upto 10 days in future/past.

![image](https://user-images.githubusercontent.com/41630517/81514302-b6761180-9371-11ea-89fe-fda81601cf13.png)

`{"today":0,"tomorrow":0,"total":0,"htmlTable":"<span>","payload":[],"_msgid":"a60425e1.7fab78"}`

Thanks for any advise

**node-red-contrib-ical-events
 - node-red version 1.0.6

**Comment by adampetrovic** [comment]
I'm also seeing the same behaviour

**Comment by naimo84** [comment]
Hey, 

excuse the circumstances. Can you please send me the URL to my mail address git@naimo84.dev? It would be a lot easier to debug for me.

A first quick test with my outlook.com calendar was successful 😞 

![image](https://user-images.githubusercontent.com/11535502/81649794-28f9f680-9431-11ea-8ef7-a932e18e3776.png)
![image](https://user-images.githubusercontent.com/11535502/81649828-357e4f00-9431-11ea-9400-77767a6ac7bf.png)


I'll have a look at it as soon as possible.

Greetings
Benjamin

**Comment by chrisgla** [comment]
I just setup Outlook ical this evening, working ok for me.

Could you please expand "Filter" explanation a little in notes, maybe with some examples?

For instance, filter on payload[x].event = "Say Hello"

Sorry for being simple!

**Comment by tsprivate** [comment]
I see you have removed deprecated timezone which should solve the issue.

By when will you release the update so we can test?

**Comment by naimo84** [comment]
Hey, 
I'm sorry. Sometimes I don't understand how flows.nodered.org synchronizes packages...
I published the v0.15.1 a week ago, but nodered didn't pull the latest version...

Now I had to "request the refresh", so it's on the way.

Greetings,
Benjamin

![image](https://user-images.githubusercontent.com/11535502/82446154-6cdea280-9aa6-11ea-9a73-2f269ab0811b.png)

**Comment by tsprivate** [comment]
not there yet ;)

**Comment by naimo84** [comment]
But it should be :(

![image](https://user-images.githubusercontent.com/11535502/82633107-99a3ce80-9bfa-11ea-99f3-a3a7b7c4d49f.png)

**Comment by tsprivate** [comment]
all good .. it is now available .. and working fine !!

thanks a lot
