### ISSUE TITLE
Repeating Events are Ignored

### ISSUE THREAD

**Issue by jstride** [naimo84/node-red-contrib-ical-events#5]
When using the upcoming node, only single events are shown. Repeating events that occur in within the chosen time frame are not shown.

**Comment by naimo84** [comment]
Hi jstride,

is it a ical or caldav? Supporting caldav is a brand new feature 😉 see #3

I'll See, what's Happening, if i define rrules for my calendars and will report back

Greets, 
Benjamin

**Comment by jstride** [comment]
Just an ics file from Outlook online

**Comment by naimo84** [comment]
Thanks. I'll have a look at it

**Comment by jstride** [comment]
Let me know if you need any help testing. I can't see this pushed through to node red as of now.

**Comment by naimo84** [comment]
It should be implemented in version 0.4.3

flows.nodered.org shows already this Version 😉
