### ISSUE TITLE
"Error: WARNING: Date in past. Will never be fired."

### ISSUE THREAD

**Issue by MimicLynx** [naimo84/node-red-contrib-ical-events#50]
Hi,
 not sure if anybody else has that problem. nodes stopped working in the last 2 months. updated it and now they kind of work. i only get the error output when the event should trigger, but no other message to trigger a flow.

Raspberry Pi 3 Model B Rev 1.2
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

`[
    {
        "id": "2c370c46.a1c604",
        "type": "debug",
        "z": "5c44c3fe.2f0ffc",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 650,
        "y": 600,
        "wires": []
    },
    {
        "id": "ba6176c1.567118",
        "type": "ical-events",
        "z": "5c44c3fe.2f0ffc",
        "confignode": "8c8d8f24.decec",
        "timeout": "5",
        "timeoutUnits": "seconds",
        "cron": "",
        "trigger": "always",
        "filter": "",
        "name": "",
        "offset": "-16",
        "offsetUnits": "minutes",
        "x": 450,
        "y": 600,
        "wires": [
            [
                "2c370c46.a1c604"
            ],
            [
                "2c370c46.a1c604"
            ]
        ]
    },
    {
        "id": "44444a2f.305304",
        "type": "inject",
        "z": "5c44c3fe.2f0ffc",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "5",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "x": 250,
        "y": 600,
        "wires": [
            [
                "ba6176c1.567118"
            ]
        ]
    },
    {
        "id": "8c8d8f24.decec",
        "type": "ical-config",
        "z": "",
        "url": "https://calendar.google.com/calendar/ical/XXXXXXXXXXXXXXXgroup.calendar.google.com/public/basic.ics",
        "username": "",
        "password": "",
        "caldav": "false",
        "name": "",
        "language": "de",
        "replacedates": true,
        "usecache": true,
        "calendar": "",
        "pastWeeks": "0",
        "futureWeeks": "4"
    }
]`

**Comment by shortyishere** [comment]
I have same problem.

**Comment by naimo84** [comment]
Hey you two,

sorry for the circumstances. May you please verify, if the timezone on your host systems is correct?
It sounds like an error from causing from different timezones.

kind regards,
Benjamin

**Comment by MimicLynx** [comment]
Hey, will check that and get back to u

**Comment by MimicLynx** [comment]
so raspi time under raspi-config is:

Current default time zone: 'Europe/Berlin'
Local time is now:      Mon Jun 15 13:06:39 CEST 2020.
Universal Time is now:  Mon Jun 15 11:06:39 UTC 2020.

which is correct

**Comment by shortyishere** [comment]
Mine is the same only a different time zone...I noticed in your code you only once looked at the time offset and not any other time...is this by design?

**Comment by naimo84** [comment]
v0.15.2 is on the way 😉
