### ISSUE TITLE
Timezone mixup when pulling events

### ISSUE THREAD

**Issue by mvondemhagen** [naimo84/node-red-contrib-ical-events#51]
.ics file shows:

```
BEGIN:VEVENT
UID:***SECRETDATA***
SUMMARY:Discussion
DTSTART;TZID=Pacific Standard Time:20200616T110000
DTEND;TZID=Pacific Standard Time:20200616T113000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200615T222525Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:***SECRETDATA***
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

node shows same event as:
```
{	"date":"16.06.2020 11:00-11:30",
	"event":"Discussion",
	"summary":"Discussion",
	"topic":"Discussion",
	"eventStart":"2020-06-16T09:00:00.000Z",
	"eventEnd":"2020-06-16T09:30:00.000Z",
	"id":"***SECRETDATA***",
	"allDay":false,
	"rule":" ",
	"location":"***SECRETDATA***",
	"countdown":{
		"days":0,
		"hours":10,
		"minutes":42,
		"seconds":27
	}
}
```

**To Reproduce**
Create .ics file and let node fetch it

**Expected behavior**
I would expect the node to convert all timestamps to local time. Local timezone is set to Europe/Berlin (currently UTC+02).

**node-red-contrib-ical-events
 - Version 0.15.1
 - node-red version v1.0.5
 - nodejs version v8.11.4

**Comment by naimo84** [comment]
Hi @mvondemhagen,

the problem here is that the TZID is "Pacific Standard Time". I tried your file with "US/Pacific" and it works correctly. With standard javascript functionality.

![image](https://user-images.githubusercontent.com/11535502/85285175-b567f200-b490-11ea-8f41-83a36f4ad457.png)

```
BEGIN:VEVENT
UID:***SECRETDATA***
SUMMARY:Discussion
DTSTART;TZID=US/Pacific:20200622T110000
DTEND;TZID=US/Pacific:20200622T113000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200615T222525Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:***SECRETDATA***
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
BEGIN:VEVENT
UID:***SECRETDATA2***
SUMMARY:Discussion
DTSTART;TZID=Pacific Standard Time:20200622T110000
DTEND;TZID=Pacific Standard Time:20200622T113000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200615T222525Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:***SECRETDATA2***
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

I guess, the events come from outlook.com?

Greets, 
Benjamin

**Comment by mvondemhagen** [comment]
Yep, this is coming out of outlook.office365.com - any idea how to fix this (on any layer of the setup)?

**Comment by naimo84** [comment]
Hmm, currently I have no idea who to fix this... I could write some mapping code 
Pacific Standard Time --> US/Pacific

But: There are many other timezones and I didn't find a mapping table for this. 

My question is: Do you really need the PST timezone? 😉

**Comment by naimo84** [comment]
https://github.com/jens-maus/node-ical/issues/6

Someone with the same issue in node-ical 😉
the library I'm using for parsing ical

**Comment by mvondemhagen** [comment]
PST, MST, GMT/BST and CET/CEST are filling up my calendar, so yes :-) I would map the important timezones myself (annoying, but possible), but AFAICS the original information is not passed to its output by your node... However, reading this is already "breaking" in an underlying lib, I can/will +1 the linked issue there as well.
