### ISSUE TITLE
All Cals in one configNode

### ISSUE THREAD

**Issue by mkcologne** [naimo84/node-red-contrib-ical-events#52]
First: Great Work: Thanks so much!
Works like charme with iCloud using the solution from the openhab-forum.

Ist there a way to check all cals within one config Node?
If i wanna see my next Event: Ich have to check the all and compare the date stamps.
Possible, but not that convenient. U know …

Cheers - Michael

**Comment by naimo84** [comment]
Hi Michael,

I'm very happy, that you like it 😉 

Currently it's not possible, but I can create a checkbox in the nodes and/or a msg.payload property "checkAll", which will do this for you.

So, how's that for a start?

Cheers, 
Benjamin

**Comment by mkcologne** [comment]
Sounds great and I would really appreciate that! 
In the meantime I will play around a bit and perhaps it end up in some sharable flows.
Cheers - M.

**Comment by naimo84** [comment]
Hi Michael,

currently i have something like this:

![image](https://user-images.githubusercontent.com/11535502/86430300-370e1a00-bcf2-11ea-9286-e9e98d84593b.png)
![image](https://user-images.githubusercontent.com/11535502/86430353-55741580-bcf2-11ea-93ee-fa8c6415b648.png)

Is this ok for you? Or do you wan't all events in one output message?

Greets,
Benjamin

**Comment by mkcologne** [comment]
One config with different outputs for every calendar? Sounds great.
I can join it in an array by myself.
Is there a way to output the calNames as well?
Cheers - Michael
