### ISSUE TITLE
node doesn't pass on msg properties from incoming message

### ISSUE THREAD

**Issue by ukmoose** [naimo84/node-red-contrib-ical-events#53]
**Describe the bug**
In an incoming message, the message properties are not passed through by the ical nodes.

**To Reproduce**
1. set msg.topic on incoming message
2. link  ical Upcoming node to iCloud secure server
3. configure debug to display msg.topic 
4. when flow is run, (and calendar output is sent onwards by the iCal node) debug output is undefined

**Expected behavior**
Expect that message properties are passed through the ical nodes.   (eg msg.req required for http in - out flows)
and msg.topic in above example

**Screenshots**
n/a

**node-red-contrib-ical-events
 - Version 0.15.3
 - node-red v1.0.3
 - nodejs v10.21.0

**Comment by naimo84** [comment]
v0.16.0 is on the way 😉
