### ISSUE TITLE
Question: Where to set up Date/time of "check every"

### ISSUE THREAD

**Issue by Senbei123** [naimo84/node-red-contrib-ical-events#55]
Hi,

it's perfect to set up the next check on a time base.

It currently looks like this on a daily base:
![grafik](https://user-images.githubusercontent.com/52634196/87035463-a9e32d80-c1e9-11ea-8b53-73456770ec6b.png)

But how can I define, that it doesn't check on 22:00 but at 00:30?
Because I would like to do an update at the new day after do some adjustments with other batches in the time between 0:00 and 0:30.

I didn't find any set up for this.

(I also looking for the same anweser for the node ical-sensor.)

BR,
Senbei

**Comment by naimo84** [comment]
Hi Senbei,

sorry for the very late response... too much work, too lees slacktime for github...

I'm doing this with https://cookbook.nodered.org/basic/trigger-at-time, but a config for your request is in my pipeline.

BR,
Benjamin
