### ISSUE TITLE
Since last update non of the nodes working anymore

### ISSUE THREAD

**Issue by Mannshoch** [naimo84/node-red-contrib-ical-events#57]
**Describe the bug**
nodes not working anymore

**To Reproduce**
1. Update to current version

**Expected behavior**
Working nodes

**Screenshots**

**node-red-contrib-ical-events: 0.16.0**
[info] Node-RED Version: v1.0.3
[info] Node.js  Version: v12.18.2
[info] Linux 4.19.118-v7+ arm LE
[info] Paletten-Nodes werden geladen
[info] Dashboard version 2.23.0 started at /ui
[info] Einstellungsdatei: /home/smart/.node-red/settings.js
[info] Kontextspeicher: 'default' [ module=memory]
[info] Benutzerverzeichnis: /home/smart/.node-red
[warn] Projekte inaktiviert: editorTheme.projects.enabled=false
[info] Flow-Datei: /home/smart/.node-red/flows_SmartHome.json

**Additional context**
journalctl:
Jul 17 08:57:00 SmartHome Node-RED[282]: (node:282) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block
Jul 17 08:57:00 SmartHome Node-RED[282]:     at /home/pi/.node-red/node_modules/node-ical/index.js:75:13
Jul 17 08:57:00 SmartHome Node-RED[282]:     at /home/pi/.node-red/node_modules/node-red-contrib-ical-events/dist/helper.js:249:33
Jul 17 08:57:00 SmartHome Node-RED[282]:     at /home/pi/.node-red/node_modules/node-red-contrib-ical-events/dist/helper.js:16:29
Jul 17 08:57:00 SmartHome Node-RED[282]:     at /home/pi/.node-red/node_modules/node-red-contrib-ical-events/dist/ical-sensor.js:172:34
Jul 17 08:57:00 SmartHome Node-RED[282]:     at Function.assign (<anonymous>)
Jul 17 08:57:00 SmartHome Node-RED[282]: (node:282) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object

**Comment by naimo84** [comment]
I'm so sorry for the circumstances...

Should be fixed with v0.17. It's already on the way
