### ISSUE TITLE
Calendar Event fails to start after deploy

### ISSUE THREAD

**Issue by jseg** [naimo84/node-red-contrib-ical-events#6]
Hello,

Thanks so much for making this Node!  Sometimes after deploying I see this message in the debug window coming from the Event node:

"Error stopping node: TypeError: _this.context(...).get(...).forEach is not a function"

It doesn't happen every time, but seems to happen if I deploy frequently.

Warm regards,

John

**Comment by naimo84** [comment]
Hey John,

I'll have a look at it an will report back.

Regards,
Benjamin

**Comment by jseg** [comment]
Thanks Benjamin,

If it is helpful, here is a dump of the context data right after seeing the error message:

{"12inp32rnmhv02cf6o5g7v14vv@google.com":{"context":"[Circular ~.12inp32rnmhv02cf6o5g7v14vv@google.com]","_callbacks":[null],"cronTime":["","","","","",""],"runOnce":true,"running":false},"3fcguv4o8tlqpj3ug3tg4mjc2o@google.com":{"context":"[Circular ~.3fcguv4o8tlqpj3ug3tg4mjc2o@google.com]","_callbacks":[null],"cronTime":["","","","","",""],"runOnce":true,"running":true,"_timeout":{"_idleTimeout":10739989,"_idlePrev":{"_idleNext":"[Circular ~.3fcguv4o8tlqpj3ug3tg4mjc2o@google.com._timeout]","_idlePrev":"[Circular ~.3fcguv4o8tlqpj3ug3tg4mjc2o@google.com._timeout]","expiry":16163595,"id":-9007199254733387,"msecs":10739989,"priorityQueuePosition":5},"_idleNext":{"_idleNext":"[Circular ~.3fcguv4o8tlqpj3ug3tg4mjc2o@google.com._timeout]","_idlePrev":"[Circular ~.3fcguv4o8tlqpj3ug3tg4mjc2o@google.com._timeout]","expiry":16163595,"id":-9007199254733387,"msecs":10739989,"priorityQueuePosition":5},"_idleStart":5423606,"_repeat":null,"_destroyed":false}}}

**Comment by naimo84** [comment]
Thanks for the information :)
What Node-Red version do you use? Also what nodejs? 

I've tried to rewrite the "on close"-code. So may you try v0.4.4 an see, what happens?
Thanks a lot.

**Comment by jseg** [comment]
Hi Benjamin,

Thanks for the update. I was using nodejs version 12.12 and node-red version .195. Using your ical version 0.4.4 I was able to recreate the problem with that configuration. I upgraded to the current node-red version (didn't realize I was behind!) and now I cannot reproduce the problem. 

Thanks a lot,

John
