### ISSUE TITLE
Trigger and CalDAV causing extremely high load

### ISSUE THREAD

**Issue by Skyr** [naimo84/node-red-contrib-ical-events#60]
**Describe the bug**

I've configured a large calendar in the Trigger node. Querying the server causes on both sides extremely high load - within 12 hours, it managed to hammer my Nextcloud instance to death; node-red becomes very unresponsive too, I see both CPU and memory consumption spiking.

**To Reproduce**
1. Add a large calendar (have tested caldav only, not sure if this occurs with ical as well)
2. To provoke effect: Set refresh interval rather low, i.e. 1 or 5 minutes

**Expected behavior**
No load impact on both sides

**node-red-contrib-ical-events**
 - 0.17.1
 - node-red 1.1.2
 - nodejs 10.22.0

**Comment by naimo84** [comment]
Hi Skyr, 

sorry for the late response. Still very busy working days currently...

I have no idea, what's this causing, but I'll have a look at it.

Regards,
Benjamin

**Comment by Skyr** [comment]
The server side seems to have been my fault - I had a huuuuge pile of entries in the table of the bruteforce module (https://github.com/nextcloud/bruteforcesettings/issues/213). The problem on the node-red side persits, my trusty RPi becomes almost completely unresponsive when I activate the trigger. As soon as time permits, I'll test this on a RPi4 to see if the amount of RAM is the bottleneck.

**Comment by Programie** [comment]
I've a similar issue: In my case, the node requests an .ics file from Nextcloud for each event in the calendar.

If you have lots of events in your calendars, this behavior causes a huge amount of requests being made by the node and therefore also increases the system load.

In my case, my Nextcloud instance gets a few thousand requests per refresh interval.

AFAIK, it is not required to request the Ical file for each event as the calendar request should always contain all the information.

If that's not possible, then the node should only request those events falling in the selected day range (between "Past view" and "Preview").

I'm using the latest beta version (1.0.0-beta.2) as the latest stable version does not return any events at all.

**Comment by naimo84** [comment]
Hey, 

v1.0.0-beta.4 is ready for testing ;) https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.4/node-red-contrib-ical-events-1.0.0-beta.4.tgz

would you like to take a look at it?

Greetings,
Benjamin

**Comment by naimo84** [comment]
If you like to test the newest beta version of my node, you can download a .tgz file from here https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.5/node-red-contrib-ical-events-1.0.0-beta.5.tgz

**Comment by Programie** [comment]
For some reason, the node went back to around 50 requests per interval with the same version. Maybe the issue only happens after a while and got fixed with a restart.

Anyway, I've updated to the latest beta version (1.0.0-beta.5) which now shows the same number of requests. So as of now, it seems to work. At least I couldn't find any spikes in my access logs.

**Comment by naimo84** [comment]
Hey, 

I'll close this for now. If it appears again, feel free to reopen it.

Greets,
Benjamin
