### ISSUE TITLE
caldav - get calendar went wrong. Error Message: Error: Response with status code: 400

### ISSUE THREAD

**Issue by Aerics84** [naimo84/node-red-contrib-ical-events#61]
**Describe the bug**
I try to connect to my calendar, but it always fail with the error message: "caldav - get calendar went wrong. Error Message: Error: Response with status code: 400"

The url is: https://hosted.mailcow.de/SOGo/dav/xxx@xxx.de/Calendar/personal/

I`m using the type CalDav and put my username and password in.

I try different kind of urls like https://hosted.mailcow.de/SOGo/dav/ or https://hosted.mailcow.de/SOGo/dav/xxx@xxx.de/Calendar/ with the same result.

Can i debug your node so i can see how you build the url and maybe its messing up? Or get some more information whats going wrong?

**Comment by naimo84** [comment]
Hi Aerics84,

I've tried it ith my own mailcow server and found a small issue with the content-type... So it was no problem with your URL. 

Will be fixed with the next version, hopefully

**Comment by Aerics84** [comment]
Thanks man.Hope it will take but to long till it will be release.
Von: Benjamin <notifications@github.com>
Gesendet: Montag, 3. August 2020, 13:45
An: naimo84/node-red-contrib-ical-events
Cc: Aerics84; Author
Betreff: Re: [naimo84/node-red-contrib-ical-events] caldav - get calendar went wrong. Error Message: Error: Response with status code: 400 (#61)






Hi Aerics84,


I've tried it ith my own mailcow server and found a small issue with the content-type... So it was no problem with your URL.


Will be fixed with the next version, hopefully
