### ISSUE TITLE
events not detected

### ISSUE THREAD

**Issue by geertvercamer** [naimo84/node-red-contrib-ical-events#62]
events are not detected.
I have a recurring event at 17:30, inserted in google agenda a few weeks ago. It is signalled as the next trigger.
This morning I added 2 events and none of them was detected.
Some agendas signal the next event in a really far future: Apr 15 2029 and even Sep 09 2999

**To Reproduce**
I just have several inputs in google calendar.

**Expected behavior**
Announce all of the events

**Screenshots**
![Knipsel](https://user-images.githubusercontent.com/11328101/89505997-b51a8080-d7ca-11ea-8954-8d124102beaa.JPG)

All latest versions

**Comment by naimo84** [comment]
Hi @geertvercamer ,

I saw, that I didn't extend the trigger node with regex.... In my "production" env I only have one trigger per day per calendar...
May you please try v0.17.3?

If this doesn't help: May you send some more details to my mail address? Perhaps some ICS or so? It's hard to say, what's the problem :/ Sorry

**Comment by geertvercamer** [comment]
Sorry for the delay.
I've learned since that the label below the trigger shows the end of the event, rather than the start. (confusing, no?)
I found the 2999 entries in the calendar and deleted them, but now the next trigger is 22/04/2022. I do have other events in my calendar in between, of course.
