### ISSUE TITLE
Allow to setup filterdestination

### ISSUE THREAD

**Issue by Mannshoch** [naimo84/node-red-contrib-ical-events#63]
**Is your feature request related to a problem? Please describe.**
I wish to filter by other content than summary.

**Describe the solution you'd like**
- [ ] Replace the text "Filter" in the node with a Combo box that allow to set up what calendar field should get checked with regex
Example:
- Summary
- Description
- Category
- Attendee
- Start Date (`YYYY-MM-DD_h:m:s`)
- End Date (`YYYY-MM-DD_h:m:s`)

**Describe alternatives you've considered**
I do need a  short and clear summary but I wish to add command somewhere to trigger the correct node

**Additional context**
- [ ] As an enhanced solution, may set up the combobox as multi select combobox.

**Comment by naimo84** [comment]
Hi Mannshoch,

thanks for the feature request. I'll have a look at it. 
Unfortunately I have very less time for coding nodered, so please be patient.

Regards,
Benjamin

**Comment by naimo84** [comment]
A first try with description, summary and attendees should be in v0.19.

I'm not sure, who to filter start and enddate? May be with operators like "between", "before", "after"?
What is your understanding of "category"?

**Comment by Mannshoch** [comment]
For Category I think about the ICAL field Category. (I use them much in my calendar.) I use e.g. a category SmartHome 
https://tools.ietf.org/html/rfc5545#section-3.8.1.2

In the case of Date I agree with your operators.

**Comment by naimo84** [comment]
Finally I finished the requirements, as you posted. Sry, that I took other a year...... Hopefully you're still using my nodes ;) 
The whole Covid leads to even more "real work" at my business job...

Greets,
Benjamin
