### ISSUE TITLE
Information in case of failed request

### ISSUE THREAD

**Issue by patrickknabe** [naimo84/node-red-contrib-ical-events#65]
**Is your feature request related to a problem? Please describe.**
Hi,

I haven't seen any possibility to get informed when a ics-request fails. I have an application where I want to switch on some lights, if it is not possible to update the ics-file.

**Describe the solution you'd like**
Maybe the outgoing message can be extended by the status of the last ics-check? Or do I already receive this information?

Thank you very much!

**Comment by naimo84** [comment]
Sorry for the delay. I'll have a look at it. But please be patient, I have currently less free time to code node-red nodes :(

**Comment by naimo84** [comment]
Sorry one more time for the big delay. 

With v0.19 there should be a msg.error with the containing error message ;)

**Comment by patrickknabe** [comment]
Perfect, thank you! I will try the change quickly!
