### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by noumenon272** [naimo84/node-red-contrib-ical-events#66]
I am unable to get any output from these nodes. I created test events and subscribed to a publicly shared calendar that I created - I copied the URL from Apple Calendar. I've tried all three nodes looking for both current, all day, and upcoming events, but I get no debug output at all.

I shared the same calendar from apple to google, and I am able to get a single debug message output from there, but it isn't useful:

```
9/7/2020, 12:54:17 PMnode: 3
msg : Object
object
_msgid: "1a08a8d9.3edee7"
payload: object
on: false
topic: ""
```

I don't know if I missed something in the setup or if I'm missing a dependency or what.  I'm running the official node-red docker container. 

thanks

**node-red-contrib-ical-events
 - Version 0.17.5
 - node-red version: v1.1.3
 - nodejs version: 10.22.0
--

**Comment by naimo84** [comment]
Sorry for the delay. I'll have a look at it. But please be patient, I have currently less free time to code node-red nodes :(

**Comment by naimo84** [comment]
Did you get any futher error messages? Did you configure the iCloud Secure like it's described in the help section of the config? 
https://community.openhab.org/t/solved-apple-icloud-caldav-connection/32510/6

**Comment by noumenon272** [comment]
yes, I did go through all that, although I can’t even get the unencrypted calendars to work.  I’m not getting any debug messages, the following error message pops up in the node red logs, which seems to be pertinent. 


```
    at strictFail (/data/node_modules/sax/lib/sax.js:677:7),
Error parsing response { Error: Text data outside of root node.,
Column: 47,
Line: 0,
Char: .,
    at error (/data/node_modules/sax/lib/sax.js:651:10),
    at SAXParser.write (/data/node_modules/sax/lib/sax.js:1035:15),
    at module.exports (/data/node_modules/xml-js/lib/xml2js.js:346:12),
    at Object.module.exports [as xml2json] (/data/node_modules/xml-js/lib/xml2json.js:13:8),
    at ClientRequest.<anonymous> (/data/node_modules/node-red-contrib-ical-events/dist/icloud.js:54:49),
    at ClientRequest.emit (events.js:198:13),
    at TLSSocket.socketCloseListener (_http_client.js:358:9),
    at _handle.close (net.js:607:12),
    at TLSSocket.emit (events.js:203:15),
    at TCP.done (_tls_wrap.js:400:7) note: [Circular] }
```

**Comment by geertvercamer** [comment]
I don't get any notifications nor errors.
Nothing to see about ical events in syslog

The node status shows the correct timestamp of the next trigger, but it looks like it doesn't trigger or doesn't write anything in payload

**Comment by noumenon272** [comment]
the recent update has fixed things for me so that unencrypted public calendars are working. thanks!
