### ISSUE TITLE
"Error: WARNING: Date in past. Will never be fired."

### ISSUE THREAD

**Issue by phreaq** [naimo84/node-red-contrib-ical-events#69]
I am getting the "Error: WARNING: Date in past. Will never be fired." error when using a negative offset when using the 'event trigger'

![image](https://user-images.githubusercontent.com/5051698/96148884-53634a80-0ece-11eb-8944-053e7ad74582.png)

I am trying to get a message 15 minutes before an event, which works, however, the error message pops up after the next check.

I did see this [issue](https://github.com/naimo84/node-red-contrib-ical-events/issues/50), but it said it was resolved in 0.15.2 . I am using 0.17.5

**Comment by phreaq** [comment]
![image](https://user-images.githubusercontent.com/5051698/96157506-fe2c3680-0ed7-11eb-8dea-bbf8b3c6d5c5.png)

 nice!

**Comment by naimo84** [comment]
Hey, I'll have a look at it. What the meaning of the second screen?

**Comment by phreaq** [comment]
> Hey, I'll have a look at it. What the meaning of the second screen?

the issue number :)

**Comment by koburg** [comment]
<img width="324" alt="Skærmbillede 2020-10-27 kl  16 47 09" src="https://user-images.githubusercontent.com/3473374/97326322-2e7aba00-1874-11eb-857e-4b15da2ff529.png">
<img width="247" alt="Skærmbillede 2020-10-27 kl  16 47 32" src="https://user-images.githubusercontent.com/3473374/97326369-39cde580-1874-11eb-8edf-801f54800b7a.png">

I also got an issue with the time I have copied link from ical / iCloud but the time is 1 Hour behind. as you see on the second picture my function call of local time in the node is showing the correct time.

**Comment by naimo84** [comment]
Hey @phreaq @koburg, 

the Error/Warning should be gone with the next release. I was adding a cronjob with a date really in the past.

@koburg: this is just a display issue. the time for "next check" is in the utc timezone. So just add one hour and you're in your timezone ;) https://time.is/UTC

Grretings, Benjamin

**Comment by phreaq** [comment]
@naimo84 will you be updating the npm site with the new build? node-red isn't picking up the changes yet
