### ISSUE TITLE
Event End node

### ISSUE THREAD

**Issue by jseg** [naimo84/node-red-contrib-ical-events#7]
Hi Benjamin,

I'd like to suggest adding a node that is functionally the same as the Event node but fires at the end time of the calendar event. This would make for very simple implementation of On/Off or startup/shutdown use cases and could help handle cases where a user edits a calendar during an event interval without needing to parse the upcoming events node. 

I'm not a javascript or node-red expert, but if you like I could make a pull request with this implemented for you to review.

Warm regards,

John

**Comment by naimo84** [comment]
Hi John,

I would be glad, if you could contribute my nodes 😊

Currently finding time for coding is problem. My newborn is 3 weeks old 👶

Perhaps you could think about extending the existing event node with a second output? 
So the first one is for start events, the second is for end events? 

Many many thanks in advance 

Greetings from Bavaria, 
Benjamin

**Comment by jseg** [comment]
Hi Benjamin,

Congratulations on your new child! 

I made a pull request that I think handles the remaining edge cases for the extended Events node. Those changes prevent data from accumulating in context and stop cron jobs that are deleted from the calendar. If you are happy with those changes, I think this issue can be closed. I had fun learning some new things over the last couple of days, thanks!

Warm regards,

John

**Comment by naimo84** [comment]
Hi John,

Thanks you so much 😄 

Yes, I'm very happy about your changes 👍 Well done! 
Coding node-red/javascript is indeed funny. So perhaps you develop your own node-red nodes soon ;) I will contribute you.

Warm regards,
Benjamin
