### ISSUE TITLE
module stopped working after iCloud password change

### ISSUE THREAD

**Issue by ahartman** [naimo84/node-red-contrib-ical-events#70]
Hello,

You and I cooperated last year on improving your module, resulting in the iCloud secure connection method.
This was worked brilliantly for me since then.
2 days ago, I have to change my iCloud password and I no longer receive events, even when using the new password.

The logging is not very helpful:
Nov 06 06:53:38 raspberrypi Node-RED[3230]: 6 Nov 06:53:38 - [debug] [ical-upcoming:consultaties] Ical read successfully https://p31-caldav.icloud.com:443/223639751/calendars/351E54A9-85EC-4AD6-A100-0B1435502C5F/

I get the same logging even using a fancy, wrong password.
Is there any way to get more details on what goes wrong?

SOLVED!
I suddenly remembered that I should use the app-specific password and not the normal iCloud password for my AppleID. It si working again.
You might want to add a comment on the app-specific password in your help text.
And maybe the logging can be more extensive to help finding issues.

Regards, ahartman, belgium

**Comment by naimo84** [comment]
Hey ahartman,

great to hear, that you're using my nodes 'till today 👍 
Sorry for missing comment. I've added it to the config and the help text. 

Thanks for the hint with the extended logging. I saw, that there is no logging from the icloud response.... 
But I'll have to add this later. 

Regards from Bavaria, Benjamin
