### ISSUE TITLE
simultaneously events produce several objects with identical IDs

### ISSUE THREAD

**Issue by micdis** [naimo84/node-red-contrib-ical-events#71]
Hey!

thanks for that great node, but I stumbled upon a problem:

with multiple events at the same time in a calendar the sensor-node produces multiple objects all at the same time with the same msg_id. I'm not sure how to differentiate these?

Thanks for your help,
Michael

edit: routing to a switch node does not filter for both objects

**Comment by micdis** [comment]
thanks for the fast commit.

I exchanged the ical-sensor.js, but now I don't get any msg at all!?

**Comment by naimo84** [comment]
Hi Michael,

may you please try v0.18.0? I just uploaded it. For me, locally, it's working as expected. 
Maybe because I outsourced some Code to the helper.js/ts also ;)

Greets,
Benjamin

**Comment by micdis** [comment]
Hey Benjamin,
thanks for the super fast response. Now the switch node can properly discriminate between the different events. Works like a charm....
Tanks a lot for your great work!

Viele Grüße aus Berlin,
Michael
