### ISSUE TITLE
“Fetch all configs concurrent” doesn’t behave as expected.

### ISSUE THREAD

**Issue by evitiello** [naimo84/node-red-contrib-ical-events#72]
**Describe the bug**
I think what this is supposed to do is fetch each of the ical configs and return a message for each.  It sort of does this, so I'm not sure if it is broken or just doesn't do what I expect it to.

In my case, I have 5 configs (one for each iCal calendar, many of which don't have any soon upcoming items), with the "Fetch all configs concurrent" box checked.

It appears to fetch 5 things, as 5 messages are returned. The first two has an empty payload and a 0 count for the today/tomorrow/total values.

The last three however all have the same entry in the payload.  It says it is from one calendar, but the entry is actually from a different one.

**To Reproduce**
1. Enable the "Fetch all configs concurrent" box
2. Setup 5 calendars, 4 of which should have nothing upcoming, and one of them should have a single entry.
3. Trigger the flow.

**Expected behavior**
5 messages output, 4 of which with no msg.payload, and one that has one entry in msg.payload.

**node-red-contrib-ical-events
 - Version 0.19.0
 - node-red 1.2.2
 - nodejs version 14.3.0

**Comment by naimo84** [comment]
Hi @evitiello ,

I will soon publish a new version, which should handle this correctly. Now there will be only one output with all events. I think this is a better way to handle it?!

regards,
Benjamin

**Comment by evitiello** [comment]
Hi - yes, I think that would work better.

**Comment by dhelland** [comment]
It seems there is one output now and it's all associated with the selected calendar. Would it be possible to include the calendarName field with each event? We need to be able to identify which calendar sent the event.

**Comment by evitiello** [comment]
FYI, just updated to the latest release and this is working great now - thank you!
