### ISSUE TITLE
Can you include the CATEGORIES property name?

### ISSUE THREAD

**Issue by smadds** [naimo84/node-red-contrib-ical-events#73]
We are using an external combiner (teamup.com) to create a single iCal feed from multiple calendars. This puts each calendar name in the CATEGORIES property. 

Would you be able to add this property to the output of your Future Events node?

**Comment by naimo84** [comment]
Hey Simon, 

v0.20.0 is on the way ;) may you please have a look? 

kind regards,
Benjamin

**Comment by smadds** [comment]
Thanks for this, Benjamin - it works well.

If possible, could Categories be added to the filter list in the future?
