### ISSUE TITLE
"TypeError: Cannot read property '1' of null"

### ISSUE THREAD

**Issue by guenter-ms** [naimo84/node-red-contrib-ical-events#74]
Hello,

I try to connect to icloud calendar and get always the TypeError message. Found no more infos in the log.

I have configured icloud secure with url: webcal://p26-caldav.icloud.com/published/2/xxxxxxxx (key changed to xxxxx)

When url is launched in Safari Browser, i will get a question to allow open the calendar.app, so it seems that a valid .ics file will come back from that url.

The Error is permanent.

**node-red-contrib-ical-events
 - Version [e.g. 0.20-0]
 - node-red version 1.2.6
 - nodejs version (? where can I find that ?)

Any idea what is my mistake?

Thx Guenni

![Bildschirmfoto 2020-12-16 um 18 26 31](https://user-images.githubusercontent.com/6253315/102383864-519c2d00-3fcc-11eb-85d9-3a620977d51e.jpg)
![Bildschirmfoto 2020-12-16 um 18 28 30](https://user-images.githubusercontent.com/6253315/102384031-89a37000-3fcc-11eb-92dd-bdd695d32116.jpg)
![Bildschirmfoto 2020-12-16 um 18 29 06](https://user-images.githubusercontent.com/6253315/102384106-9f189a00-3fcc-11eb-9d13-01e7969714cd.jpg)

**Comment by guenter-ms** [comment]
SOLVED!

I did not follow the icloud rules to build the URL. I tried to make it via Type = CalDav und found the URL in the mac calendar app. The URL starts with webcal://.... which is obviously not supported.

Now I took the described way and it works. But its a stony way to get the URL....

Take care
guenni

**Comment by naimo84** [comment]
Hi @guenter-ms ,

i know that it's a stony way. I've tried to implement it in an easier way. But the solution also not very handy.

But I will soon publish a new version, which also allows to use webcal url. In fact, webcal is nothing else than http ;) just replace it

Regards and happy new year,
Benjamin

**Comment by guenter-ms** [comment]
Thank you, will wait for the new version.
Happy new year!
Guenter
