### ISSUE TITLE
webcal URL leads to Error:ENOENT

### ISSUE THREAD

**Issue by fpetry** [naimo84/node-red-contrib-ical-events#75]
**Describe the bug**
I tried to query a generated URL of the local waste disposal service:
webcal://st-ingbert.mein-abfallkalender.de/ical.ics?sid=8553&cd=inline&ft=6&fp=next_1000&wids=157,155,156,154&uid=161276&pwid=79a9821ee8&cid=25

The console shows:

~~~
Error: Error: ENOENT: no such file or directory, open 'webcal://st-ingbert.mein-abfallkalender.de/ical.ics?sid=8553&cd=inline&ft=6&fp=next_1000&wids=157,155,156,154&uid=161276&pwid=79a9821ee8&cid=25'
~~~

**To Reproduce**
1. Create an upcoming node with the URL 'webcal://st-ingbert.mein-abfallkalender.de/ical.ics?sid=8553&cd=inline&ft=6&fp=next_1000&wids=157,155,156,154&uid=161276&pwid=79a9821ee8&cid=25'
2. Trigger a query (inject node)
3. Error described above visible in debug output

**Expected behavior**
The URL should return valid iCAL and the events should be usable in the nodes.
An online iCAL validator (https://icalendar.org/validator.html) has nothing to complain.
I can also use the URL in a Thunderbird calendar.

**node-red-contrib-ical-events
 - Version 0.20.0
 - node-red version 1.0.6
 - nodejs version

**Additional context**
A public share iCAL URL of nextcloud also did result in the ENOENT error.

**Comment by naimo84** [comment]
Hi @fpetry ,

I will soon publish a new version, which also allows to use webcal url. In fact, webcal is nothing else than http ;) just replace it

Regards and happy new year,
Benjamin

**Comment by fpetry** [comment]
I could have come up with that idea... :-)

Thank you. Replacing "webcal" with "http" works fine.
