### ISSUE TITLE
"Error: WARNING: Date in past. Will never be fired."

### ISSUE THREAD

**Issue by CubeComming** [naimo84/node-red-contrib-ical-events#76]
I get an ERROR message, which says "Error: WARNING: Date in past. Will never be fired." from the trigger node. 

My TZ is 1 hour bevor UTZ, so if UTZ is 5pm o'clock its 6pm for me. I already tried setting the config offset to -65 Minutes or +65 Minutes but nothing worked for me (5 because i want to be notified 5 Minutes bevor the event). My calendar is also set to my TZ. 
I can also not change the offset from minutes to anything else like hours or seconds.

I would appreciate any help 
Thank you

**Comment by naimo84** [comment]
Hi @CubeComming ,

may I ask which version of my node do you use?  I thought, I fixed this issue with #69 ;)

Greets,
Benjamin

**Comment by CubeComming** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/76119729/104496897-e00acb00-55d9-11eb-8fd8-35fe7f0d2346.png)

Do you mean this?

**Comment by naimo84** [comment]
Yes, thanks for sharing. It the latest version... So I will look why this is still happening.

**Comment by CubeComming** [comment]
Thank you very much. Could you please also post an example config for this node so that I can take a look if I somehow messed up the setup.

Thank you

**Comment by CubeComming** [comment]
Thank you very much.

Sadly i cannot install from github (cause i run node red on a HassIo image) and I depend on the install via "palette". Would it be possible for you to update that version?

https://flows.nodered.org/node/node-red-contrib-ical-events

Thank you

**Comment by CubeComming** [comment]
Thank you very much.

Sadly i cannot install from github (cause i run node red on a HassIo image) and I depend on the install via "palette". Would it be possible for you to update that version?

https://flows.nodered.org/node/node-red-contrib-ical-events

Thank you

**Comment by CubeComming** [comment]
It seems to work now, thank you very much for your help.
