### ISSUE TITLE
Get list of tasks (VTODO)

### ISSUE THREAD

**Issue by Programie** [naimo84/node-red-contrib-ical-events#77]
**Is your feature request related to a problem? Please describe.**
CalDAV and the ical format also supports tasks (VTODO entries). I want to get a list of (open) tasks from my calendars.

**Describe the solution you'd like**
Implement a new node to retrieve the list of tasks.

**Describe alternatives you've considered**
Nothing, as nothing exists yet which could provide a list of tasks in my calendars.

**Comment by naimo84** [comment]
Sorry @Programie,

for some reason I've overlooked this issue........ 
I'll try to implement Todos as soon as possible ;)

Greets,
Benjamin

**Comment by naimo84** [comment]
Hi,

I've released v1.1.0. May you have a look at it? 
If you like the node, leave it a star ⭐ Thanks.

Greetings,
Benjamin

**Comment by Programie** [comment]
I just tested it. It works for me. :-)

But in my case, I would expect a single node (i.e. ical-upcoming) to have to ability to return events, tasks or both.

I.e. I want to get a list of events from all of my calendars to trigger something event based. In another flow, I want to get a list of (open) tasks from a single calendar.

I'm not sure whether it makes sense to change it to this behavior. Maybe I'm just wrong.

**Comment by naimo84** [comment]
Hey @Programie, @RobertKitzing ,

may you wanna try a beta version as well? https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v2.1.0-beta.3/node-red-contrib-ical-events-2.1.0-beta.3.tgz

I've changed a lot of things in the frontend of the nodes, so I'm afraid something is broken and don't wanna push it to flows.nodered.org before anyone else than myself has tested it ;)

Greets,
Benjamin

**Comment by Programie** [comment]
I've just tested the beta version.

There is one bug I just noticed:

I've created a new "Test" calendar in my Nextcloud instance and added one Todo and one event in the future (in two days).

Then, I've configured my Nextcloud instance as a new CalDAV config, checked the option "Include Todos" and specified my "Test" calendar as calendar name.

After that, I've added an "upcoming" node using the newly created config and selected "Events" as event type (instead of Events + Todos).

Once I inject something into the node, both entries are returned even if only "Events" is selected as event type. The same also happens if I select only "Todos" as event type.


btw: Shouldn't the "Include Todos" option be obsolete with the new version allowing to select the event types in the node properties?

**Comment by naimo84** [comment]
Yes, I have no idea, why I didn't double check this behaviour...

Hopefully I fixed it with beta.4 :) https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v2.1.0-beta.4/node-red-contrib-ical-events-2.1.0-beta.4.tgz

**Comment by Programie** [comment]
Tested it again with beta.4 and now it works as expected. Thanks for the quick fix! :+1:

Another small feature request which could be useful: Allow to specify multiple calendars in the node configuration. I'm not sure whether that's "off-topic" for this issue, if so, I would open another one.

**Comment by naimo84** [comment]
Thanks for testing the beta 👍 

I would close this issue for now. And you could open a new one, please 😁 I will have a look at it as soon as possible ;)

**Comment by Programie** [comment]
OK, I've opened another issue for the "off-topic" request: #119
