### ISSUE TITLE
ical-upcoming does not return active event

### ISSUE THREAD

**Issue by ChankyTheConqueror** [naimo84/node-red-contrib-ical-events#78]
Hi,
I'd like to report a bug. 

If preview is set to < 4 days then ical-upcoming returns an empty array even though there is an upcoming event in 1 day. If set to >=4 days then it works as expected.
![image](https://user-images.githubusercontent.com/64441284/105643849-a451ea00-5e92-11eb-93c4-7c90cfae6c3b.png)

version -> 0.23.0
nodered -> v1.27
nodejs-> v12.20.0

**setup:**
timestamp->ical-upcoming->debug_node
filter: ^[A-Z]*\d*[^2]$

for the timestamp value injected was : 1611517842729

**output with preview set to 2days** -> 
[]empty
**output with preview set to 4day**->
[{"date":"25.01.2021 00:00-00:00","summary":"P1","topic":"P1","calendarName":"","event":"P1","eventStart":"2021-01-24T23:00:00.000Z","eventEnd":"2021-01-25T23:00:00.000Z","description":"Altpapier","id":"73g801utcn1sijdnqed3gfb4gc@google.com","allDay":true,"rule":" rrule ","location":"","countdown":{"days":0,"hours":1,"minutes":42,"seconds":20}}]

**Comment by naimo84** [comment]
Hey @ChankyTheConqueror ,

sorry for the circumstanes. This is a relay strange behaviour. If you like, you can send me some more details via email? The google ical url would be nice. It's a lot easier to find the bug with the real example ;)

Thanks and greets,
Benjamin

**Comment by ChankyTheConqueror** [comment]
Hi Benjamin, 
I've send you the calender via email, thanks and best regards

**Comment by naimo84** [comment]
Hey, 

v1.0.0-beta.4 is ready for testing ;) https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.4/node-red-contrib-ical-events-1.0.0-beta.4.tgz

would you like to take a look at it?

Greetings,
Benjamin

**Comment by ChankyTheConqueror** [comment]
Hi Benjamin,
beta4 looks good, it fixes the issue, thanks for you time and effort

Best regards

**Comment by naimo84** [comment]
Hi Chanky,

nice to hear it's working for you now :)
You're most welcome.

Best regards to Austria
Benjamin
