### ISSUE TITLE
Module luxon not found

### ISSUE THREAD

**Issue by Joniator** [naimo84/node-red-contrib-ical-events#79]
**Describe the bug**
I can't find any nodes of the Plugin. It is shown in the palette as installed, but only the ical-config is enabled.
I'm not able to enable the other nodes, if I do I get an expection "Cannot find module 'luxon'", full error below.

After installing luxon myself, I can enable and use the nodes.

**To Reproduce**
- Install package with npm

**Expected behavior**
It installs luxon and I can use the plugin without installing its dependencies

** Log output**
`Error: Cannot find module 'luxon'
Require stack:
- /opt/node_modules/rrule/dist/es5/rrule.js
- /opt/node_modules/node-ical/ical.js
- /opt/node_modules/node-ical/index.js
- /opt/node_modules/node-red-contrib-ical-events/dist/caldav.js
- /opt/node_modules/node-red-contrib-ical-events/dist/helper.js
- /opt/node_modules/node-red-contrib-ical-events/dist/ical-events.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js`

**node-red-contrib-ical-events
 - Version 0.23.0
 - node-red version 1.2.7
 - nodejs version 14.15.4

**Additional context**
I'm running the hassio addon, and install it via its config file.
In the end its just an alpine linux dockercontainer and installs the plugins at the beginning, which works fine for other plugins.

**Comment by naimo84** [comment]
Hey @Joniator, 

sorry for the circumstances. I will add luxon to the package.json. 

I don't know, why it's not installed automatically...

Greets,
Benjamin

**Comment by naimo84** [comment]
If you like to test the newest beta version of my node, you can download a .tgz file from here https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.5/node-red-contrib-ical-events-1.0.0-beta.5.tgz

**Comment by naimo84** [comment]
Hi,

I've released v1.1.0. May you have a look at it? 
If you like the node, leave it a star ⭐ Thanks.

And I'll close the issue for now, because I think it schould be solved. Feel free to reopen it.

Greetings,
Benjamin
