### ISSUE TITLE
Connect to iCloud calendar securely

### ISSUE THREAD

**Issue by ahartman** [naimo84/node-red-contrib-ical-events#8]
I know of 2 methods to retire an iCloud calendar:
1. Share the calendar publicly (read-only) and use the URL given, no user name or pasword needed.
2. Compose the 'real' internal URL with some CURL commands and that. User name is your Apple ID and password is an app-specific password you can generate in appleid.apple.com.

I have both approaches working in other software.
The 'homebridge-calendar' plugin uses method 1; 'homebridge-daily-sensors" uses method 2.

For the node-red modules method 1 works but method 2 gives an empty array. 

Problem with method 1 is that data are not secure, anybody finding or guessing the URL can look at the events.
Is it possible to use method 2 or another secure access method and any help on that is appreciated.

Regards, ahartman, belgium

**Comment by naimo84** [comment]
Hi ahartman,

I've tried to implement method 2, so you may have a look at v0.5.0?

There is a new type "iCloud" in the options, because neither the caldav nor ical implementation worked as expected.

Regards, 
Benjamin

**Comment by ahartman** [comment]
Dear Benjamin,
I tested your 0.5.0 and I have good news and bad news.
= The Upcoming node works fine with a new config iCloud config node.
= The Event node when using the same new iCloud config node, gives "SyntaxError: Unexpected token i in JSON at position 0".

regards, andré hartman, belgium

**Comment by naimo84** [comment]
Hi andré,

I'm sorry, jseg was developing the event end node. Parallely I tried to implement the icloud type.
So, it was my mistake, and I forgot the event node. v0.5.1 should do it correctly.

regards, benjamin

**Comment by ahartman** [comment]
Benjamin,
The new version v0.5.1 products the same error.
Regards, andré hartman

**Comment by naimo84** [comment]
sorry, my newborn is currently very time consuming 😃 

So, I forgot to transpile Typescript to Javascript Files before publishing the new version.

v0.5.2 should finally do it
