### ISSUE TITLE
Event trigger Ical

### ISSUE THREAD

**Issue by koburg** [naimo84/node-red-contrib-ical-events#80]
I don't get any events output from the trigger any more when using ical.
it is showing the next trigger as usual but no output when it should.

i have not changed any settings only updated the node.

**Comment by naimo84** [comment]
Hey @koburg, 

sorry for the circumstances. From which version did you upgrade.

With bd381cf35799cb083b2aae7d61b6adcce9b62e6d I fixed a little error/warning for issue #76. But this should not affect your problem...

If you like, you can send me an email with the ical? 

Greets, 
Benjamin

**Comment by koburg** [comment]
I think it was from previous version not sure. But I always check for upgrades in palette  about once a week. 

Sure I can send iCal link just the link from the setting ? Where do I find your email?

**Comment by naimo84** [comment]
Thanks for sharing your calender ;)
May you please also share you're config? I tried your ical and can't figure out any problem. 

Have you set the offset property? There was a problem with v0.22 when you set it to hours... it took minutes instead...

![image](https://user-images.githubusercontent.com/11535502/106995528-6355b180-677f-11eb-9d40-dc40b6c2f49d.png)

**Comment by naimo84** [comment]
I did a short test tomorrow in the morning, with your synon/synoff event. Unfortunatelly it's working on my side... see below

![2021-02-05 08_06_14-Node-RED - Brave](https://user-images.githubusercontent.com/11535502/107047098-b8b5b100-67c7-11eb-9022-403b8d738f51.png)
![2021-02-05 08_06_51-Node-RED - Brave](https://user-images.githubusercontent.com/11535502/107047103-b94e4780-67c7-11eb-839a-3ab626f1f5fd.png)
![2021-02-05 08_07_06-Node-RED - Brave](https://user-images.githubusercontent.com/11535502/107047102-b94e4780-67c7-11eb-8f32-a4cb9c8e3761.png)

**Comment by naimo84** [comment]
If you like to test a beta version of my node, you can download a .tgz file from here https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.1/node-red-contrib-ical-events-1.0.0-beta.1.tgz

and upload it in the palette manager

![2021-02-05 15_45_22-Werbung - benjamin@neumann cloud - Outlook](https://user-images.githubusercontent.com/11535502/107048425-3928e180-67c9-11eb-9854-8bd4d0745dc0.png)

**Comment by geertvercamer** [comment]
I tried this beta. I'm afraid I have to restart nodered service on the pi after every change to the flow.

**Comment by naimo84** [comment]
Hi @geertvercamer,

sorry for the circumstances. Do you have any log messages for me? I can't imagine, why the beta should force you to restart the node-red service.

Greets,
Benjamin

**Comment by naimo84** [comment]
Hi,

I've released v1.1.0. May you have a look at it? 
If you like the node, leave it a star ⭐ Thanks.

And I'll close the issue for now, because I think it schould be solved. Feel free to reopen it.

Greetings,
Benjamin
