### ISSUE TITLE
Option for array response of matching entries.

### ISSUE THREAD

**Issue by Deggle** [naimo84/node-red-contrib-ical-events#83]
**Feature Request**
A checkbox/radio to select the existing output (of one message per event) or as a single message with a payload as an array of all matched/active events. For my purposes, on the Sensor node, but may be applicable to others.

There are nodes that combine separate messages but I think it makes more sense for this to be built in.

I _think_ this would solve something I'm straggling with... I want to be able to trigger a sensor node and if there is a matching event have that returned, but if there is no matching event be able to know that is the case (so a message with an empty array, or an on:false entry). Currently I get multiple responses and if there is an event that doesn't match the filter I also get an on:false message for that which isn't helpful as the onward code would interpret this as the event I'm looking for not being present.

If all messages are in one array I can just follow with a node that looks for an occurrence of the one I'm looking for - if there are no occurrences the event isn't on.

Sorry if that doesn't make sense, I can probably explain better if you need.

**Comment by naimo84** [comment]
Hi @Deggle,

with the v1.0.0-beta versions, I already change the behaviour. Currently only one { on: false } message is generated, if there is no matching event. But also one or more { on: true }, if there is one or more match/es.

May you give the beta (https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.2/node-red-contrib-ical-events-1.0.0-beta.2.tgz) a try? If you're using node-red 1.2 or newer, you can upload  the .tgz via the palette manager.

Currently it's not stable enough, in my eyes, to publish it to flows.nodered.org.

Greets from Germany,
Benjamin

**Comment by Deggle** [comment]
Hi Benjamin,

Thanks for getting back to me. I've updated to the beta (I'm sure it's stable enough for what I'm currently using it for) and that has helped differentiate between an event being present or not with a single message.

However - if there are two matching events I do still think it would be useful to have the option to output a single message with an array as the payload rather than multiple distinct messages. It's much easier to split payloads if that's desired than it is combine them (I'm using a 'join' node with a 1 second timeout, which works fine but feels a bit clunky).

I appreciate you can't take on everyone's feature requests, but I'd be surprised if others wouldn't find this useful for some scenarios, so please do consider it.

Thanks for your great work on this project!

Kind regards,
Tim

**Comment by naimo84** [comment]
Hey, 

v1.0.0-beta.4 is ready for testing ;) https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.4/node-red-contrib-ical-events-1.0.0-beta.4.tgz

would you like to take a look at it?

Greetings,
Benjamin

**Comment by naimo84** [comment]
Hi,

I've released v1.1.0. May you have a look at it? 
If you like the node, leave it a star ⭐ Thanks.

And I'll close the issue for now, because I think it schould be solved. Feel free to reopen it.

Greetings,
Benjamin
