### ISSUE TITLE
The nodes do not properly detect all events through DAV 

### ISSUE THREAD

**Issue by e-lange** [naimo84/node-red-contrib-ical-events#85]
Hi folks,

**The issue:**
I use a private nextcloud instance (20.0.8) as CalDAV-server. Synchronization of calendars works perfectly between nextcloud, Android, macOS, IpadOS.
Yet, the ical-events nodes do seem to have issues properly detecting the scheduled events ahead. I do see events but these events are usually more in the future a couple of days ahead. But some of them are missing.
For instance: It is Tuesday and I do have a recurring event each work day. But the nodes only recognize the event at the weekend (which is also an recurring event btw.).

**I am running:**
- node-red-contrib-ical-events: 1.0.0-beta4
- node-red: 1.2.9
- nodejs: 12.21

**To Reproduce**
I extracted an event in iCal directly from nextcloud. To make sure the exported iCal event is reasonable I have exported it from nextcloud, deleted the event, imported it through calendar of macOS, and it went perfectly through.
However, same issue from node-red: The event is not detected.

Here is the iCal event (sorry for the wrong file extension!)
[F2B7DE8E-124E-4C92-8DDE-411368C0F306.ics](https://github.com/naimo84/node-red-contrib-ical-events/files/6266820/F2B7DE8E-124E-4C92-8DDE-411368C0F306.txt)

**Expected behavior**
Detect the events properly.

Let me know if you need more information and/or testing. I am happy to help.

**Comment by naimo84** [comment]
Hi @e-lange ,

sorry for the circumstances. I can reproduce your problem and will hopefully fix it soon. Please be patient ;)

Greets,
Benjamin

**Comment by naimo84** [comment]
If you like to test the newest beta version of my node, you can download a .tgz file from here https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.5/node-red-contrib-ical-events-1.0.0-beta.5.tgz

**Comment by e-lange** [comment]
Thx a lot for the quick response. I think we can close this one. However, I am still seeing issues, but with a different pattern. I will post a new issue.

**Comment by e-lange** [comment]
Close it.
