### ISSUE TITLE
Concurrent / overlapping events in different iCalDAV calenders not correctly detected

### ISSUE THREAD

**Issue by e-lange** [naimo84/node-red-contrib-ical-events#86]
**The issue**
I do have nextcloud running as caldav server. I am using a single account with multiple calendars.
Within the different calendars multiple events are scheduled. If these events are overlapping the nodes are reporting only one of the events but as often as there are concurrent events.

**Example**
![image](https://user-images.githubusercontent.com/58532249/115121430-082c1080-9fb3-11eb-9049-be6ca5257f53.png)

**In Node RED**
Simple sensor node (sorry, just a pic - but it is rather simple...)
![image](https://user-images.githubusercontent.com/58532249/115121473-390c4580-9fb3-11eb-8ee2-a7bdb73f3a2c.png)

**The corresponing debug output**
![image](https://user-images.githubusercontent.com/58532249/115121522-85f01c00-9fb3-11eb-9345-2feca2b454d8.png)

It reports the event "MittenDrin" three times.
If I now move away the event "MittenDrin"
![image](https://user-images.githubusercontent.com/58532249/115121636-1595ca80-9fb4-11eb-8085-5fdb6f704d20.png)
I get the following output from the debug node:
![image](https://user-images.githubusercontent.com/58532249/115121645-25151380-9fb4-11eb-9cc1-336b2082fa7a.png)

If I move away one of the remaining two events the node properly reports the last remaining event.

**Expected behavior**
Detect concurrent events and report them accordingly.

**I am running**
- node-red-contrib-ical-events: 1.0.0-beta5
- node-red: 1.3.1
- nodejs: 12.21
- nextcloud: 21.0.1.1 (caldav server)

**Additional context**
Let me know if you need more inputs / different descriptions / flows...
Cheers

**Comment by naimo84** [comment]
Hi @e-lange,

v1.0.0-beta.6 should fix this, sorry for the circumstances.
https://github.com/naimo84/node-red-contrib-ical-events/releases/download/v1.0.0-beta.6/node-red-contrib-ical-events-1.0.0-beta.6.tgz

Have a nice sunday,.

greets,
Benjamin
