### ISSUE TITLE
Trigger node emits identical message on start / end for different events

### ISSUE THREAD

**Issue by e-lange** [naimo84/node-red-contrib-ical-events#87]
**The trigger node emits identical messages when two events end and start at the same time**
It seems that in the case a caldav server provides multiple calendars the emitted messages at the two outputs point to the same message in case two events (in two calendars) end and start at the same time.
Is it possible that the emitted object is not a new JavaScript object for each new event but referencing only single object? (I am speculating here)

**To Reproduce**
1. Schedule two events in one account in different calendars
2. Match the start time of one event to exactly the end time of the other event
3. Use the trigger node and debug the output of the _Start_ and _End Message_ output of the node
4. The two messages are identical and seem to stem from only one of the two events

**Expected behavior**
The end message should match the event just ended and the start message should match the event just started. 

**Screenshots**
Two events matching start and end time in two calendars (_Studio_ & _Erdgeschoss_):
![grafik](https://user-images.githubusercontent.com/58532249/116935645-ef845180-ac66-11eb-9604-42735503649e.png)
![grafik](https://user-images.githubusercontent.com/58532249/116935696-01fe8b00-ac67-11eb-9ea5-663e40244744.png)

Trigger node:
![grafik](https://user-images.githubusercontent.com/58532249/116934168-e3979000-ac64-11eb-97da-a2419df16cc9.png)

And the debug messages (please node the subtle difference of the emitting node):
![grafik](https://user-images.githubusercontent.com/58532249/116934402-3cffbf00-ac65-11eb-824c-439ad36bfe44.png) 
![grafik](https://user-images.githubusercontent.com/58532249/116934500-5a348d80-ac65-11eb-8f07-eaddd5ab29a0.png)

Apparently, the messages do not differ and seem to stem from one calendar _Erdgeschoss_ only.

**Versions**
 - node-red-contrib-ical-events 1.0.0-beta.6
 - node-red 1.3.4
 - nodejs 12.22.1
 - nextcloud 21.0.1.1

**Additional**
As usual, if you need more info, more reproducers, more context, please let me know.

**Comment by e-lange** [comment]
Hi @naimo84,

thanks for the super quick response!

I just tried beta.7 and it does not seem to detect recurring events properly:
![grafik](https://user-images.githubusercontent.com/58532249/117057819-2ec1a980-ad1e-11eb-9afa-4b844d28bd94.png)


This is what I get with beta.6, which is the expected point in time for the trigger:
![grafik](https://user-images.githubusercontent.com/58532249/117057489-cf639980-ad1d-11eb-8b7e-8fdd527e9b2e.png)

Can you replicate this or do you need some ics-events?

Cheers

**Comment by naimo84** [comment]
Hey @e-lange,

you're most welcome ;)
I don't know why this changed between beta.6 and beta.7

Normally I'm testing with a Sogo Caldav server, this is working with both beta versions...
Now I switched to my nextcloud CalDav server, and I can reproduce your problem.

Sometimes it's really annoying, that each server interprets the ics/caldav "standard" differently 😉 

I'll investigate and will report back soon

Greets,
Benjamin

**Comment by naimo84** [comment]
Hey, I'm back 😁 

parenthesis are sometimes very useful 👍 

**(**ev.uid.uid ? ev.uid.uid : ev.uid**)** + eventStart.toISOString() + "start"
vs.
**ev.uid.uid ? ev.uid.uid : ev.uid** + eventStart.toISOString() + "start"

is definitly not the same ;)
Sorry for that... beta.8 is online

Greets

**Comment by e-lange** [comment]
Hi,

indeed, those parenthesis do have an impact :)
I just tested 1.0.0-beta.8 and it seems to work as expected. I will keep it running.

Great job! I will send you a coffee or a beer - which ever you prefer.

Cheers

**Comment by naimo84** [comment]
Hey @e-lange,

you are crazy, many many thanks for the ko-fi 😉
I will put it in my daughter's piggy bank.

and perhaps one beer 👍

cheers
