### ISSUE TITLE
Recurring appointments are not recognized

### ISSUE THREAD

**Issue by thunder-62** [naimo84/node-red-contrib-ical-events#88]
**Describe the bug**
flow recognizes normal appointments but fails to show a trigger on a recurring calendar entry

**To Reproduce**
set up a trigger node, no input, hourly check, trigger always, offset: 0, cron expression: 0 0 * * * * 
iCal Source: Nextcloud

normal appointment triggers the node
daily recurring appointment does not

**Expected behavior**
recurring events should trigger as well

**Screenshots**
N/A

**node-red-contrib-ical-events
 - Version 1.1.0
 - node-red version 1.03
 - nodejs version v10.24.1

**Additional context**
N/A

**Comment by naimo84** [comment]
Hi again @thunder-62, 

I did a quick dev test with my nextcloud instance. Unfortunately it's working here. 

So, there must be something "special" with your events ;) Can you give me some more informations?
Is it a allDay event?

Greets,
Benjamin

![2021-06-01 06_56_36-Juni 2021 - Kalender - Nextcloud - Brave](https://user-images.githubusercontent.com/11535502/120272116-cf1ed580-c2ac-11eb-8c6f-c91019b8f770.png)
![2021-06-01 06_55_14-Node-RED - Brave](https://user-images.githubusercontent.com/11535502/120272114-ce863f00-c2ac-11eb-9bc8-2db1795a179e.png)
![2021-06-01 06_56_22-Node-RED - Brave](https://user-images.githubusercontent.com/11535502/120272117-cf1ed580-c2ac-11eb-99fe-36d01faaf7a8.png)

**Comment by thunder-62** [comment]
I have to stand corrected.. It now works but I dont know why... maybe I am using the node incorrectly...  Would it be possible to get some more informeation regarding the cron expression and the number of checks?

**Comment by thunder-62** [comment]
BTW: I see you are from Bavaria as well ;-)

**Comment by thunder-62** [comment]
one last question It is probably described somewhere and I did not notice it correctly... Injecting a timestamp is just to trigger an additional calendar fetch?

**Comment by naimo84** [comment]
> one last question It is probably described somewhere and I did not notice it correctly... Injecting a timestamp is just to trigger an additional calendar fetch?

yes, injecting is currently used for triggering a new fetch. For some users, it's useful to implement the node into a bigger flow ;)
Only the sensor node is additionally looking for an ongoing current event.




> I have to stand corrected.. It now works but I dont know why... maybe I am using the node incorrectly... Would it be possible to get some more information regarding the cron expression and the number of checks?

I see, that I have to extend the Readme :/ I was planning to remove the cron setting, but I know that some wanted a more configurable way to setup the fetching of new events. So I have to extend the readme ^^

soooo: cron supersedes the "check every" setting. Configuring one of these is enough :)

As I wrote in the other issue: Checking every minute would be not necessary in most cases.
Checking every hour sounds ok, but I think it's might be also too often. If the events do not change frequently ;)

For testing and implementing new events, injecting a timestamp is very useful.

Greets,
Benjamin 

P.S. Und af boarisch: Servus aus Straubing 😁 I hoff, ma versteht mei Denglish ;)

**Comment by thunder-62** [comment]
Thanks for the info. I will remove the cron statement and will fetch every 12 h. Should I change anything in the calendar and need immediate re-fetching, I use the Injection node.

Thanks a lot...

Uwe

P.S. Servus aus der Hallertau Du schreibst perfektes Denglish
