### ISSUE TITLE
node-red crashing. ical issue?

### ISSUE THREAD

**Issue by thunder-62** [naimo84/node-red-contrib-ical-events#89]
**Describe the bug**
not certain whether this is related to his cpomponent but there is at least a reference to ~/.node-red/node_modules/dav/dav.js

**To Reproduce**
sorry sporadic since last update of this component

**Expected behavior**
no crashes ;-)

**Screenshots**
N/A

**node-red-contrib-ical-events
 - Version 1.1.0
 - node-red version 1.0.3
 - nodejs version v10.24.1

**Additional context**
crash trace. should this ring a bell pls. let me know. otherwise apologies and close the bug report...

Mai 31 18:44:30 smartPAF Node-RED[5434]: <--- Last few GCs --->
Mai 31 18:44:30 smartPAF Node-RED[5434]: [5434:0x3c18a70] 10548981 ms: Scavenge 213.9 (259.2) -> 208.9 (260.2) MB, 8.3 / 0.0 ms  (av                                    erage mu = 0.250, current mu = 0.250) allocation failure
Mai 31 18:44:30 smartPAF Node-RED[5434]: [5434:0x3c18a70] 10549467 ms: Scavenge 214.6 (260.2) -> 211.7 (260.2) MB, 6.3 / 0.0 ms  (av                                    erage mu = 0.250, current mu = 0.250) allocation failure
Mai 31 18:44:30 smartPAF Node-RED[5434]: [5434:0x3c18a70] 10549545 ms: Scavenge 218.1 (263.6) -> 213.2 (275.6) MB, 6.4 / 0.0 ms  (av                                    erage mu = 0.250, current mu = 0.250) allocation failure
Mai 31 18:44:30 smartPAF Node-RED[5434]: <--- JS stacktrace --->
Mai 31 18:44:30 smartPAF Node-RED[5434]: ==== JS stack trace =========================================
Mai 31 18:44:30 smartPAF Node-RED[5434]: 0: ExitFrame [pc: 0x333ab3bdbf1d]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 1: StubFrame [pc: 0x333ab3bcb576]
Mai 31 18:44:30 smartPAF Node-RED[5434]: Security context: 0x2939a5a9e6c1 <JSObject>
Mai 31 18:44:30 smartPAF Node-RED[5434]: 2: replace [0x2939a5a905c1](this=0x2f532a461da1 <String[44]: &quot;45fa30a4b32b9cec0b579566                                    22efb339&quot;>,0x2f532a461dc9 <JSRegExp <String[7]: &#?\w+;>>,0x22cf0ee02a09 <JSFunction entityReplacer (sfi = 0x2577f7ec8819)>)
Mai 31 18:44:30 smartPAF Node-RED[5434]: 3: parse [0x268406ea7f59] [/home/uhuttere/.node-red/node_modules/dav/dav.js:~6645] [pc=0x33                                    3a...
Mai 31 18:44:30 smartPAF Node-RED[5434]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap                                     out of memory
Mai 31 18:44:30 smartPAF Node-RED[5434]: 1: 0x8fb090 node::Abort() [node-red]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 2: 0x8fb0dc  [node-red]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 3: 0xb0336e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node-re                                    d]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 4: 0xb035a4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*,                                     bool) [node-red]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 5: 0xef7602  [node-red]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 6: 0xef7708 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node-re                                    d]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 7: 0xf037e2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8                                    ::GCCallbackFlags) [node-red]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 8: 0xf04114 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal:                                    :GarbageCollectionReason, v8::GCCallbackFlags) [node-red]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 9: 0xf06d81 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpa                                    ce, v8::internal::AllocationAlignment) [node-red]
Mai 31 18:44:30 smartPAF Node-RED[5434]: 10: 0xed69cb v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [                                    node-red]

**Comment by naimo84** [comment]
Hi @thunder-62,

dav.js maybe from my nodes ;) But I've never seen an OutOfMemory ;) 
How many entries/calendars do you have in your nextcloud? more or less 

I don't know exactly how dav.js is loading these entries. Maybe it loads the complete calendar into the memory and does the filtering afterwards :)

Greets,
Benjamin

**Comment by thunder-62** [comment]
Hmmm... about 10 events per day mostly recurring as I use the calendar to control daily actions in my smart home. Maybe the out of Memory is because of requesting too many updates in a short timeframe?

What are good parameters for the "check every" and cron entries?

I am afraid of simply stressing the system too much... Maybe the Nextcloud is not answering fast enough for the node to complete it's work?

**Comment by naimo84** [comment]
If the events do not change very often, like a waste calendar, I think a good parameter for check every is 6-12 hours. 
"daily actions in my smart home" sounds also like events, which do not change often.

Depends really on your need ;) checking every minute would be too often, cloud stress out the system indeed ;)

**Comment by thunder-62** [comment]
Thanks a lot for your support!

Cheers,
Uwe
