### ISSUE TITLE
Keine Daten von Owncloud-Kalender / Redmatic

### ISSUE THREAD

**Issue by vore** [naimo84/node-red-contrib-ical-events#91]
Hallo!
Ich habe vor zwei Tage auf die neueste Version 1.2.0 upgedated. Seit dem bekomme ich aber keine Werte mehr von meinem Kalender. Ich nutzt Owncloud mit dem Kalender-Addon mit dem Typ Caldav. Die Einstellungen sind die gleichen wie im IObroker (Pfad / Username/ Password). Der IObroker kann Daten lesen, ical-events liefert nur ein leeres Array zurück. Mit der alten Version hat es einwandfrei funktioniert. Im Log von Redmatic finde ich nur ein "erfolgreich gelesen". Ich nutze Redmatic  7.2.1.
Gruß
Volker

**Comment by naimo84** [comment]
Hallo Volker,

entschuldige bitte die Umstände. 
Kannst du mir ein paar Infos zu den Einstellungen liefern? 

Welchen Node nutzt du denn? upcoming/sensor/trigger?
Nutzt du einen Filter?
Ist es ein wiederkehrendes Event?
beim upcoming wären Preview/Pastview interessant.

Am einfachsten wäre ein Export der Nodes ;) Gerne auch per Mail.

Von welcher Version hast du geupdated?

Ich habe gerade einen schnellen Entwickler Test gegen meine OwncloudInstanz gemacht, da funktionierte alles :(

Danke und Grüße,
Benjamin

**Comment by vore** [comment]
Hallo!
Kein Problem.. ist bei uns allen nur ein Hobby :-) konnte es bisher erst einmal anders lösen.
Ich habe mal einen Test-Kalender angelegt und Fehler in meine Kalender auszuschließen, aber es bleibt bei dem Verhalten. 
Ich habe 4 Termine hintereinander eingetragen und nutze die "Upcomming-Node" ohne jeglichen Filter (jetzt zum Testen).
Das Update war auf die 1.2.0. Ich erinnere mich nicht welche vorher installiert war.. müsste aber max 1-2 Versionen darunter gewesen sein. Leider habe ich keine Möglichkeit gefunden, die ältere Version wieder zu installieren

Hier ein Export meiner Test-Nodes:

`[{"id":"6637879d.f6c898","type":"debug","z":"1352f11a.1a47bf","name":"Holidays","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1100,"y":740,"wires":[]},{"id":"4d30516e.fd86f","type":"inject","z":"1352f11a.1a47bf","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":830,"y":740,"wires":[["3dd63a7.784bd46"]]},{"id":"3dd63a7.784bd46","type":"ical-upcoming","z":"1352f11a.1a47bf","confignode":"da27228b.6cccb8","checkall":false,"cron":"","timeout":"0","timeoutUnits":"","name":"Owncloud","offset":"","endpreview":"","endpreviewUnits":"","preview":"1","previewUnits":"days","pastview":"","pastviewUnits":"days","trigger":"always","timezone":"","filter2":"","filter":"","x":960,"y":740,"wires":[["6637879d.f6c898"]]},{"id":"da27228b.6cccb8","type":"ical-config","url":"http://192.168.11.3/owncloud/remote.php/dav/calendars/owncloud/test/","caldav":"","caltype":"caldav","name":"Test OwnCloud","replacedates":false,"usecache":false,"username":"","includeTodo":false,"password":"","calendar":"","pastWeeks":"0","futureWeeks":"4"}]`

[Test.ics.zip](https://github.com/naimo84/node-red-contrib-ical-events/files/6689030/Test.ics.zip)

**Comment by naimo84** [comment]
Hallo ;)
Jap, leider nur ein Hobby ;)

Danke für's Teilen deines Test Flows. Dadurch bin ich auf ein spannendes Problem gestoßen. Ich konnte in der Tat nachvollziehen, dass mit deinem Flow ein leeres Array zurück geliefert wird. Allerdings nur wenn man "true" als msg.payload übergibt. Alles andere gibt bei mir ein korrektes Array zurück ;)

Für irgendein Issue hier auf Github habe ich den "Prüfzeitpunkt" via msg.payload konfiguierbar gemacht. Heißt, man kann einen beliebigen Timestamp übergeben und die Events des Kalender werden dagegen geprüft, nicht gegen das aktuelle Datum. Bisher leider ein undokumentiertes Feature ;) Welches erst mit einer der 1.0.0 Betas dazugekommen ist.

Das true/false zu so einem Ergebnis führt, hätte ich nicht gedacht... 

Hier ein kurzes jsFiddle https://jsfiddle.net/duxh054f/

Wird in deinem ursprünglichen Flow auch ein true übergeben, oder ist das nur der Testflow?

Grüße,
Benjamin

**Comment by vore** [comment]
Hallo!
Bisher wurde das über ein "True" gestartet. Habe es jetzt auf einen "Timestamp" umgestellt, dann passt es wieder. Danke für diese Info.. und ja.. die gute Doku.. keiner will sie aber ohne geht es irgendwie auch nicht. Kenne ich aus meinem Beruf. 
Danke!
Gruß
Volker
