### ISSUE TITLE
Fresh installation with "TypeError: Cannot read property 'getHours' of undefined"

### ISSUE THREAD

**Issue by Speeedy0815** [naimo84/node-red-contrib-ical-events#92]
Hi. I have a fresh installation and I only get:

"TypeError: Cannot read property 'getHours' of undefined"

as an arrormessage. And the node returns only an empty array.

Node red: 1.3.5
node-red-contrib-ical-events: 1.2.0
Raspberry Pi 4
 
What can I do? Do you need more information?

**Comment by naimo84** [comment]
Hi @Speeedy0815,

sorry for the circumstances. But yes, a bit more information would be useful :)
What type do you use? caldav/ical/icloud?
Do you include Todos? 

the javascript function getHours is only used on a few codesnippets.
![image](https://user-images.githubusercontent.com/11535502/123088458-09037780-d426-11eb-808b-2099cc21e3e6.png)
As you see, it's only applied on eventStart and eventEnd dates.
So this means, that one of your events has no start or end date. I even don't know, if this is possible ;)

A export of your flow and your ics would be nice 

Regards,
Benjamin

**Comment by Speeedy0815** [comment]
Thank you for your VERY fast Answer.

Here is the flow:

`[{"id":"c2f88460.232828","type":"ical-upcoming","z":"4d68f497.57c2ec","confignode":"74a6acea.dc4824","checkall":false,"cron":"","timeout":"0","timeoutUnits":"hours","name":"","offset":"","endpreview":"2","endpreviewUnits":"days","preview":"7","previewUnits":"days","pastview":"0","pastviewUnits":"days","trigger":"always","timezone":"","filterProperty":"summary","filterOperator":"between","filter2":"","filter":"","x":590,"y":1400,"wires":[["12564d30.86d573"]]},{"id":"12564d30.86d573","type":"debug","z":"4d68f497.57c2ec","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":850,"y":1400,"wires":[]},{"id":"eea8d605.15dbc8","type":"inject","z":"4d68f497.57c2ec","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":370,"y":1400,"wires":[["c2f88460.232828"]]},{"id":"74a6acea.dc4824","type":"ical-config","url":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","caldav":"false","caltype":"ical","name":"Geburtstagskalender","replacedates":false,"usecache":false,"username":"","includeTodo":false,"password":"","calendar":"","pastWeeks":"0","futureWeeks":"4"}]`

**Comment by Speeedy0815** [comment]
The link to the calender I'll not poste public.

**Comment by Speeedy0815** [comment]
I wrote you an mail with the calender.

**Comment by johanvh83** [comment]
Any solution for this issue? Have the same error

**Comment by Speeedy0815** [comment]
until yet, no. I wrote som mails with naimo84, but we don't found a solution.

**Comment by johanvh83** [comment]
Thanks Speedy0815 for your response. Get exactly the same error. I have the feeling that this contribution is very powerfull and usefull but as I have no 'programming skills' I have to rely on my self made knowledge. In this case the documentation is to basic for me. Unfortunately, I'm also not able to set it up in a proper way.

**Comment by naimo84** [comment]
Hey, unfortunately time is fleeting. kids are very time consuming 😁 

hopefully this helps a little bit to find the error: https://github.com/naimo84/node-red-contrib-ical-events/wiki/Debugging

Greets,
Benjamin

**Comment by Speeedy0815** [comment]
Thank you very much. I tested it right now. It's working!!!!
