### ISSUE TITLE
Can't find countdown.days anymore

### ISSUE THREAD

**Issue by RBN77** [naimo84/node-red-contrib-ical-events#96]
Hi, 

does the object "countdown.days" no longer exist ? Since I reinstalled my NodeRed I can't find the object anymore, maybe the change came with the new version ? Or do I have to install something else to see the object ? 

Thanks a lot

**Comment by naimo84** [comment]
Hi, 

sorry, I don't know why, but I've forgotten, to add the countdown property with v1.0.0-beta :/ 

I've readded it and published v1.2.4 ;)

Greets,
Benjamin
