### ISSUE TITLE
Timezone Option set "TypeError: date.getTime is not a function"

### ISSUE THREAD

**Issue by superbreadi** [naimo84/node-red-contrib-ical-events#97]
"Upcoming events" node error with setting timezone "TypeError: date.getTime is not a function"

**Steps to reproduce the behavior:**
1. Set timezone option (Europe/Berlin) in "upcoming events" node
2. Trigger flow
3. See error "TypeError: date.getTime is not a function"

**Expected behavior**
Normal operation. 
When timezone option is blank, no error

node-red-contrib-ical-events
 - Version 1.2.3
 - node-red version 2.0.2
 - nodejs version 14.17.3

**Comment by naimo84** [comment]
Hey @superbreadi, 

sorry for that... It was a mistake, I made with v1.2.3 ;)
Should be fixed in v1.2.4.

Greets,
Benjamin
