### ISSUE TITLE
msg.preview (number) and msg.previewUnits (Days) doesn't override value in ical node.

### ISSUE THREAD

**Issue by cholek3** [naimo84/node-red-contrib-ical-events#98]
**Describe the bug**
Upcoming node:
When "preview" values are set to i.e 2 Days in main ical node, it produces correct output. When inject node is set with "msg.preview = 2" and "msg.previewUnits: Days", ical node DOES NOT return any values (empty array) - See screenshot#1 and screenshot#2.

For reference purposes, I did the same for "hours". When "preview" values are set to i.e 29 hours in main ical node, it produces correct output. When inject node is set with "msg.preview = 29" and "msg.previewUnits: Hours", ical node DOES return correct values - See screenshot#3 and screenshot#4.

**To Reproduce**
1. inject: Set inject node with "msg.preview = number value" and "msg.previewUnits: Days" (screenshot#1 and screenshot#2)
2. config: see screenshot#5
3. output: screenshot#1 and screenshot#2 (issue) and screenshot#3 and screenshot#4 (correct)
4. See error: screenshot#1 (screenshot#3 for reference purposes)

**Expected behavior**
Upcoming node to output X amount of days of events, set in inject node (works fine with HOURS).

**Screenshots**
Screenshot#1:
![calendar_1](https://user-images.githubusercontent.com/43534386/127741154-3095a008-9378-43e8-aef4-6a0d288fce95.jpg)

Screenshot#2:
![calendar_1a](https://user-images.githubusercontent.com/43534386/127741180-82fa6736-0e6a-467a-a970-f542538e0212.jpg)

Working setup for reference purposes:
Screenshot#3:
![calendar_2](https://user-images.githubusercontent.com/43534386/127741190-e568ec0f-d005-41d7-9f3d-034bb0a3e3fa.jpg)

Screenshot#4:
![calendar_2a](https://user-images.githubusercontent.com/43534386/127741197-d76667c8-b24f-48c4-ad4f-971bbbb6504e.jpg)

Screenshot#5:
![calendar_3](https://user-images.githubusercontent.com/43534386/127741205-73d5528e-5a27-44db-a3cd-e20b6f7f7c3e.jpg)

**node-red-contrib-ical-events
 - Version 1.2.4
 - node-red version: 1.3.5
 - nodejs version

**Comment by naimo84** [comment]
Hey @cholek3 ,

should be fixed in the version pushed right now :)

Greets,
Benjamin

**Comment by cholek3** [comment]
Thank you for that.
If you don't mind I just have a quick question. 

Documentation mention we can use input messages, such as `msg.preview`, `msg.previewUnits`, etc, as well as `msg.trigger` and `msg.filter`. I am guessing `msg.trigger` can have property of "**Always**", "**Match**" or "**No match**" and `msg.filter` can have property of "**summary**", "**description**", "**attendee**", "**category**", "**start date**" and "**end date**"? 
But what if I set `msg.trigger` = **Match** and `msg.filter` = **start date**, what about filter Operator (**between**, **after**, **before**)? 
Can we set those via `msg` input?

And even if I set 
trigger=**Match**,
filter=**start date**, 
operator=**between**, 
after=**2021-08-06_00:00:00**, 
before=**2021-08-07_00:00:00** 
in the node itself, it will not display all day events on the 6th of August, only timed events.

Thank you. Nodes are great, really, just can't figure that out.
